<?php
/**
 * @file
 * Collect the SysAdmin modules
 *
 *
 * System administration menu.
 * Created on 2013.02.15.
 */

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the myntcd module
 */
function sysadminmenu_permission() {
	return array(
		'system administration' => array(
			'title' => t('System Administration')
		),
	);
} // function sysadminmenu_perm()

/**
 * sysadminmenu_menu: menus
 */
function sysadminmenu_menu() {
	$items['admin/config/sysadmin'] = array(
		'title' => 'System Administration',
		'description' => 'System Administration.',
		'position' => 'right',
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('system administration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);
	return $items;
} // function sysadminmenu_menu()
