<?php

/**
 * @file
 * Monitoring the users network traffic flow.
 *
 *
 * My Network Traffic Counter Daemon
 * Created / Modify on 2009.01.02. / 2013.02.22.
 */


/* ========== Main hook functions ========== */


/**
 * Implementation of hook_help().
 * Display help and module information
 * @param section which section of the site we're displaying help
 * @return text - help text for section
 */
// function myntcd_help($path, $arg) {
// 	$output = '';
// 	switch ($path) {
// 		case "admin/help#description":
// 			$output = t("My Network Traffic Counter Daemon");
// 		break;
// 	}
// 	return $output;
// } // function myntcd_help()


/**
 * Implementation of hook_init().
 * Connect the external database.
 */
function myntcd_init() {
	$myntcd_database = array(
	    'database' => variable_get('myntcd_db'),
	    'username' => variable_get('myntcd_user'),
	    'password' => variable_get('myntcd_pwd'),
	    'host' => variable_get('myntcd_server'),
	    'port' => variable_get('myntcd_port'),
	    'driver' => variable_get('myntcd_server_type'),
	  );
	  Database::addConnectionInfo('myntcd', 'default', $myntcd_database);
} // function myntcd_init


/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the myntcd module
 */
function myntcd_permission() {
	return array(
		'my traffic' => array(
			'title' => t('The user can view the traffic of your own.'),
		),
		'traffic manager' => array(
			'title' => t('Traffic manager'),
		),
		'traffic administer' => array(
			'title' => t('traffic administer'),
		),
		'myntcd administer' => array(
			'title' => t('myntcd administer'),
		),
	);
} // function myntcd_permission()


/**
 * Implements hook_menu().
 * @return the menu items.
 */
function myntcd_menu() {
	$items = array();

	//Administrator menus, System admin
	$items['admin/config/sysadmin/myntcd'] = array(
		'title' => 'Myntcd settings',
		'description' => 'Configure My Network Traffic Counter Daemon web base frontend',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_settings'),
		'access arguments' => array('myntcd administer'),
		'file' => 'myntcd.admin.inc',
	);

	// Sajat IP adatainak lekerdezese
	$items['my_traffic'] = array(
		'title' => 'My Traffic',
		'page callback' => 'myntcd_my_traffic',
		'access arguments' => array('my traffic'),
		'weight' => 0,
	);

	$items['my_traffic/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_my_traffic',
		'access arguments' => array('my traffic'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['my_traffic/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('daily'),
		'access arguments' => array('my traffic'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('weekly'),
		'access arguments' => array('my traffic'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('monthly'),
		'access arguments' => array('my traffic'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('yearly'),
		'access arguments' => array('my traffic'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// IP-k adminisztralasa
	$items['myntcd'] = array(
		'title' => 'Myntcd',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_search_form'),
		'access arguments' => array('traffic manager'),
		'weight' => 1,
		'type' => MENU_NORMAL_ITEM,
	);

	// IP-hez kapcsolodo kep megjelenitese
	$items['myntcd/img'] = array(
		'title' => 'Img',
		'page callback' => 'myntcd_img',
		'access arguments' => array('traffic manager'),
		'type' => MENU_CALLBACK,
		'weight' => 1,
	);

	// IP forgalmi adatai
	$items['myntcd/ip/%'] = array(
		'title' => '!ip',
		'title arguments' => array('!ip' => 2),
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 1,
		'type' => MENU_CALLBACK,
	);
	$items['myntcd/ip/%/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/ip/%/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// IP tartomanyok
	$items['myntcd/iprange'] = array(
		'title' => 'IP Ranges',
		'page callback' => 'myntcd_iprange',
		'access arguments' => array('traffic manager'),
		'weight' => 3,
		'type' => MENU_NORMAL_ITEM,
	);

	$items['myntcd/iprange/%'] = array(
		'title' => '!iprange',
		'title arguments' => array('!iprange' => 2),
		'page callback' => 'myntcd_iprange',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 3,
	);

	$items['myntcd/iprange/%/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_iprange',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_iprange',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_iprange',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_iprange',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// Top lista
	$items['myntcd/top'] = array(
		'title' => 'Top Lists',
		'page callback' => 'myntcd_top',
		'access arguments' => array('traffic manager'),
		'weight' => 5,
	);

	$items['myntcd/top/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_top',
		'access arguments' => array('traffic manager'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/top/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_top',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_top',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_top',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_top',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// IP cim szuresek kezelese
	$items['myntcd/filter'] = array(
		'title' => 'Filter',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_blacklist'),
		'access arguments' => array('traffic administer'),
		'weight' => 7,
	);

	$items['myntcd/filter/blacklist'] = array(
		'title' => 'Blacklist',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_blacklist'),
		'access arguments' => array('traffic administer'),
		'weight' => 2,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/filter/whitelist'] = array(
		'title' => 'Whitelist',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_whitelist'),
		'access arguments' => array('traffic administer'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/filter/new'] = array(
		'title' => 'Add filter',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_add'),
		'access arguments' => array('traffic administer'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	return $items;
} // function myntcd_menu()


/**
 * Implementation of hook_theme()
 * @return tomb
 */
function myntcd_theme() {
	return array(
		'myntcd_rrds' => array(
			'variables' => array(
				'ip' => NULL,
				'path' => NULL,
			),
		),
		'myntcd_tables' => array(
			'variables' => array(
				'rows' => NULL,
				'ip' => NULL,
				'when' => NULL,
				'start' => NULL,
				'stop' => NULL,
				'path' => NULL,
			),
		),
		'myntcd_filter_blacklist' => array(
			'render element' => 'form',
		),
		'myntcd_filter_whitelist' => array(
			'render element' => 'form',
		),
	);
} // function myntcd_theme()


/* ========== Form functions ========== */


/**
 * myntcd_my_traffic: sajat forgalom megjelenitese
 * @param when (daily/weekly/monthly/yearly)
 * @param date monthly eseten kapott datum
 * @return build tomb, amiben a tablazatok megjelenitesehez vannak infok
 */
function myntcd_my_traffic($when = '', $date = '') {
	// Kliens gep IP cime
	$my_ip = $_SERVER['REMOTE_ADDR'];

	$dates = _myntcd_getback_dates($when, $date, 'my_traffic');

	_myntcd_set_title('myip', $my_ip, $dates['start'], $dates['stop']);

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// $SQL = "SELECT * FROM filter WHERE ip = :ip AND date >= :date AND blacklist = 1";
	// $result = db_query($SQL, array(':ip' => $my_ip, ':date' => $dates['date']));

	$query = db_select('filter', 'f')
		->fields('f')
	  ->condition('ip', $my_ip)
	  ->condition('date', $dates['date'], '>=')
	  ->condition('blacklist', 1);
	$result = $query->execute();

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	// Ha feketelistan van az ipcim
	if ($filter = $result->fetchAssoc()) {
		drupal_set_message(
			t(
				'The IP address transfer blocking: !date',
				array('!date' => $filter['date'].' 23:59:59')
			),
			'warning'
		);
	}

	switch ($when) {
		case '':
			// Osszegzes kepernyo
			$build['myntcd_my_traffic'] = array(
			  '#theme' => 'myntcd_rrds',
			  '#ip' => $my_ip,
			  '#path' => 'my_traffic',
			);
			return $build;

			break;
		case 'daily': // Napi forgalom
			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			// A mai nap forgalmi adatai orankenti bontasban
			// $SQL = "SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM now ";
			// $SQL .= "WHERE ip = :ip AND date(date) = :date GROUP BY hour(date) ORDER BY date DESC";
			// $result = db_query($SQL, array(':ip' => $my_ip, ':date' => $dates['date']));

			$query = db_select('now', 'n')
				->fields('n', array('date'));
			$query->addExpression('SUM(in_byte)', 'in_byte');
			$query->addExpression('SUM(out_byte)', 'out_byte');
			$query
			  ->condition('ip', $my_ip)
			  ->where('DATE(date) = :date', array(':date' => $dates['date']))
			  ->groupBy('HOUR(date)')
			  ->orderBy('date', 'DESC');
			$result = $query->execute();

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			$link = FALSE;

			break;
		case 'weekly': // Heti forgalom
		case 'monthly': // Havi forgalom
			_myntcd_create_tmptable('myip', $dates['start'], $dates['stop'], $my_ip);

			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			// $SQL = "SELECT date, in_byte, out_byte FROM tmp_table ORDER BY date DESC";
			// $result = db_query($SQL);

			$query = db_select('tmp_table', 't')
				->fields('t', array('date', 'in_byte', 'out_byte'))
			  ->orderBy('date', 'DESC');
			$result = $query->execute();

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			$link = FALSE;

			break;
		case 'yearly': // Eves forgalom
			_myntcd_create_tmptable('myip', $dates['start'], $dates['stop'], $my_ip);

			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			// $SQL = "SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte ";
			// $SQL .= "FROM tmp_table GROUP BY month(date) ORDER BY date DESC";
			// $result = db_query($SQL);

			$query = db_select('tmp_table', 't')
				->fields('t', array('date'));
			$query->addExpression('SUM(in_byte)', 'in_byte');
			$query->addExpression('SUM(out_byte)', 'out_byte');
			$query
			  ->groupBy('MONTH(date)')
			  ->orderBy('date', 'DESC');
			$result = $query->execute();

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			$link = TRUE;

			break;
		default:
			drupal_goto('my_traffic');
			break;
	}

	// Tablazat sorainak elkeszitese
	$process_vars = array(
	  'path' => 'my_traffic',
	  'when' => $when,
	  'result' => $result,
	  'link' => $link,
	  'only_total' => FALSE,
	);
	$rows = _myntcd_process_tabledatas($process_vars);

	$build['myntcd_my_traffic'] = array(
	  '#theme' => 'myntcd_tables',
	  '#when' => $when,
	  '#rows' => $rows,
	  '#start' => $dates['start'],
	  '#stop' => $dates['stop'],
	  '#ip' => $my_ip,
	  '#path' => 'my_traffic',
	);
	return $build;
} // function myntcd_my_traffic()


/**
 * Keresesi oldal, ahol ip cimekre lehet keresni
 * @param form
 * @param form_state
 * @return form az oldal megjelenitesehez szukseges adatotkkal ter vissza
 */
function myntcd_search_form($form, &$form_state) {
	// ip kereses
	$form['ip'] = array(
		'#type' => 'textfield',
		'#title' => t('Ip address'),
		'#size' => 45,
		'#maxlength' => 39,
		'#required' => FALSE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Jump'),
	);

	return $form;
} // myntcd_search()


/**
 * Ha keresobe beirt ip cim validalasa
 * @param form
 * @param form_state
 */
function myntcd_search_form_validate($form, &$form_state) {
	if (!_myntcd_is_ip($form_state['values']['ip'])) {
		form_set_error('ip', t('Invalid IP address.'));
	}
} // myntcd_search_validate()


/**
 * myntcd_search_submit: az adott ip cim oldalara ugrik
 * @param form
 * @param form_state
 */
function myntcd_search_form_submit($form, &$form_state) {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// $SQL = "SELECT ip FROM now WHERE ip = :ip";
	// $result = db_query_range($SQL, 0, 1, array(':ip' => $form_state['values']['ip']));

	$query = db_select('now', 'n')
		->fields('n', array('ip'))
		->condition('ip', $form_state['values']['ip'])
	  ->range(0, 1);
	$result = $query->execute();

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	if ( $ip = $result->fetchAssoc()) {
		drupal_goto('myntcd/ip/'.$form_state['values']['ip']);
	}
} // myntcd_search_form_submit()


/**
 * myntcd_ip: IP traffic summary
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 * @param date kapott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_ip($ip, $when = '', $date = '') {
	if (_myntcd_is_ip($ip)) {

		$dates = _myntcd_getback_dates($when, $date, 'myntcd/ip/'.$ip);

		_myntcd_set_title('ip', $ip, $dates['start'], $dates['stop']);

		switch ($when) {
			case '':
				$build['myntcd_ip'] = array(
				  '#theme' => 'myntcd_rrds',
				  '#ip' => $ip,
				  '#path' => 'myntcd/ip/'.$ip,
				);
				return $build;

				break;
			case 'daily': // Napi forgalom
				// utolso nap masik tablaba van
				if ($dates['date'] == date('Y-m-d')) {
					$from = "now";
					$only_total = FALSE;
				} else {
					$from = "daily";
					// Ha nem aktualis nap van egyszerubb tablazat kell
					$only_total = TRUE;
				}
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				// A mai nap forgalmi adatai orankenti bontasban
				// $SQL = "SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet, ";
				// $SQL .= "SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM ".$from." ";
				// $SQL .= "WHERE ip = :ip AND date(date) = :date GROUP BY hour(date), type ORDER BY date DESC";
				// $result = db_query($SQL, array(':ip' => $ip, ':date' => $dates['date']));

				$query = db_select($from, 'nord')
					->fields('nord', array('date', 'type'));
				$query->addExpression('SUM(in_packet)', 'in_packet');
				$query->addExpression('SUM(out_packet)', 'out_packet');
				$query->addExpression('SUM(in_byte)', 'in_byte');
				$query->addExpression('SUM(out_byte)', 'out_byte');
				$query
				  ->condition('ip', $ip)
				  ->where('DATE(date) = :date', array(':date' => $dates['date']))
				  ->groupBy('HOUR(date)')
				  ->groupBy('type')
				  ->orderBy('date', 'DESC');
				$result = $query->execute();

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();

				$link = FALSE;

				break;
			case 'weekly': // Heti forgalom
			case 'monthly': // Havi forgalom
				_myntcd_create_tmptable('ip', $dates['start'], $dates['stop'], $ip);

				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				// $SQL = "SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet, ";
				// $SQL .= "SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table ";
				// $SQL .= "GROUP BY date, ip, type ORDER BY date DESC";
				// $result = db_query($SQL);

				$query = db_select('tmp_table', 't')
					->fields('t', array('date', 'type'));
				$query->addExpression('SUM(in_packet)', 'in_packet');
				$query->addExpression('SUM(out_packet)', 'out_packet');
				$query->addExpression('SUM(in_byte)', 'in_byte');
				$query->addExpression('SUM(out_byte)', 'out_byte');
				$query
				  ->groupBy('date')
				  ->groupBy('ip')
				  ->groupBy('type')
				  ->orderBy('date', 'DESC');
				$result = $query->execute();

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();

				$link = TRUE;
				$only_total = FALSE;

				break;
			case 'yearly': // Eves forgalom
				_myntcd_create_tmptable('ip', $dates['start'], $dates['stop'], $ip);

				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				// $SQL = "SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet, ";
				// $SQL .= "SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table ";
				// $SQL .= "GROUP BY month(date), ip, type ORDER BY date DESC";
				// $result = db_query($SQL);

				$query = db_select('tmp_table', 't')
					->fields('t', array('date', 'type'));
				$query->addExpression('SUM(in_packet)', 'in_packet');
				$query->addExpression('SUM(out_packet)', 'out_packet');
				$query->addExpression('SUM(in_byte)', 'in_byte');
				$query->addExpression('SUM(out_byte)', 'out_byte');
				$query
				  ->groupBy('MONTH(date)')
				  ->groupBy('ip')
				  ->groupBy('type')
				  ->orderBy('date', 'DESC');
				$result = $query->execute();

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();

				$link = TRUE;
				$only_total = FALSE;

				break;
		}

		// Tablazat sorainak elkeszitese
		$process_vars = array(
		  'path' => 'myntcd/ip',
		  'when' => $when,
		  'result' => $result,
		  'ip' => $ip,
		  'link' => $link,
		  'only_total' => $only_total,
		);
		$rows = _myntcd_process_tabledatas($process_vars);

		$build['myntcd_ip'] = array(
		  '#theme' => 'myntcd_tables',
		  '#when' => $when,
		  '#rows' => $rows,
		  '#start' => $dates['start'],
		  '#stop' => $dates['stop'],
		  '#ip' => $ip,
		  '#path' => 'myntcd/ip',
		);
		return $build;
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip()


/**
 * Ip tartomanyok megjelenitese
 * @param iprange adott ip tartomany
 * @param when (daily/weekly/monthly/yearly)
 * @param date datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_iprange($iprange = '', $when = '', $date = '') {
	if ($iprange == '' && $when == '') {
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		// IP tartomanyok listazasa
		// $SQL = "SELECT iprange FROM ipranges ORDER BY iprange ASC";
		// $result = db_query($SQL);

		$query = db_select('ipranges', 'i')
			->fields('i', array('iprange'))
			->orderBy('iprange', 'ASC');
		$result = $query->execute();

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$rows = array();
		$rows[] = array(
			array('data' => l(t('All'), 'myntcd/iprange/all') ),
			array('data' => l(t('Daily'), 'myntcd/iprange/all') ),
			array('data' => l(t('Weekly'), 'myntcd/iprange/all/weekly') ),
			array('data' => l(t('Monthly'), 'myntcd/iprange/all/monthly') ),
			array('data' => l(t('Yearly'), 'myntcd/iprange/all/yearly') ),
		);

		while ($row = $result->fetchAssoc()) {
			if ( _myntcd_is_ip($row['iprange']) ) {
				$rows[] = array(
					array('data' => l($row['iprange'], 'myntcd/iprange/'.$row['iprange']) ),
					array('data' => l(t('Daily'), 'myntcd/iprange/'.$row['iprange']) ),
					array('data' => l(t('Weekly'), 'myntcd/iprange/'.$row['iprange'].'/weekly') ),
					array('data' => l(t('Monthly'), 'myntcd/iprange/'.$row['iprange'].'/monthly') ),
					array('data' => l(t('Yearly'), 'myntcd/iprange/'.$row['iprange'].'/yearly') ),
				);
			}
		}

		$dates['start'] = '';
		$dates['stop'] = '';
		$path = 'myntcd/iprange_list';

	} elseif (_myntcd_is_ip($iprange) || $iprange == 'all') {

		if ($when == '') {
			$when = 'daily';
		}

		$dates = _myntcd_getback_dates($when, $date, 'myntcd/iprange/'.$iprange);

		_myntcd_set_title('iprange', $iprange, $dates['start'], $dates['stop']);

		switch ($when) {
			case 'daily': // Napi forgalom
				if ($dates['date'] == date('Y-m-d')) {
					$nowordaily = "now";
				} else {
					$nowordaily = "daily";
				}

				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				if ($iprange == 'all') {
					// $SQL = "SELECT ipranges.ipr_id, ipranges.iprange, SUM($nowordaily.in_byte) AS in_byte, ";
					// $SQL .= "SUM($nowordaily.out_byte) AS out_byte, SUM($nowordaily.in_byte) + SUM($nowordaily.out_byte) AS total ";
					// $SQL .= "FROM $nowordaily, ipranges WHERE ipranges.ipr_id = $nowordaily.ipr_id AND date($nowordaily.date) = :date ";
					// $SQL .= "GROUP BY ipranges.ipr_id ORDER BY $nowordaily.ip";
					// $result = db_query($SQL, array(':date' => $dates['date']));

					$query = db_select($nowordaily, 'nord');
					$query->join('ipranges', 'i', 'i.ipr_id = nord.ipr_id');
					$query->fields('i', array('ipr_id', 'iprange'));
					$query->addExpression('SUM(nord.in_byte)', 'in_byte');
					$query->addExpression('SUM(nord.out_byte)', 'out_byte');
					$query->addExpression('SUM(nord.in_byte) + SUM(nord.out_byte)', 'total');
					$query
					  ->where('DATE(nord.date) = :date', array(':date' => $dates['date']))
					  ->groupBy('i.ipr_id')
					  ->orderBy('nord.ip');
					$result = $query->execute();
				} else {
					// IP tartomanyhoz tartozo napi forgalom
					// $SQL = "SELECT ipranges.iprange, $nowordaily.ip, SUM($nowordaily.in_byte) AS in_byte, ";
					// $SQL .= "SUM($nowordaily.out_byte) AS out_byte, SUM($nowordaily.in_byte) + SUM($nowordaily.out_byte) AS total ";
					// $SQL .= "FROM $nowordaily, ipranges WHERE ipranges.ipr_id = $nowordaily.ipr_id AND date($nowordaily.date) = :date AND ipranges.iprange = :iprange ";
					// $SQL .= "GROUP BY $nowordaily.ip ORDER BY total DESC";
					// $result = db_query($SQL, array(':date' => $dates['date'], ':iprange' => $iprange));

					$query = db_select($nowordaily, 'nord');
					$query->join('ipranges', 'i', 'i.ipr_id = nord.ipr_id');
					$query
						->fields('i', array('iprange'))
						->fields('nord', array('ip'));
					$query->addExpression('SUM(nord.in_byte)', 'in_byte');
					$query->addExpression('SUM(nord.out_byte)', 'out_byte');
					$query->addExpression('SUM(nord.in_byte) + SUM(nord.out_byte)', 'total');
					$query
					  ->where('DATE(nord.date) = :date', array(':date' => $dates['date']))
					  ->condition('i.iprange', $iprange)
					  ->groupBy('nord.ip')
					  ->orderBy('total', 'DESC');
					$result = $query->execute();
				}

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
				break;
			case 'weekly': // Heti forgalom
			case 'monthly': // Havi forgalom
			case 'yearly': // Eves forgalom
				_myntcd_create_tmptable('iprange', $dates['start'], $dates['stop'], $iprange);

				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				if ($iprange == 'all') {
					// $SQL = "SELECT ipranges.ipr_id, ipranges.iprange, SUM(tmp_table.in_byte) AS in_byte, ";
					// $SQL .= "SUM(tmp_table.out_byte) AS out_byte, SUM(tmp_table.in_byte) + SUM(tmp_table.out_byte) AS total ";
					// $SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id ";
					// $SQL .= "GROUP BY ipranges.ipr_id ORDER BY tmp_table.ip";
					// $result = db_query($SQL);

					$query = db_select('tmp_table', 't');
					$query->join('ipranges', 'i', 'i.ipr_id = t.ipr_id');
					$query->fields('i', array('ipr_id', 'iprange'));
					$query->addExpression('SUM(t.in_byte)', 'in_byte');
					$query->addExpression('SUM(t.out_byte)', 'out_byte');
					$query->addExpression('SUM(t.in_byte) + SUM(t.out_byte)', 'total');
					$query
					  ->groupBy('i.ipr_id')
					  ->orderBy('t.ip');
					$result = $query->execute();
				} else {
					// $SQL = "SELECT ipranges.iprange, tmp_table.ip, SUM(tmp_table.in_byte) AS in_byte, SUM(tmp_table.out_byte) AS out_byte, ";
					// $SQL .= "SUM(tmp_table.in_byte) + SUM(tmp_table.out_byte) AS total ";
					// $SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id AND ipranges.iprange = :iprange ";
					// $SQL .= "GROUP BY tmp_table.ip ORDER BY total DESC";
					// $result = db_query($SQL, array(':iprange' => $iprange));

					$query = db_select('tmp_table', 't');
					$query->join('ipranges', 'i', 'i.ipr_id = t.ipr_id');
					$query
						->fields('i', array('iprange'))
						->fields('t', array('ip'));
					$query->addExpression('SUM(t.in_byte)', 'in_byte');
					$query->addExpression('SUM(t.out_byte)', 'out_byte');
					$query->addExpression('SUM(t.in_byte) + SUM(t.out_byte)', 'total');
					$query
					  ->condition('i.iprange', $iprange)
					  ->groupBy('t.ip')
					  ->orderBy('total', 'DESC');
					$result = $query->execute();
				}

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
				break;
		}

		if ($iprange == 'all') {
			$process_vpath = 'myntcd/iprange/all';
		} else {
			$process_vpath = 'myntcd/iprange';
		}

		// Tablazat sorainak elkeszitese
		$process_vars = array(
		  'path' => $process_vpath,
		  'when' => $when,
		  'result' => $result,
		  'date' => $date,
		  'link' => TRUE,
		);
		$rows = _myntcd_process_tabledatas($process_vars);

		$path = 'myntcd/iprange';

	} else {
		drupal_goto('myntcd/iprange');
	}

	$build['myntcd_iprange'] = array(
	  '#theme' => 'myntcd_tables',
	  '#when' => $when,
	  '#rows' => $rows,
	  '#start' => $dates['start'],
	  '#stop' => $dates['stop'],
	  '#ip' => $iprange,
	  '#path' => $path,
	);
	return $build;
} // function myntcd_iprange()


/**
 * Toplistak
 * @param when (daily/weekly/monthly/yearly)
 * @param date datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_top($when = '', $date = '') {
	if($when == '') {
		_myntcd_create_tmptable('top', date('Y-01-01'), date('Y-m-d'));

		$array_when = array('daily', 'weekly', 'monthly', 'yearly');
		foreach ($array_when as $when) {
			$dates = _myntcd_getback_dates($when, $date, 'myntcd/top');

			switch ($when) {
				case 'daily': // Napi forgalom
					// Kapcsolodas az SQL szerverhez
					db_set_active('myntcd');

					// Napi Top lista
					// $SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
					// $SQL .= "FROM now WHERE date(date) = :date GROUP BY ip, date(date) ORDER BY total DESC";
					// $result = db_query_range($SQL, 0, 20, array(':date' => $dates['date']));

					$query = db_select('now', 'n')
						->fields('n', array('ip'));
					$query->addExpression('SUM(in_byte)', 'in_byte');
					$query->addExpression('SUM(out_byte)', 'out_byte');
					$query->addExpression('SUM(in_byte) + SUM(out_byte)', 'total');
					$query
					  ->where('DATE(date) = :date', array(':date' => $dates['date']))
					  ->groupBy('ip')
					  ->groupBy('DATE(date)')
					  ->orderBy('total', 'DESC')
					  ->range(0, 20);
					$result = $query->execute();

					// Vissza valtas az alapertelmezett SQL szerverhez
					db_set_active();
					break;
				case 'weekly': // Heti forgalom
				case 'monthly': // Havi forgalom
				case 'yearly': // Eves forgalom
					// Kapcsolodas az SQL szerverhez
					db_set_active('myntcd');

					// $SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
					// $SQL .= "FROM tmp_table WHERE date >= :start AND date <= :stop GROUP BY ip  ORDER BY total DESC";
					// $result = db_query_range($SQL, 0, 20, array(':start' => $dates['start'], ':stop' => $dates['stop']));

					$query = db_select('tmp_table', 't')
						->fields('t', array('ip'));
					$query->addExpression('SUM(in_byte)', 'in_byte');
					$query->addExpression('SUM(out_byte)', 'out_byte');
					$query->addExpression('SUM(in_byte) + SUM(out_byte)', 'total');
					$query
					  ->condition('date', $dates['start'], '>=')
					  ->condition('date', $dates['stop'], '<=')
					  ->groupBy('ip')
					  ->orderBy('total', 'DESC')
					  ->range(0, 20);
					$result = $query->execute();

					// Vissza valtas az alapertelmezett SQL szerverhez
					db_set_active();
					break;
			}

			// Tablazat sorainak elkeszitese
			$process_vars = array(
			  'path' => 'myntcd/top',
			  'when' => $when,
			  'result' => $result,
			  'date' => $date,
			  'link' => TRUE,
			);
			$tables[$when] = _myntcd_process_tabledatas($process_vars);
		}

		$dates['start'] = '';
		$dates['stop'] = '';
		$path = 'myntcd/top_all';

	} else {

		$dates = _myntcd_getback_dates($when, $date, 'myntcd/top');

		_myntcd_set_title('top', t(ucfirst($when)), $dates['start'], $dates['stop']);

		_myntcd_create_tmptable('top', $dates['start'], $dates['stop']);

		$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total');
		foreach ($traffic as $order_by => $table) {
			switch ($when) {
				case 'daily': // Napi forgalom
					// Napnak megfelelo adatbazis kivalasztasa
					if ($dates['date'] == date('Y-m-d')) {
						$from = "now";
					} else {
						$from = "daily";
					}

					// Kapcsolodas az SQL szerverhez
					db_set_active('myntcd');

					// Napi Top lista
					// $SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
					// $SQL .= "FROM ".$from." WHERE date(date) = :date GROUP BY ip, date(date) ORDER BY ".$order_by." DESC";
					// $result = db_query_range($SQL, 0, 20, array(':date' => $dates['date']));

					$query = db_select($from, 'nord')
						->fields('nord', array('ip'));
					$query->addExpression('SUM(in_byte)', 'in_byte');
					$query->addExpression('SUM(out_byte)', 'out_byte');
					$query->addExpression('SUM(in_byte) + SUM(out_byte)', 'total');
					$query
					  ->where('DATE(date) = :date', array(':date' => $dates['date']))
					  ->groupBy('ip')
					  ->groupBy('DATE(date)')
					  ->orderBy($order_by, 'DESC')
					  ->range(0, 20);
					$result = $query->execute();

					// Vissza valtas az alapertelmezett SQL szerverhez
					db_set_active();
					break;
				case 'weekly': // Heti forgalom
				case 'monthly': // Havi forgalom
				case 'yearly': // Eves forgalom
					// Kapcsolodas az SQL szerverhez
					db_set_active('myntcd');

					// $SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
					// $SQL .= "FROM tmp_table GROUP BY ip ORDER BY ".$order_by." DESC";
					// $result = db_query_range($SQL, 0, 20);

					$query = db_select('tmp_table', 't')
						->fields('t', array('ip'));
					$query->addExpression('SUM(in_byte)', 'in_byte');
					$query->addExpression('SUM(out_byte)', 'out_byte');
					$query->addExpression('SUM(in_byte) + SUM(out_byte)', 'total');
					$query
					  ->groupBy('ip')
					  ->orderBy($order_by, 'DESC')
					  ->range(0, 20);
					$result = $query->execute();

					// Vissza valtas az alapertelmezett SQL szerverhez
					db_set_active();
					break;
			}

			// Tablazat sorainak elkeszitese
			$process_vars = array(
			  'path' => 'myntcd/top',
			  'when' => $when,
			  'result' => $result,
			  'date' => $date,
			  'link' => TRUE,
			);
			$tables[$table] = _myntcd_process_tabledatas($process_vars);
		}

		$path = 'myntcd/top';
	}

	$build['myntcd_top'] = array(
	  '#theme' => 'myntcd_tables',
	  '#when' => $when,
	  '#rows' => $tables,
	  '#start' => $dates['start'],
	  '#stop' => $dates['stop'],
	  '#ip' => '',
	  '#path' => $path,
	);
	return $build;
} // function myntcd_top()


/**
 * A feketelistan levo ip cimek megjelenitese
 * @param form
 * @param form_state
 * @return egy segedfugvenyt hiv meg
 */
function myntcd_filter_blacklist($form, &$form_state) {
	return _myntcd_filter_bwform(1);
} // function myntcd_filter_blacklist()


/**
 * A feketelistan elvegzett modositasokat dolgozza fel
 * @param form
 * @param form_state
 */
function myntcd_filter_blacklist_submit($form, &$form_state) {
	_myntcd_filter_bwsubmit($form_state);
} // function myntcd_filter_blacklist_submit()


/**
 * A feherlistan levo ip cimek megjelenitese
 * @param form
 * @param form_state
 * @return egy segedfugvenyt hiv meg
 */
function myntcd_filter_whitelist($form, &$form_state) {
	return _myntcd_filter_bwform(0);
} // function myntcd_filter_whitelist()


/**
 * A feherlistan elvegzett modositasokat dolgozza fel
 * @param form
 * @param form_state
 */
function myntcd_filter_whitelist_submit($form, &$form_state) {
	_myntcd_filter_bwsubmit($form_state);
} // function myntcd_filter_whitelist_submit()


/**
 * Fel lehet venni a feher es fekete listakra ip cimeket
 * @param form
 * @param form_state
 * @return form az oldal megjelenitesehez szukseges adatotkkal ter vissza
 */
function myntcd_filter_add($form, &$form_state) {
	$form['filter_ip'] = array(
		'#type' => 'textfield',
		'#title' => t('IP Address'),
		'#size' => 20,
		'#maxlength' => 39,
		'#required' => TRUE,
	);

	$form['filter_type'] = array(
		'#type' => 'select',
		'#title' => t('Type'),
		'#options' => array(1 => t('Blacklist'), 0 => t('Whitelist')),
		'#required' => FALSE,
	);

	$form['filter_time'] = array(
		'#type' => 'radios',
		'#title' => t('Time interval'),
		'#default_value' => '1',
		'#options' => array(
		    '1' => t('day'),
		    '7' => t('week'),
		    '30' => t('month'),
		    '-1' => t('for ever')
		),
		'#required' => FALSE,
	);

	$form['filter_time_interval'] = array(
		'#type' => 'textfield',
		'#default_value' => '1',
		'#size' => 20,
		'#required' => TRUE,
	);

	$form['filter_comment'] = array(
		'#type' => 'textfield',
		'#title' => t('Comment'),
		'#size' => 20,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save')
	);

	return $form;
} // function myntcd_filter_add()


/**
 * A filter oldalon megadott adatokat validalja
 * @param form
 * @param form_state
 */
function myntcd_filter_add_validate($form, &$form_state) {
	if (!_myntcd_is_ip($form_state['values']['filter_ip'])) {
		form_set_error('filter_ip', t('Invalid IP address.'));
	}
	if (!is_numeric($form_state['values']['filter_time_interval'])) {
		form_set_error('filter_time_interval', t('Time interval is not numeric.'));
	}
} // function myntcd_filter_add_validate()


/**
 * Feldolgozza a valtozasokat
 * @param form
 * @param form_state
 */
function myntcd_filter_add_submit($form, &$form_state) {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// $sqlvalues = array(
	// 	':ip' => $form_state['values']['filter_ip'],
	// 	':blacklist' => $form_state['values']['filter_type'],
	// 	':comment' => $form_state['values']['filter_comment'],
	// );

	// $SQL = "INSERT INTO filter (ip, blacklist, comment, date) VALUES (:ip, :blacklist, :comment, ";
	// if ($form_state['values']['filter_time'] == '-1') {
	// 	$SQL .= "DEFAULT)";
	// } else {
	// 	$filtertime = $form_state['values']['filter_time'] * $form_state['values']['filter_time_interval'];
	// 	$filtertime = date('Y-m-d', strtotime('+'.$filtertime.' day'));

	// 	$SQL .= ":date)";
	// 	$sqlvalues[':date'] = $filtertime;
	// }

	// db_query($SQL, $sqlvalues);

	$sqlvalues = array(
	    'ip' => $form_state['values']['filter_ip'],
	    'blacklist' => $form_state['values']['filter_type'],
	    'comment' => $form_state['values']['filter_comment'],
	);

	if ($form_state['values']['filter_time'] != '-1') {
		$filtertime = $form_state['values']['filter_time'] * $form_state['values']['filter_time_interval'];
		$filtertime = date('Y-m-d', strtotime('+'.$filtertime.' day'));

		$sqlvalues['date'] = $filtertime;
	}

	$query = db_insert('filter')
	  ->fields($sqlvalues)
		->execute();

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();
} // function myntcd_filter_add_submit()


/**
 * myntcd_img: rrd grafikont jelenit meg egy adott ip-hez
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 * @param start forgalmi adatok kezdeti ideje
 * @param stop forgalmi adatok befejezesi ideje
 */
function myntcd_img($ip, $when, $start = '', $stop = '') {
	// Utolso idopont meghatarozasa
	if ($stop == '') {
		if ($when == 'daily') {
			if ($start != '' && strtotime($start) < strtotime('now')) {
				$stop = strtotime('+1 day', strtotime($start));
			} else {
				$stop = strtotime('now');
			}
		} else {
			$stop = strtotime('now');
		}
	} else {
		if ($when != 'yearly') {
			$stop = strtotime($stop.' 23:59:59');
		} else {
			$stop = strtotime($stop);
		}
	}
	if ($start != '') {
		$start = strtotime($start);
	}
	// Kep tipusanak megfelelo kezdesi idopont meghatarozasa
	switch ($when) {
		default:
		case 'daily':
			if ($start == '') {
				$start = strtotime('-1 day', $stop);
				$title = $ip.' ('.date('Y-m-d', $stop).')';
			} else {
				$title = $ip.' ('.date('Y-m-d', $start).')';
			}
		break;
		case 'weekly':
			if ($start == '') {
				$start = strtotime('-1 week +1 day', $stop);
			}
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $stop).')';
		break;
		case 'monthly':
			if ($start == '') {
				$start = strtotime('-1 month', $stop);
			}
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $stop).')';
		break;
		case 'yearly':
			if ($start == '') {
				$start = strtotime('-1 year', $stop);
			}
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $stop).')';
		break;
	}
	// Kep elkeszitese
	$img = _myntcd_get_rrd_image_myntcd($ip, $title, $start, $stop);
} // function myntcd_img


/* ========== Theme functions ========== */


/**
 * theme_myntcd_rrds: IP traffic RRDs
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return adott oldallal ter vissza
 */
function theme_myntcd_rrds($variables) {
	$ip = $variables['ip'];
	$path = $variables['path'];
	$output = '';

	$array_when = array('daily', 'weekly', 'monthly', 'yearly');
	foreach ($array_when as $when) {
		$output .= '<div class="myntcd_rrd_img">';
		$output .= l(
			'<img src="'.url('myntcd/img/'.$ip.'/'.$when).'" alt="myntcd_'.$when.'_image" />',
			$path.'/'.$when,
			array('html' => TRUE)
		);
		$output .= '</div>';
	}

	return $output;
} // function theme_myntcd_rrds


/**
 * theme_myntcd_tables: egyseges theme a tablazatoknak
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return adott oldallal ter vissza
 */
function theme_myntcd_tables($variables) {

	$ip = $variables['ip'];
	$when = $variables['when'];
	$rows = $variables['rows'];
	$start = $variables['start'];
	$stop = $variables['stop'];
	$path = $variables['path'];

	$output = '';

	if ($path == 'myntcd/ip' || $path == 'myntcd/iprange' || $path == 'myntcd/top') {
		$output .= _myntcd_navigation($ip, $when, $start, $stop, $path);
	}
	if ($path == 'myntcd/ip' || $path == 'my_traffic') {
		$output .= '<div class="myntcd_rrd_img">';
		$output .= '<img src="'.url('myntcd/img/'.$ip.'/'.$when.'/'.$start.'/'.$stop).'" alt="myntcd_'.$when.'_image" />';
		$output .= '</div>';
	}

	if ($path == 'myntcd/ip') {
		$header = array(
			array('data' => t('Time')),
			array('data' => t('Type')),
			array('data' => t('In Packet'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out Packet'), 'class' => 'myntcd_header_right'),
			array('data' => t('Total Packet'), 'class' => 'myntcd_header_right'),
			array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
		);
	} elseif ($path == 'myntcd/iprange_list') {
		$header = array(
			array('data' => t('IP Address')),
			array('data' => t('Operations'), 'colspan' => '4'),
		);
	} else {
		if ($path == 'my_traffic') {
			$first_column = 'Time';
		} else {
			$first_column = 'IP Address';
		}

		$header = array(
			array('data' => t($first_column)),
			array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
		);
	}

	if ($path == 'myntcd/top_all') {
		$array_when = array('daily', 'weekly', 'monthly', 'yearly');
		foreach ($array_when as $when) {
			$output .= '<div class = "myntcd_top_label">';
			$output .= t('!when Top !num total byte', array('!when' => t(ucfirst($when)), '!num' => '20'));
			$output .= ':</div>';

			$output .= '<div class = "myntcd_top_table">';
			$output .= theme('table', array('header' => $header, 'rows' => $rows[$when], 'empty' => t('No content available.')));
			$output .= '</div>';
		}
	} elseif ($path == 'myntcd/top') {
		$traffic = array('in', 'out', 'total');
		foreach ($traffic as $table) {
			$output .= '<div class = "myntcd_top_label">';
			$output .= t(' Top !num !table byte', array('!num' => '20', '!table' => t($table)));
			$output .= ':</div>';

			$output .= '<div class = "myntcd_top_table">';
			$output .= theme('table', array('header' => $header, 'rows' => $rows[$table], 'empty' => t('No content available.')));
			$output .= '</div>';
		}
	} else {
		if ($path == 'myntcd/iprange') {
			$output .= '<div class = "myntcd_top_table">';
		}
		$output .= theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No content available.')));
		if ($path == 'myntcd/iprange') {
			$output .= '</div>';
		}
	}

	return $output;
} // function theme_myntcd_tables()


/**
 * A feketelista megjelenitse
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return egy segedfugvenyt hiv meg
 */
function theme_myntcd_filter_blacklist($variables) {
	return _myntcd_filter_tables($variables);
} // function theme_myntcd_filter_blacklist()


/**
 * A feherlista megjelenitse
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return egy segedfugvenyt hiv meg
 */
function theme_myntcd_filter_whitelist($variables) {
	return _myntcd_filter_tables($variables);
} // function theme_myntcd_filter_whitelist()


/* ========== Own functions ========== */


/**
 * Ellenorzi az ip formatumot
 * @param ip text
 * @return boolean
 */
function _myntcd_is_ip($ip) {
	$num = "(25[0-5]|2[0-4]\d|[01]?\d\d|\d)";
	//$num = "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)";

	$ipv4regexp = "/^$num\.$num\.$num\.$num$/";

	$ipv6regexp = "/^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|";
	$ipv6regexp .= "((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|";
	$ipv6regexp .= ":((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(:(((:[0-9A-Fa-f]{1,4}){1,7})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/";

	if (preg_match($ipv4regexp, $ip)) {
		return 1;
	} elseif (preg_match($ipv6regexp, $ip)) {
		return 1;
	} else {
		return 0;
	}
} // function _myntcd_is_ip()


/**
 * Adott idointervallumnak megfelelo datumokkal ter vissza
 * @param when (daily/weekly/monthly/yearly)
 * @param date monthly eseten kapott datum
 * @return dates
 */
function _myntcd_getback_dates($when, $date, $path) {
	if ($date == '') {
		switch ($when) {
			case '':
			case 'daily':
			case 'weekly':
				$date = date('Y-m-d');
				break;
			case 'monthly':
				$date = date('Y-m-01');
				break;
			case 'yearly':
				$date = date('Y-01-01');
				break;
		}
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto($path.'/'.$when);
	}

	switch ($when) {
		case '':
			$dates['date'] = $date;
			$dates['start'] = '';
			$dates['stop'] = '';
			break;
		case 'daily':
			$dates['date'] = $date;
			$dates['start'] = $date;
			$dates['stop'] = '';
			break;
		case 'weekly':
			$dates['date'] = $date;
			$dates['start'] = date('Y-m-d', strtotime($date.' -1 week +1 day'));
			$dates['stop'] = $date;
			break;
		case 'monthly':
			$dates['date'] = date('Y-m-d');
			$dates['start'] = $date;

			if (strtotime('now') < strtotime($date.' +1 month')) {
				$dates['stop'] = date('Y-m-d');
			} else {
				$dates['stop'] = date('Y-m-d', strtotime($date.' +1 month -1 day'));
			}
			break;
		case 'yearly':
			$dates['date'] = date('Y-m-d');

			if (strtotime(date('Y')) > strtotime(date('Y', strtotime($date)))) {
				$dates['start'] = date('Y', strtotime($date)).'-01-01';
				$dates['stop'] = date('Y', strtotime($date)).'-12-31';
			} else {
				$dates['start'] = $date;
				$dates['stop'] = date('Y-m-d');
			}
			break;
	}

	return $dates;
} // function _myntcd_getback_dates()


/**
 * A fejlecen megjeleno szoveget kesziti el
 * @param ip ip cim
 * @param start forgalmi adatok kezdeti ideje
 * @param stop forgalmi adatok befejezesi ideje
 * @return az oldalhoz megfelelo fejleccel ter vissza
 */
function _myntcd_set_title($from, $ip, $start = '', $stop = '') {
	if ($start != '') {
		if ($stop != '') {
			$date = $start.' - '.$stop;
		} else {
			$date = $start;
		}
	}
	switch ($from) {
		case 'myip':
		case 'ip':
			if ($start == '') {
				return drupal_set_title(t('!title', array('!title' => $ip)));
			} else {
				return drupal_set_title(t('!title (!date)', array('!title' => $ip, '!date' => $date)));
			}
			break;
		case 'iprange':
			if ($ip == 'all') {
				$ip = t('all');
			}
			return drupal_set_title(t('IP Range traffic: !ip (!date)', array('!ip' => $ip, '!date' => $date)));
			break;
		case 'top':
			return drupal_set_title(t('!when Top !num (!date)', array('!when' => $ip, '!num' => '20', '!date' => $date)));
			break;
	}
} // function _myntcd_set_title()


/**
 * Forgalmi adatok tablazatta alakitasa
 * @param from melyik fuggveny hivta meg
 * @param start forgalmi adatok osszegyujtesenek kezdeti ideje
 * @param stop forgalmi adatok osszegyujtesenek befejezesi ideje
 * @param ip ip cim
 */
function _myntcd_create_tmptable($from, $start, $stop = '', $ip = '') {
	if ($stop == '') {
		$stop = date('Y-m-d');
	}

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	$SQL = "CREATE TEMPORARY TABLE tmp_table ";
	$SQL .= "( `ip` varchar(39) default NULL, ";

	$SQL2 = "INSERT INTO tmp_table SELECT ip, ";

	if ($from == 'myip' || $from == 'ip' || $from == 'top') {
		$SQL .= "`date` DATE, ";

		$SQL2 .= "DATE(date), ";
	}
	if ($from == 'ip') {
		$SQL .= "`type` int(3) NOT NULL default '0', ";
		$SQL .= " `in_packet` bigint(20) unsigned NOT NULL default '0', ";
		$SQL .= " `out_packet` bigint(20) unsigned NOT NULL default '0', ";

		$SQL2 .= "type, SUM(in_packet), SUM(out_packet), ";
	} elseif ($from == 'iprange') {
		$SQL .= "`ipr_id` smallint(5) unsigned NOT NULL, ";

		$SQL2 .= "ipr_id, ";
	}
	$SQL2 .= "SUM(in_byte), SUM(out_byte) ";

	$SQL .= " `in_byte` bigint(20) unsigned NOT NULL default '0', ";
	$SQL .= " `out_byte` bigint(20) unsigned NOT NULL default '0')";

	$SQL3 = $SQL2;
	$SQL2 .= "FROM now WHERE ";
	$SQL3 .= "FROM daily WHERE ";
	$TMPSQL = "";
	if ($from == 'myip' || $from == 'ip') {
		$TMPSQL = "ip = :ip AND ";

		$args2 = array(':ip' => $ip, ':stop' => $stop);
		$args3 = array(':ip' => $ip, ':start' => $start, ':stop' => $stop);
	} else {
		$args2 = array(':stop' => $stop);
		$args3 = array(':start' => $start, ':stop' => $stop);
	}
	$SQL2 .= $TMPSQL;
	$SQL2 .= "DATE(date) = :stop GROUP BY ";
	$SQL3 .= $TMPSQL;
	$SQL3 .= "DATE(date) >= :start AND DATE(date) <= :stop GROUP BY ";
	$TMPSQL = "";
	if ($from == 'myip') {
		$TMPSQL .= "DATE(date)";
	} else {
		$TMPSQL .= "ip";
		if ($from == 'ip'){
			$TMPSQL .= ", type";
		}
	}
	$SQL2 .= $TMPSQL;
	if ($from == 'ip' || $from == 'top') {
		$SQL3 .= $TMPSQL.", date";
	} else {
		$SQL3 .= $TMPSQL;
	}

	$result = db_query($SQL);

	$result = db_query($SQL2, $args2);

	$result = db_query($SQL3, $args3);

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();
} // function _myntcd_create_tmptable()


/**
 * Feldolgozza a sql lekerdezes sorait es a tablazat adatait elokesziti
 * @param path megadott utvonal reszlet, ami itt kiegeszul
 * @param when (daily/weekly/monthly/yearly)
 * @param result lekerdezes eredmenye
 * @param link(0/1) kiirt datum linkelve legyen-e
 * @param date a kapott datum
 * @param ip egy adott ip cim
 * @param only_total csak az osszesitet adatok kellenek
 * @return tl a tablazat sorainak tombjevel ter vissza
 */
function _myntcd_process_tabledatas($variables) {
	$path = $variables['path'];
	$when = $variables['when'];
	$result = $variables['result'];
	$link = $variables['link'];
	if ($path == 'myntcd/iprange/all' || $path == 'myntcd/iprange' || $path == 'myntcd/top') {
		$date = $variables['date'];
	}
	if ($path == 'myntcd/ip') {
		$ip = $variables['ip'];
	}
	if ($path == 'my_traffic' || $path == 'myntcd/ip') {
		$only_total = $variables['only_total'];
	}

	if ($result->rowCount() != 0) {
		if ($path == 'my_traffic' || $path == 'myntcd/ip') {
			$date = '';
			$type = '';
			$rows['total'][0] = array(
				'date' => t('Total traffic:'),
				'in_packet' => 0,
				'out_packet' => 0,
				'total_packet' => 0,
				'in_byte' => 0,
				'out_byte' => 0,
				'total_byte' => 0,
			);
		}

		if ($path == 'myntcd/ip') {
			$link_path = $path.'/'.$ip;
		} else {
			$link_path = $path;

			if ($path == 'myntcd/iprange/all') {
				$link_path = $path = 'myntcd/iprange';
				$as = 'iprange';
			} elseif ($path == 'myntcd/iprange' || $path == 'myntcd/top') {
				$link_path = 'myntcd/ip';
				$as = 'ip';
			}
		}

		while ($row = $result->fetchAssoc()) {
			// Linkelhetove alakitja a datumot
			if ($path == 'myntcd/iprange' || $path == 'myntcd/top') {
				if ($link) {
					if ($date != '') {
						$row[$as] = l($row[$as], $link_path.'/'.$row[$as].'/'.$when.'/'.$date);
					} else {
						$row[$as] = l($row[$as], $link_path.'/'.$row[$as].'/'.$when);
					}
				}
				$rows[$row[$as]][0]['in_byte'] = $row['in_byte'];
				$rows[$row[$as]][0]['out_byte'] = $row['out_byte'];
				$rows[$row[$as]][0]['total_byte'] = $row['total'];
			} else {
				switch ($when) {
					case 'daily':
						$row['date'] = format_date(strtotime($row['date']), 'custom', 'H:00');
						break;
					case 'weekly':
					case 'monthly':
						$row['date'] = format_date(strtotime($row['date']), 'custom', 'Y-m-d');
						if ($link) {
							$row['date'] = l($row['date'], $link_path.'/daily/'.$row['date']);
						}
						break;
					case 'yearly':
						$format_date = format_date(strtotime($row['date']), 'custom', 'Y. F');
						if ($link) {
							$link_date_format = 'Y-m-01';

							$row['date'] = l(
								$format_date,
								$link_path.'/monthly/'.date($link_date_format, strtotime($row['date']))
							);
						} else {
							$row['date'] = $format_date;
						}
						break;
				}

				// a teljes forgalom novelese
				if ($path == 'myntcd/ip') {
					$total_packet = $row['in_packet'] + $row['out_packet'];

					$rows['total'][0]['in_packet'] += $row['in_packet'];
					$rows['total'][0]['out_packet'] += $row['out_packet'];
					$rows['total'][0]['total_packet'] += $total_packet;
				}

				$total_byte = $row['in_byte'] + $row['out_byte'];

				$rows['total'][0]['in_byte'] += $row['in_byte'];
				$rows['total'][0]['out_byte'] += $row['out_byte'];
				$rows['total'][0]['total_byte'] += $total_byte;

				if ($path == 'myntcd/ip') {
					$exist = FALSE;
					foreach ($rows['total'] as $key => $value) {
						if ($key == $row['type']) {
							$exist = TRUE;
						}
					}
					if (!$exist) {
						$rows['total'][$row['type']] = array(
							'date' => '',
							'in_packet' => 0,
							'out_packet' => 0,
							'total_packet' => 0,
							'in_byte' => 0,
							'out_byte' => 0,
							'total_byte' => 0,
						);
					}

					$rows['total'][$row['type']]['in_packet'] += $row['in_packet'];
					$rows['total'][$row['type']]['out_packet'] += $row['out_packet'];
					$rows['total'][$row['type']]['total_packet'] += $total_packet;
					$rows['total'][$row['type']]['in_byte'] += $row['in_byte'];
					$rows['total'][$row['type']]['out_byte'] += $row['out_byte'];
					$rows['total'][$row['type']]['total_byte'] += $total_byte;
				}

				if (!$only_total) {
					if ($date != $row['date']) {
						$date = $row['date'];

						$rows[$row['date']][0] = array(
							'date' => $date,
							'in_packet' => 0,
							'out_packet' => 0,
							'total_packet' => 0,
							'in_byte' => 0,
							'out_byte' => 0,
							'total_byte' => 0,
						);
					}

					if ($path == 'myntcd/ip') {
						$rows[$row['date']][0]['in_packet'] += $row['in_packet'];
						$rows[$row['date']][0]['out_packet'] += $row['out_packet'];
						$rows[$row['date']][0]['total_packet'] += $total_packet;
					}

					$rows[$row['date']][0]['in_byte'] += $row['in_byte'];
					$rows[$row['date']][0]['out_byte'] += $row['out_byte'];
					$rows[$row['date']][0]['total_byte'] += $total_byte;

					if ($path == 'myntcd/ip') {
						// tablazat soranak elokeszitese
						$rows[$row['date']][$row['type']] = array(
							'date' => '',
							'in_packet' => $row['in_packet'],
							'out_packet' => $row['out_packet'],
							'total_packet' => $total_packet,
							'in_byte' => $row['in_byte'],
							'out_byte' => $row['out_byte'],
							'total_byte' => $total_byte,
						);
					}
				}
			}
		}

		// Vegig megy a tomb sorain
		while (!is_null($key = key($rows))) {
			// Hozza fuzi a tablazat soraihoz a datumhoz tartozo adatokat
			foreach (array(0, 6, 17, 1, -1) as $element) {
				// A letezo forgalom tipus kerul feldolgozasra
				if (array_key_exists($element, $rows[$key])) {
					// ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk
					if ($rows[$key][$element]['in_byte'] <= $rows[$key][$element]['out_byte']) {
						$warning_byte = '_warning';
					} else {
						$warning_byte = '';
					}

					// ha a kimeno csomag szam tul nagy akkor azt mas stilussal jeloljuk
					if ($path == 'myntcd/ip') {
						if ($rows[$key][$element]['in_packet'] <= $rows[$key][$element]['out_packet']) {
							$warning_packet = '_warning';
						} else {
							$warning_packet = '';
						}
					}

					if ($rows[$key][$element]['total_byte']) {
						$rate = (round($rows[$key][$element]['out_byte'] / $rows[$key][$element]['total_byte'], 2) * 100).' %';
					} else {
						$rate = '0 %';
					}

					if ($path == 'myntcd/iprange' || $path == 'myntcd/top') {
						$title = $key;
					} else {
						$title = $rows[$key][$element]['date'];
					}
					$in_byte = _myntcd_convert_bytes_to_hrf($rows[$key][$element]['in_byte']);
					$out_byte = _myntcd_convert_bytes_to_hrf($rows[$key][$element]['out_byte']);
					$total_byte = _myntcd_convert_bytes_to_hrf($rows[$key][$element]['total_byte']);

					if ($path == 'my_traffic' || $path == 'myntcd/iprange' || $path == 'myntcd/top') {
						$tl[] = array(
							array('data' => $title, 'class' => 'myntcd_title'),
							array('data' => $in_byte, 'class' => 'myntcd_in_byte'),
							array('data' => $out_byte, 'class' => 'myntcd_out_byte'.$warning_byte),
							array('data' => $total_byte, 'class' => 'myntcd_total_byte'.$warning_byte),
							array('data' => $rate, 'class' => 'myntcd_rate'.$warning_byte),
						);
					} else {
						$tl[] = array(
							array('data' => $title, 'class' => 'myntcd_title'),
							array(
								'data' => _myntcd_get_packet_type($element),
								'class' => 'myntcd_type',
							),
							array(
								'data' => number_format($rows[$key][$element]['in_packet'], 0, '', ' ').' db',
								'class' => 'myntcd_in_packet',
							),
							array(
								'data' => number_format($rows[$key][$element]['out_packet'], 0, '', ' ').' db',
								'class' => 'myntcd_out_packet'.$warning_packet,
							),
							array(
								'data' => number_format($rows[$key][$element]['total_packet'], 0, '', ' ').' db',
								'class' => 'myntcd_total_packet'.$warning_packet,
							),
							array('data' => $in_byte, 'class' => 'myntcd_in_byte'),
							array('data' => $out_byte, 'class' => 'myntcd_out_byte'.$warning_byte),
							array('data' => $total_byte, 'class' => 'myntcd_total_byte'.$warning_byte),
							array('data' => $rate, 'class' => 'myntcd_rate'.$warning_byte),
						);
					}
				}
			}
			next($rows);
		}
		return $tl;
	}
} // function _myntcd_process_tabledatas()


/**
 * A fekete lista es a feher lista formjat kesziti el.
 * @param $black_or_white fekete/feher lista kell e
 * @return $form az adott listanak az oldala
 */
function _myntcd_filter_bwform($black_or_white) {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// $SQL = "SELECT * FROM filter WHERE blacklist = :borw ORDER BY date DESC, ip";
	// $result = db_query($SQL, array(':borw' => $black_or_white));

	$query = db_select('filter', 'f')
	  ->fields('f')
	  ->condition('blacklist', $black_or_white)
	  ->orderBy('date', 'DESC')
	  ->orderBy('ip');
	$result = $query->execute();

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$form['table']['#tree'] = TRUE;
	// while ($row = $result->fetchAssoc()) {
	foreach ($result as $row) {
		// $form['table'][$row['ip']] = array(
		$form['table'][$row->ip] = array(
			'chk' => array(
				'#type' => 'checkbox',
			),
			'ip_address' => array(
				'#type' => 'link',
				// '#title' => $row['ip'],
				'#title' => $row->ip,
				// '#href' => 'myntcd/ip/'.$row['ip'],
				'#href' => 'myntcd/ip/'.$row->ip,
			),
			'end_date' => array(
				// '#markup' => $row['date'] == '0000-00-00' ? t('for ever') : $row['date'],
				'#markup' => $row->date == '0000-00-00' ? t('for ever') : $row->date,
			),
			'comment' => array(
				'#type' => 'textfield',
				// '#default_value' => $row['comment'],
				'#default_value' => $row->comment,
			),
		);
	}

	$form['black_or_white'] = array(
		'#type' => 'hidden',
		'#value' => $black_or_white
	);

	if ($black_or_white) {
	  $form['white'] = array(
			'#type' => 'submit',
			'#value' => t('Add Whitelist'),
		);
	}

	$form['save'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	$form['remove'] = array(
		'#type' => 'submit',
		'#value' => t('Delete'),
	);

	return $form;
} // function _myntcd_filter_bwform()


/**
 * A fekete lista es a feher lista muveleteit hajtja vegre.
 * @param form_state szukseges adatokat tarolja
 */
function _myntcd_filter_bwsubmit(&$form_state) {
	foreach ($form_state['values']['table'] as $ip => $items) {
		if ($items['chk']) {
			if ($form_state['values']['op'] == t('Save')) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				// $SQL = "UPDATE filter SET comment = :comment WHERE ip = :ip AND blacklist = :borw";
				// db_query($SQL, array(':comment' => $items['comment'], ':ip' => $ip, ':borw' => $form_state['values']['black_or_white']));

				db_update('filter')
				  ->fields(array(
				    'comment' => $items['comment'],
				  ))
				  ->condition('ip', $ip)
				  ->condition('blacklist', $form_state['values']['black_or_white'])
				  ->execute();

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			} elseif ( $form_state['values']['op'] == t('Delete') ) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				// $SQL = "DELETE FROM filter WHERE ip = :ip AND blacklist = :borw";
				// db_query($SQL, array(':ip' => $ip, ':borw' => $form_state['values']['black_or_white']));

				db_delete('filter')
				  ->condition('ip', $ip)
				  ->condition('blacklist', $form_state['values']['black_or_white'])
				  ->execute();

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			} elseif ( $form_state['values']['op'] == t('Add Whitelist') ) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				// $SQL = "UPDATE filter SET blacklist = 0 WHERE ip = :ip AND blacklist = 1";
				// db_query($SQL, array(':ip' => $ip));

				db_update('filter')
				  ->fields(array(
				    'blacklist' => 0,
				  ))
				  ->condition('ip', $ip)
				  ->condition('blacklist', 1)
				  ->execute();

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			}
		}
	}
} // function _myntcd_filter_bwsubmit()


/**
 * A felekete és feher listanak a tablazatat kesziti el
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return adott oldallal ter vissza
 */
function _myntcd_filter_tables($variables) {
	$form = $variables['form'];
	$output = '';
	$rows = array();
	foreach (element_children($form['table']) as $ip) {
		$rows[] = array(
		  'data' => array(
		  	drupal_render($form['table'][$ip]['chk']),
		    drupal_render($form['table'][$ip]['ip_address']),
		    drupal_render($form['table'][$ip]['end_date']),
		    drupal_render($form['table'][$ip]['comment']),
		  ),
		);
	}

	$header = array(
		'ip_address' => t('IP Address'),
		'end_date' => t('End date'),
		'comment' => t('Comment'),
	);

	// Add a "Select all" checkbox.
	drupal_add_js('misc/tableselect.js');
	array_unshift($header, array('class' => array('select-all')));

	$output .= theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No content available.')));
	$output .= drupal_render_children($form);

	return $output;
} // function _myntcd_filter_tables()


/**
 * RRD adatbazisbol keszit kepet es kuldi a kimenetre
 * @param ip
 * @param title kep cime
 * @param start grafikon kezdesi ideje
 * @param stop grafikon befejezesi ideje
 */
function _myntcd_get_rrd_image_myntcd($ip, $title, $start, $end) {
	$rrd_dir = variable_get('myntcd_rrd_dir', '/usr/local/myntcd/rrd');
	$rrd_cmd = variable_get('myntcd_rrd_cmd', '/usr/bin/rrdtool');

	// .png kimenet beallitasa
	drupal_add_http_header('Content-Type', 'image/png');
	if (is_file($rrd_dir.'/'.$ip.'.rrd')) {
		$error = $out = '';
		$rrdcmd = "$rrd_cmd graph - --imgformat 'PNG' --width 500";
		$rrdcmd .= " --start '$start' --end '$end'";
		$rrdcmd .= " --vertical-label 'byte / sec' --title '$title'  ";
		$rrdcmd .= " --alt-y-mrtg --lazy -c \"MGRID#ee0000\"";
		$rrdcmd .= " -c \"GRID#000000\" 'DEF:A=$rrd_dir/".str_replace(':', '\:', $ip).".rrd:in:AVERAGE'";
		$rrdcmd .= " 'DEF:B=$rrd_dir/".str_replace(':', '\:', $ip).".rrd:out:AVERAGE' 'CDEF:C=A,B,+'";
		$rrdcmd .= " 'LINE1:A#00FF00:".t('In')."' 'GPRINT:A:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'LINE1:B#0000FF:".t('Out')."' 'GPRINT:B:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'COMMENT:".t('Total')."\:' 'GPRINT:C:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		// Parancs futtatasa es az eredmeny kiiratasa a kimentre
		passthru($rrdcmd);
		die;
	}
} // function _myntcd_get_rrd_image_myntcd()


/**
 * Navigacios linkeket allitja elo
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 * @param start forgalmi adatok kezdeti ideje
 * @param stop forgalmi adatok befejezesi ideje
 * @param path megadott utvonal reszlet, ami itt kiegeszul
 * @return a legeneralt linkek html kodjaval ter vissza
 */
function _myntcd_navigation($ip, $when, $start, $stop, $path) {
	$output = '';

	switch ($when) {
		case 'daily':
			$minus_date = $start.' -1 day';
			$plus_date = $start.' +1 day';
			$show_next_date = $start;
			$date_format = 'Y-m-d';
			break;
		case 'weekly':
			$minus_date = $stop.' -7 day';
			$plus_date = $stop.' +7 day';
			$show_next_date = $stop;
			$date_format = 'Y-m-d';
			break;
		case 'monthly':
			$minus_date = $start.' -1 month';
			$plus_date = $start.' +1 month';
			$show_next_date = $stop;
			$date_format = 'Y-m-01';
			break;
		case 'yearly':
			$minus_date = $start.' -1 year';
			$plus_date = $start.' +1 year';
			$show_next_date = $stop;
			$date_format = 'Y-01-01';
			break;
	}

	$output .= '<div class="myntcd-navigation clear-block">';

	$prev_date = date($date_format, strtotime($minus_date));
	if ($ip != '') {
		$full_path = $path.'/'.$ip.'/'.$when;
	} else {
		$full_path = $path.'/'.$when;
	}
	$output .= l(
		t('previous'),
		$full_path.'/'.$prev_date,
		array('attributes' => array('class' => 'myntcd-previous'))
	);

	if ($show_next_date == date('Y-m-d')) {
		$output .= '<span class="myntcd-next-grey">'.t('next').'</span>';
	} else {
		$next_date = date($date_format, strtotime($plus_date));
		$output .= l(
			t('next'),
			$full_path.'/'.$next_date,
			array('attributes' => array('class' => 'myntcd-next'))
		);
	}
	$output .= '</div><br />';

	return $output;
} // function _myntcd_navigation()


/**
 * Ellenorzi a datum formatumot
 * @param date text
 * @return boolean
 */
function _myntcd_chk_date($date) {
	if (preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])-(0[1-9]|[12][[:digit:]]|3[01])$/", $date)) {
		return TRUE;
	} else {
		return FALSE;
	}
} // function _myntcd_chk_date()


/**
 * Vissza adja a csomag tipusanak nevet
 * @param type csomag tipusa
 * @return csomag tipus neve
 */
function _myntcd_get_packet_type($type) {
	switch ($type) {
		case "-1":
			#OTHER
			$type = t('Other');
		break;
		case "1":
			#ICMP
			$type = t('ICMP');
		break;
		case "6":
			#TCP
			$type = t('TCP');
		break;
		case "17":
			#UDP
			$type = t('UDP');
		break;
		default:
			$type = '';
			break;

	}
	return $type;
} // function _myntcd_get_packet_type()


/**
 * Convert Bytes to human readable format
 * A tablazatokbol kiolvasott byte erteketek konvertalja olvashatobb formara
 * @param bytes az adatbazisbol kiolvasott adat
 * @return convertedbytes olvashatobb format ad vissza
 */
function _myntcd_convert_bytes_to_hrf($bytes) {
	$finish = FALSE;
	$exponent = 1;
	// mertekegysegek: byte, kilobyte, megabyte, gigabyte, terrabyte, petabyte, exabyte, zettabyte, yottabyte, brontobyte, geopbyte
	$units = array('B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');
	while($finish != TRUE) {
		// Ha a lefelekerekitve a byte-okat elosszuk a 1024^kitevo-vel az egyenlo nullaval
		if (floor($bytes / pow(1024, $exponent)) == 0) {
			// Ha a kitevo 1, vagyis a byte-okat 1024-el osztva az ertek egyenlo nulla, akkor byte lesz az erteke
			if ($exponent == 1) {
				$convertedbytes = $bytes.' &nbsp;&nbsp;'.$units[$exponent - 1];
			} else { // Ha a kitevo nagyobb mint 1
				// akkor atalakitjuk a szamot a megfelelo formara es hozzarakjuk a mertekegyseget
				$convertedbytes = number_format(round($bytes / pow(1024, $exponent - 1), 2), 2, '.', ' ').' '.$units[$exponent - 1];
			}
			$finish = TRUE;
		}
		// Ha meg nem nulla az ertek akkor noveljuk a kitevot
		$exponent++;
	}
	return $convertedbytes;
} // function _myntcd_convert_bytes_to_hrf()
