<?php
/*
 * Created on 2009.01.02.
 */

/**
 * Implementation of hook_help().
 * Display help and module information
 * @param section which section of the site we're displaying help
 * @return text - help text for section
 */
function myntcd_help($path, $arg) {
	$output = '';
	switch ($path) {
		case "admin/modules#description":
			$output = t("My Network Traffic Counter Daemon");
		break;
	}
	return $output;
} // function myntcd_help()

/**
 * Implementation of hook_init().
 * Minden modul betolteskor lefut.
 */
function myntcd_init() {
	global $db_url, $db_prefix;
	$myntcd_db_url = variable_get('myntcd_db_url', '');
	if ( !empty($myntcd_db_url) ) {
		$db_url['myntcd'] = $myntcd_db_url;
		$db_prefix['myntcd'] = '';
	}
} // function myntcd_init

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the myntcd module
 */
function myntcd_perm() {
	return array('my traffic', 'traffic manager', 'traffic administer', 'myntcd administer');
} // function myntcd_perm()

/**
 * myntcd_menu: menus
 */
function myntcd_menu() {
	$items = array();

	/** Administrator menus, System admin*/
	$items['admin/sysadmin/myntcd'] = array(
		'title' => 'Myntcd settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_settings'),
		'access arguments' => array('myntcd administer'),
	);

	/** Sajat IP adatainak lekerdezese */
	$items['my_traffic'] = array(
		'title' => 'My Traffic',
		'page callback' => 'myntcd_my_traffic',
		'access arguments' => array('my traffic'),
		'weight' => 0,
	);

	$items['my_traffic/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_my_traffic',
		'access arguments' => array('my traffic'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['my_traffic/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('daily'),
		'access arguments' => array('my traffic'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('weekly'),
		'access arguments' => array('my traffic'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('monthly'),
		'access arguments' => array('my traffic'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('yearly'),
		'access arguments' => array('my traffic'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	/** Sajat IP-hez sajat kep */
	$items['myntcd/myimg'] = array(
		'title' => 'MyImg',
		'page callback' => 'myntcd_myimg',
		'access arguments' => array('my traffic'),
		'type' => MENU_CALLBACK,
		'weight' => 1,
	);

	/** IP-k adminisztralasa */
	$items['myntcd'] = array(
		'title' => 'Myntcd',
		'page callback' => 'myntcd_myntcd',
		'access arguments' => array('traffic manager'),
		'weight' => 1,
		'type' => MENU_NORMAL_ITEM,
	);

	/** IP-hez kapcsolodo kep megjelenitese */
	$items['myntcd/img/%/%'] = array(
		'title' => 'Img',
		'page callback' => 'myntcd_img',
		'page arguments' => array(2, 3),
		'access arguments' => array('traffic manager'),
		'type' => MENU_CALLBACK,
		'weight' => 1,
	);

	// IP forgalmi adatai
	$items['myntcd/ip/%'] = array(
		'title' => '!ip',
		'title arguments' => array('!ip' => 2),
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 1,
		'type' => MENU_CALLBACK,
	);
	$items['myntcd/ip/%/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/ip/%/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_ip_daily',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_ip_weekly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_ip_monthly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_ip_yearly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	/** IP tartomanyok */
	$items['myntcd/iprange'] = array(
		'title' => 'IP Ranges',
		'page callback' => 'myntcd_iprange_list',
		'access arguments' => array('traffic manager'),
		'weight' => 3,
		'type' => MENU_NORMAL_ITEM,
	);

	/** IP tartomanyok */
	$items['myntcd/iprange/%'] = array(
		'title' => '!iprange',
		'title arguments' => array('!iprange' => 2),
		'page callback' => 'myntcd_iprange_daily',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 3,
	);

	$items['myntcd/iprange/%/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_iprange_daily',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_iprange_weekly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_iprange_monthly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_iprange_yearly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	/** Top lista */
	$items['myntcd/top'] = array(
		'title' => 'Top Lists',
		'page callback' => 'myntcd_top',
		'access arguments' => array('traffic manager'),
		'weight' => 5,
	);

	$items['myntcd/top/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_top',
		'access arguments' => array('traffic manager'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/top/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_top_daily',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_top_weekly',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_top_monthly',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_top_yearly',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	/** IP cim szuresek kezelese */
	$items['myntcd/filter'] = array(
		'title' => 'Filter',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_blacklist'),
		'access arguments' => array('traffic administer'),
		'weight' => 7,
	);

	$items['myntcd/filter/blacklist'] = array(
		'title' => 'Blacklist',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_blacklist'),
		'access arguments' => array('traffic administer'),
		'weight' => 2,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/filter/whitelist'] = array(
		'title' => 'Whitelist',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_whitelist'),
		'access arguments' => array('traffic administer'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/filter/new'] = array(
		'title' => 'Add filter',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_add'),
		'access arguments' => array('traffic administer'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	return $items;
} // function myntcd_menu()

/**
 * Implementation of hook_theme()
 */
function myntcd_theme() {
	return array(
		'myntcd_my_traffic' => array(
			'arguments' => array(),
		),
		'myntcd_when_my_traffic' => array(
			'arguments' => array('when' => NULL, 'rows' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_daily_my_traffic' => array(
			'arguments' => array('rows' => NULL),
		),
		'myntcd_weekly_my_traffic' => array(
			'arguments' => array('rows' => NULL),
		),
		'myntcd_monthly_my_traffic' => array(
			'arguments' => array('rows' => NULL),
		),
		'myntcd_yearly_my_traffic' => array(
			'arguments' => array('rows' => NULL),
		),
		'myntcd_iprange_list' => array(
			'arguments' => array('ranges' => NULL),
		),
		'myntcd_ip' => array(
			'arguments' => array('ip' => NULL),
		),
		'myntcd_ip_daily' => array(
			'arguments' => array('rows' => NULL,'ip' => NULL, 'date' => NULL),
		),
		'myntcd_ip_weekly' => array(
			'arguments' => array('rows' => NULL,'ip' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_ip_monthly' => array(
			'arguments' => array('rows' => NULL,'ip' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_ip_yearly' => array(
			'arguments' => array('rows' => NULL,'ip' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_ip_when' => array(
			'arguments' => array('rows' => NULL,'ip' => NULL, 'when' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_iprange_daily' => array(
			'arguments' => array('rows' => NULL,'iprange' => NULL, 'date' => NULL),
		),
		'myntcd_iprange_weekly' => array(
			'arguments' => array('rows' => NULL,'iprange' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_iprange_monthly' => array(
			'arguments' => array('rows' => NULL,'iprange' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_iprange_yearly' => array(
			'arguments' => array('rows' => NULL,'iprange' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_iprange_when' => array(
			'arguments' => array('rows' => NULL,'iprange' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_top' => array(
			'arguments' => array('tables' => NULL),
		),
		'myntcd_top_daily' => array(
			'arguments' => array('tables' => NULL, 'date' => NULL),
		),
		'myntcd_top_weekly' => array(
			'arguments' => array('tables' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_top_monthly' => array(
			'arguments' => array('tables' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_top_yearly' => array(
			'arguments' => array('tables' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_top_when' => array(
			'arguments' => array('tables' => NULL, 'when' => NULL, 'start' => NULL, 'stop' => NULL),
		),
		'myntcd_filter_blacklist' => array(
			'arguments' => array('form' => NULL),
		),
		'myntcd_filter_whitelist' => array(
			'arguments' => array('form' => NULL),
		),
	);
}


/**
 * Settings for the myntcd module
 * @return form contents for this module
 */
function myntcd_settings() {
	/** Myntcd SQL szerver bealitasa */
	$form['myntcd_sql_server'] = array(
		'#type' => 'fieldset',
		'#title' => t('Mysql Server Settings'),
		'#collapsible' => TRUE,
		'#collapsed' => false,
	);

	$form['myntcd_sql_server']['myntcd_server_type'] = array(
		'#type' => 'item',
		'#value' => 'MySql',
		'#title' => t('Type'),
	);

	$form['myntcd_sql_server']['myntcd_server'] = array(
		'#type' => 'textfield',
		'#title' => t('Host'),
		'#default_value' => variable_get('myntcd_server', localhost),
		'#description' => '',
		'#maxlength' => '200',
		'#size' => '30',
	);

	$form['myntcd_sql_server']['myntcd_port'] = array(
		'#type' => 'textfield',
		'#title' => t('Port'),
		'#default_value' => variable_get('myntcd_port', 3306),
		'#description' => '',
		'#maxlength' => '5',
		'#size' => '5',
	);

	$form['myntcd_sql_server']['myntcd_db'] = array(
		'#type' => 'textfield',
		'#title' => t('Database name'),
		'#default_value' => variable_get('myntcd_db', traffic),
		'#description' => '',
		'#size' => '10',
	);

	$form['myntcd_sql_server']['myntcd_user'] = array(
		'#type' => 'textfield',
		'#title' => t('Username'),
		'#default_value' => variable_get('myntcd_user', user),
		'#description' => '',
		'#size' => '10',
	);

	$form['myntcd_sql_server']['myntcd_pwd'] = array(
		'#type' => 'password',
		'#title' => t('Password'),
		'#description' => '',
		'#size' => '10',
	);

	/** RRD adatbazis hasznalatahoz szukseges beallitasok */
	$form['myntcd_rrd'] = array(
		'#type' => 'fieldset',
		'#title' => t('RRD Tool settings'),
		'#collapsible' => TRUE,
		'#collapsed' => false,
	);

	$form['myntcd_rrd']['myntcd_rrd_cmd'] = array(
		'#type' => 'textfield',
		'#title' => t('RRD command'),
		'#default_value' => variable_get('myntcd_rrd_cmd', '/usr/bin/rrdtool'),
		'#description' => '',
		'#maxlength' => '200',
		'#size' => '30',
	);

	$form['myntcd_rrd']['myntcd_rrd_dir'] = array(
		'#type' => 'textfield',
		'#title' => t('RRD file dir'),
		'#default_value' => variable_get('myntcd_rrd_dir', '/usr/share/myntcd/rrd'),
		'#description' => '',
		'#maxlength' => '200',
		'#size' => '30',
	);

	$form["submit"] = array(
		"#type" => "submit",
		"#value" => t('Save'),
	);

	return $form;
} // function myntcd_settins()

function myntcd_settings_submit($form, &$form_state) {
	global $db_url;

	$v = $form_state['values'];

	$db_type =  explode('://', $db_url['default']);

	variable_set('myntcd_server_type', $db_type[0]);
	variable_set('myntcd_server', $v['myntcd_server']);
	variable_set('myntcd_port', $v['myntcd_port']);
	variable_set('myntcd_db', $v['myntcd_db']);
	variable_set('myntcd_user', $v['myntcd_user']);
	if ( !empty($v['myntcd_pwd']) ) {
		variable_set('myntcd_pwd', $v['myntcd_pwd']);
	} else {
		$v['myntcd_pwd'] = variable_get('myntcd_pwd', password);
	}
	variable_set('myntcd_rrd_cmd', $v['myntcd_rrd_cmd']);
	variable_set('myntcd_rrd_dir', $v['myntcd_rrd_dir']);

	$myntcd_db_url = $db_type[0].'://'.$v['myntcd_user'].':'.$v['myntcd_pwd'].'@'.$v['myntcd_server'];
	if ( !empty($v['myntcd_port']) ) {
		$myntcd_db_url .= ':'.$v['myntcd_port'];
	}
	$myntcd_db_url .= '/'.$v['myntcd_db'];

	variable_set('myntcd_db_url', $myntcd_db_url);
}

/**
 * myntcd_my_traffic: sajat forgalom megjelenitese
 */
function myntcd_my_traffic($when = '', $date = '') {
	$output = '';
	drupal_add_css(drupal_get_path('module', 'myntcd').'/myntcd.css');

	/** Kliens gep IP cime */
	$my_ip = $_SERVER['REMOTE_ADDR'];

	switch ($when) {
		case '':
			$date = date('Y-m-d');

			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');
			$SQL = "SELECT * FROM {filter} WHERE ip='%s' AND date >= '%s' AND blacklist = 1";
			$result = db_query($SQL, $my_ip, $date);
			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			if ( $filter = db_fetch_array($result) ) {
				drupal_set_message(t('The IP address transfer blocking: !date', array('!date' => $filter['date'].'23:59:59') ), 'warning');
			}

			/** Bekoszonto kepernyo */
			$output .= theme('myntcd_my_traffic');

		break;
		case 'daily':
		/** Napi forgalom */
			$date = date('Y-m-d');
			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			/** A mai nap forgalmi adatai orankenti bontasban */
			$SQL = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM {now} WHERE';
			$SQL .= " ip='%s' AND date(date) = '%s' GROUP BY hour(date) ORDER BY date DESC";
			$result = db_query($SQL, $my_ip, $date);
			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, $rows, $total, 'H:00');

			/** Osszes napi forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);
			$output .= theme('myntcd_daily_my_traffic', $rows);
		break;

		case 'weekly':
		/** Heti forgalom */
			if ($date != '') {
				drupal_goto('my_traffic/weekly');
			}
			$date = date('Y-m-d');
			$start_week = date('Y-m-d', strtotime('-1 week'));

			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			$SQL = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM {now} WHERE';
			$SQL .= " ip='%s' AND date(date) = '%s' GROUP BY date(date) ORDER BY date DESC";
			$result = db_query($SQL, $my_ip, $date);

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, $rows, $total, 'Y-m-d');

			$SQL = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM {daily} WHERE';
			$SQL .= " ip='%s' AND date > '%s' AND date <= '%s' GROUP BY date ORDER BY date DESC";
			$result = db_query($SQL, $my_ip, $start_week, $date);

			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			/** Tablazat sorainak elkesitese */
			_myntcd_get_my_rows($result, $rows, $total, 'Y-m-d');

			if ($total['in_byte'] <= $total['out_byte']) {
				$warrning = 'warrning';
			} else {
				$warrning = '';
			}

			/** Osszes heti forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);
			$output .= theme('myntcd_weekly_my_traffic', $rows);
		break;

		case 'monthly':
		/** Havi forgalom */
			if ($date == '') {
				$date = date('Y-m-01');
			}
			if (!_myntcd_chk_date($date)) {
				drupal_goto('my_traffic/monthly');
			} else {
				$date = date('Y-m-01', strtotime($date));
			}

			if (strtotime('now') < strtotime($date.' +1 month')) {
				$end_month = date('Y-m-d');
			} else {
				$end_month = date('Y-m-d', strtotime($date.' +1 month -1 day'));
			}

			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			$SQL = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM {now} WHERE';
			$SQL .= " ip='%s' AND date(date) = '%s' GROUP BY date(date) ORDER BY date DESC";
			$result = db_query($SQL, $my_ip, $end_month);

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, $rows, $total, 'Y-m-d');


			$SQL = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM {daily} WHERE';
			$SQL .= " ip='%s' AND date >= '%s' AND date <= '%s' GROUP BY date ORDER BY date DESC";
			$result = db_query($SQL, $my_ip, $date, $end_month);

			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			/** Tablazat sorainak elkesitese */
			_myntcd_get_my_rows($result, $rows, $total, 'Y-m-d');

			if ($total['in_byte'] <= $total['out_byte']) {
				$warrning = 'warrning';
			} else {
				$warrning = '';
			}

			/** Osszes havi forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);

			$output .= theme('myntcd_monthly_my_traffic', $rows, $date, $end_month);
		break;

		case 'yearly':
		/** Eves forgalom */
			if ($date != '') {
				drupal_goto('my_traffic/yearly');
			}
			$date = date('Y-m-d');
			$start_year = date('Y-01-01');

			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			$SQL = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM {now} WHERE';
			$SQL .= " ip='%s' AND date(date) = '%s' GROUP BY date(date) ORDER BY date DESC";
			$result = db_query($SQL, $my_ip, $date);

			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkesitese */
			_myntcd_get_my_rows($result, $day, $total, 'Y. F', 1);

			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			$SQL = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM {daily} WHERE';
			$SQL .= " ip='%s' AND date >= '%s' GROUP BY month(date) ORDER BY date DESC";
			$result = db_query($SQL, $my_ip, $start_year);

			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, $rows, $total, 'Y. F', 1);

			if ($total['in_byte'] <= $total['out_byte']) {
				$warrning = 'warrning';
			} else {
				$warrning = '';
			}

			/** Aktualis honaphoz az aktualis nap forgalmi adatainak hozza adasa */
			if (count($rows)) {
				if ($rows[0][0]['data'] == $day[0][0]['data']) {
					$rows[0][1]['data'] = str_replace(' ', '', rtrim($rows[0][1]['data'], ' MB')) + str_replace(' ', '', rtrim($day[0][1]['data'], ' MB'));
					$rows[0][2]['data'] = str_replace(' ', '', rtrim($rows[0][2]['data'], ' MB')) + str_replace(' ', '', rtrim($day[0][2]['data'], ' MB'));
					$rows[0][3]['data'] = str_replace(' ', '', rtrim($rows[0][3]['data'], ' MB')) + str_replace(' ', '', rtrim($day[0][3]['data'], ' MB'));
					/** 0-val osztas ellen */
					if ($rows[0][3]['data']) {
						$rows[0][4]['data'] = (round($rows[0][2]['data']/$rows[0][3]['data'],2)*100).' %';
					} else {
						$rows[0][4]['data'] = '0 %';
					}

					$rows[0][1]['data'] = number_format($rows[0][1]['data'], 2, '.', ' ').' MB';
					$rows[0][2]['data'] = number_format($rows[0][2]['data'], 2, '.', ' ').' MB';
					$rows[0][3]['data'] = number_format($rows[0][3]['data'], 2, '.', ' ').' MB';
				} else {
					if (count($day)) {
						array_unshift($rows, $day[0]);
					}
				}
			}

			/** Eves forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);

			$output .= theme('myntcd_yearly_my_traffic', $rows, date('Y'));
		break;
		default:
			drupal_goto('my_traffic');
		break;
	}
	if ($output == '') {
		$output = ' ';
	}

	return $output;
} // function my_traffic_myntcd()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye
 * @param rows tablazat sorai
 * @param total osszesitet adatok
 * @param date_format kiirt datum formatuma
 * @param link(0/1) kiirt datum linkelve legyen-e
 */
function _myntcd_get_my_rows(&$result, &$rows, &$total, $date_format, $link = 0) {
	while ($row = db_fetch_array($result)) {
		/** Atalakitja a datumot a kert formatumra */
		if ($link) {
			$row['date'] = l(format_date(strtotime($row['date']), 'custom', $date_format), 'my_traffic/monthly/'.date('Y-m-01', strtotime($row['date'])));
		} else {
			$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
		}

		/** kiszamolja az osszes forgalmat es azt hogy a teljes forgalom hany %-a a kimeno forgalom */
		$row['total_byte'] = $row['in_byte']+$row['out_byte'];
		if ($row['total_byte']) {
			$row['rate'] = (round($row['out_byte']/$row['total_byte'],2)*100).' %';
		} else {
			$row['rate'] = '0 %';
		}

		/** a teljes forgalom novelese */
		$total['in'] += $row['in_byte'];
		$total['out'] += $row['out_byte'];

		/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
		if ($row['in_byte'] <= $row['out_byte']) {
			$warrning = '_warrning';
		} else {
			$warrning = '';
		}
		/** tablazat soranak elkeszitese */
		$rows[] = array(
			array('data' => $row['date'], 'class' => 'myntcd_date'),
			array('data' => number_format(round($row['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_in_byte'),
			array('data' => number_format(round($row['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_out_byte'.$warrning),
			array('data' => number_format(round($row['total_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_byte'.$warrning),
			array('data' => $row['rate'], 'class' => 'myntcd_rate'.$warrning),
		);
	}
} // function _myntcd_get_my_rows()

/**
 * Teljes forgalom adatanak hozzafuzese a tablazat elejehez
 * @param rows tablazat sorai
 * @param total osszesitet adatok
 */
function _myntcd_get_my_totlal_line(&$rows, $total) {
	/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
	if ($total['in'] <= $total['out']) {
		$warrning = '_warrning';
	} else {
		$warrning = '';
	}

	/** Osszes napi forgalom hozza fuzese a tablazathoz */
	if ($total['in']+$total['out']) {
		if ($total['out']) {
			$total['rate'] = (round($total['out']/($total['in']+$total['out']),2)*100).' %';
		} else {
			$total['rate'] = '0 %';
		}

		$row = array(
			array('data' => t('Total traffic:'), 'class' => 'myntcd_total'),
			array('data' => number_format(round($total['in']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_in_byte'),
			array('data' => number_format(round($total['out']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_out_byte'.$warrning),
			array('data' => number_format(round(($total['in']+$total['out'])/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_total_byte'.$warrning),
			array('data' => $total['rate'], 'class' => 'myntcd_total_rate'.$warrning),
		);
		/** Osszes napi forgalom hozza adasa a tablazat elejehez */
		array_unshift($rows, $row);
	}
} // function _myntcd_get_my_totlal_line()


/**
 * theme_myntcd_my_traffic
 */
function theme_myntcd_my_traffic() {
	$output = '';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/myimg/daily').'" alt="myntcd_daily_image" />', 'my_traffic/daily', array('html' => TRUE) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/myimg/weekly').'" alt="myntcd_weekly_image" />', 'my_traffic/weekly', array('html' => TRUE) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/myimg/monthly').'" alt="myntcd_monthly_image" />', 'my_traffic/monthly', array('html' => TRUE) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/myimg/yearly').'" alt="myntcd_yearly_image" />', 'my_traffic/yearly', array('html' => TRUE) ).'</div>';

	return $output;
}

/**
 * theme_myntcd_when_my_traffic
 */
function theme_myntcd_when_my_traffic($when, $rows, $start, $stop = '') {
	$output = '';
	if ($stop != '') {
		$date = $start.' - '.$stop;
	} else {
		$date = $start;
	}
	drupal_set_title(t('!title (!date)', array('!title' => drupal_get_title(), '!date' => $date )) );

	$output .= '<div class="my_ip_myntcd">'.t('My ip: %IP', array('%IP' => $_SERVER['REMOTE_ADDR']) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/myimg/'.$when).'" alt="myntcd_'.$when.'_image" />', 'my_traffic/'.$when, array('html' => TRUE) ).'</div>';

	$header = array(array('data' => t('Time')),
		array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
	);
	$output .= theme('table', $header, $rows);
	return $output;

} // function theme_myntcd_when_my_traffic()

/**
 * theme_myntcd_daily_my_traffic
 */
function theme_myntcd_daily_my_traffic($rows) {
	return theme('myntcd_when_my_traffic', 'daily', $rows, date('Y-m-d'));
} // function theme_daily_my_traffic_myntcd()

/**
 * theme_myntcd_weekly_my_traffic
 */
function theme_myntcd_weekly_my_traffic($rows) {
	return theme('myntcd_when_my_traffic', 'weekly', $rows, date('Y-m-d', strtotime('-6 day')), date('Y-m-d'));
} // function theme_monthly_my_traffic_myntcd()

/**
 * theme_myntcd_monthly_my_traffic
 */
function theme_myntcd_monthly_my_traffic($rows, $start, $stop) {
	return theme('myntcd_when_my_traffic', 'monthly', $rows, $start, $stop);
} // function theme_monthly_my_traffic_myntcd()

/**
 * theme_myntcd_yearly_my_traffic
 */
function theme_myntcd_yearly_my_traffic($rows, $date) {
	return theme('myntcd_when_my_traffic', 'yearly', $rows, $date);
} // function theme_monthly_my_traffic_myntcd()


/**
 * myntcd_myimg
 */
function myntcd_myimg($type) {
	myntcd_img($_SERVER['REMOTE_ADDR'], $type);
} // function myimg_myntcd()


function myntcd_myntcd() {
	$ip = arg(1);

	$output = '';
	drupal_add_css(drupal_get_path('module', 'myntcd').'/myntcd.css');

	/** ha IP az IP */
	if (_myntcd_is_ip($ip)) {
		drupal_goto('myntcd/ip/'.$ip);
	} elseif($ip == '') {
		$output .= drupal_get_form('myntcd_search');
	} else {
		drupal_goto('myntcd');
	}
	return $output;
} // function myntcd_myntcd()

function myntcd_search() {
	/** ip kereses */
	$form = array();
	$form['ip'] = array(
		'#type' => 'textfield',
		'#title' => t('Ip address'),
		'#size' => 20,
		'#maxlength' => 15,
		'#required' => false,
	);
	$form['submit'] = array('#type' => 'submit', '#value' => t('Jump'));

	return $form;
}

function myntcd_search_validate($form, &$form_state) {
	if (!_myntcd_is_ip($form_state['values']['ip'])) {
		form_set_error('ip', t('Is not IP address.'));
	}
}

/**
 * myntcd_search_submit: jump ip address
 */
function myntcd_search_submit($form, &$form_state) {
	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');
	$SQL = "SELECT ip FROM {now} WHERE ip = '%s'";
	$result = db_query_range($SQL, $form_state['values']['ip'], 0, 1);
	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();
	if ( $ip = db_fetch_array($result) ) {
		drupal_goto('myntcd/ip/'.$form_state['values']['ip']);
	}
}

/**
 * myntcd_ip: IP traffic summary
 */
function myntcd_ip($ip) {
	if (_myntcd_is_ip($ip)) {
		return theme('myntcd_ip', $ip);
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip

/**
 * theme_myntcd_ip: IP traffic summary
 */
function theme_myntcd_ip($ip) {
	drupal_add_css(drupal_get_path('module', 'myntcd').'/myntcd.css');

	$output = '';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/img/'.$ip.'/daily').'" alt="myntcd_daily_image" />', 'myntcd/'.$ip.'/daily', array('html' => TRUE) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/img/'.$ip.'/weekly').'" alt="myntcd_weekly_image" />', 'myntcd/'.$ip.'/weekly', array('html' => TRUE) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/img/'.$ip.'/monthly').'" alt="myntcd_monthly_image" />', 'myntcd/'.$ip.'/monthly', array('html' => TRUE) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/img/'.$ip.'/yearly').'" alt="myntcd_yearly_image" />', 'myntcd/'.$ip.'/yearly', array('html' => TRUE) ).'</div>';

	return $output;
} // function theme_myntcd_ip

/**
 * myntcd_ip_daily: IP daily traffic
 */
function myntcd_ip_daily($ip, $date = '') {
	if (_myntcd_is_ip($ip)) {
		if ($date == '') {
			$date = date('Y-m-d');
		} elseif (!_myntcd_chk_date($date)) {
			drupal_goto('myntcd/ip/'.$ip.'/daily');
			return;
		}

		/** utolso nap masik tablaba van */
		if ($date == date('Y-m-d')) {
			$from = " FROM {now}";
		} else {
			$from = " FROM {daily}";
		}
		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		/** A mai nap forgalmi adatai orankenti bontasban */
		$SQL = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet';
		$SQL .= ', SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte';
		$SQL .= $from." WHERE ip='%s' AND date(date) = '%s' GROUP BY hour(date), type ORDER BY date DESC";
		$result = db_query($SQL, $ip, $date);

		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		$rows = $total = array();
		$total['in'] = $total['out'] = 0;
		/** Tablazat sorainak elokeszitese */
		_myntcd_get_ip_all_rows($result, $rows, $total, 'H:00', $ip, 'daily');

		/** Ha nem aktualis nap van egyszerubb tablazat kell */
		if ($date != date('Y-m-d')) {
			$rows = array();
		}
		/** Napi forgalom hozza fuzese a tablazathoz */
		_myntcd_get_ip_line($rows, $total);

		return theme('myntcd_ip_daily', $rows, $ip, $date);
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_daily

/**
 * myntcd_ip_weekly: IP weekly traffic
 */
function myntcd_ip_weekly($ip, $date = '') {
	if (_myntcd_is_ip($ip)) {
		if ($date == '') {
			$date = date('Y-m-d');
		} elseif (!_myntcd_chk_date($date)) {
			drupal_goto('myntcd/ip/'.$ip.'/weekly');
			return;
		}

		$start_week = date('Y-m-d', strtotime($date.' -1 week'));

		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		/** forgalmi adatok betoltese az atmenti tablaba */
		_myntcd_ip2tmptable($ip, $start_week, $date);

		$SQL = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet,';
		$SQL .= ' SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table';
		$SQL .= " GROUP BY date, ip, type ORDER BY date DESC";
		$result = db_query($SQL);

		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		$rows = $total = array();
		/** Tablazat sorainak elokeszitese */
		_myntcd_get_ip_all_rows($result, $rows, $total, 'Y-m-d', $ip, 'weekly');
		/** Heti forgalom hozza fuzese a tablazathoz */
		_myntcd_get_ip_line($rows, $total);

		return theme('myntcd_ip_weekly', $rows, $ip, $start_week, $date);
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_weekly

/**
 * myntcd_ip_monthly: IP monthly traffic
 */
function myntcd_ip_monthly($ip, $month = '') {
	if (_myntcd_is_ip($ip)) {
		if ($month == '') {
			$month = date('Y-m');
		} elseif (!preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])$/", $month)) {
			drupal_goto('myntcd/ip/'.$ip.'/monthly');
			return;
		}

		$start_month = $month.'-01';
		if ( $month == date('Y-m') ) {
			$end_month = $month.date('-d');
		} else {
			$end_month = date('Y-m-d', strtotime('-1 day', strtotime('+1 month', strtotime($month."-01"))));
		}

		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		/** forgalmi adatok betoltese az atmenti tablaba */
		_myntcd_ip2tmptable($ip, $start_month, $end_month);

		$SQL = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet,';
		$SQL .= ' SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table';
		$SQL .= " GROUP BY date, ip, type ORDER BY date DESC";
		$result = db_query($SQL);

		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		$rows = $total = array();
		/** Tablazat sorainak elokeszitese */
		_myntcd_get_ip_all_rows($result, $rows, $total, 'Y-m-d', $ip, 'monthly');
		/** Heti forgalom hozza fuzese a tablazathoz */
		_myntcd_get_ip_line($rows, $total);

		return theme('myntcd_ip_monthly', $rows, $ip, $start_month, $end_month);
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_monthly
/**
 * myntcd_ip_yearly: IP yearly traffic
 */
function myntcd_ip_yearly($ip, $year = '') {
	if (_myntcd_is_ip($ip)) {
		if ($year == '') {
			$year = date('Y');
		} elseif (!preg_match("/^([123456789][[:digit:]]{3})$/", $year)) {
			drupal_goto('myntcd/ip/'.$ip.'/yearly');
			return;
		}

		if ( $year == date('Y') ) {
			$start_year = date('Y-01-01');
			$stop_year = date('Y-m-d');
		} else {
			$start_year = $year.'-01-01';
			$stop_year = $year.'-12-31';
		}

		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		/** forgalmi adatok betoltese az atmenti tablaba */
		_myntcd_ip2tmptable($ip, $start_year, $stop_year);

		$SQL = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet,';
		$SQL .= ' SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table';
		$SQL .= " GROUP BY date, ip, type ORDER BY date DESC";
		$result = db_query($SQL);

		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		$rows = $total = array();
		/** Tablazat sorainak elokeszitese */
		_myntcd_get_ip_all_rows($result, $rows, $total, 'Y. F', $ip, 'yearly');
		/** Heti forgalom hozza fuzese a tablazathoz */
		_myntcd_get_ip_line($rows, $total);

		return theme('myntcd_ip_yearly', $rows, $ip, $start_year, $stop_year);
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_yearly

/**
 * theme_myntcd_ip_daily: IP daily traffic
 */
function theme_myntcd_ip_daily($rows, $ip, $date) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m-d', strtotime($date.' -1 day'));
	$output .= l(t('previous'), 'myntcd/ip/'.$ip.'/daily/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($date == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m-d', strtotime($date.' +1 day'));
		$output .= l(t('next'), 'myntcd/ip/'.$ip.'/daily/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';

	$output .= theme('myntcd_ip_when', $ip, 'daily', $rows, $date);
	return $output;
} // function theme_myntcd_ip_daily

/**
 * theme_myntcd_ip_weekly
 */
function theme_myntcd_ip_weekly($rows, $ip, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m-d', strtotime($stop.' -7 day'));
	$output .= l(t('previous'), 'myntcd/ip/'.$ip.'/weekly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m-d', strtotime($stop.' +7 day'));
		$output .= l(t('next'), 'myntcd/ip/'.$ip.'/weekly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';
	$output .= theme('myntcd_ip_when', $ip, 'weekly', $rows, $start, $stop);

	return $output;
} // function theme_myntcd_ip_weekly

/**
 * theme_myntcd_ip_monthly
 */
function theme_myntcd_ip_monthly($rows, $ip, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m', strtotime($start.' -1 month'));
	$output .= l(t('previous'), 'myntcd/ip/'.$ip.'/monthly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m', strtotime($start.' +1 month'));
		$output .= l(t('next'), 'myntcd/ip/'.$ip.'/monthly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';
	$output .= theme('myntcd_ip_when', $ip, 'monthly', $rows, $start, $stop);

	return $output;
} // function theme_myntcd_ip_monthly

/**
 * theme_myntcd_ip_yearly
 */
function theme_myntcd_ip_yearly($rows, $ip, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y', strtotime($start.' -1 year'));
	$output .= l(t('previous'), 'myntcd/ip/'.$ip.'/yearly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y', strtotime($start.' +1 year'));
		$output .= l(t('next'), 'myntcd/ip/'.$ip.'/yearly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';
	$output .= theme('myntcd_ip_when', $ip, 'yearly', $rows, $start, $stop);

	return $output;
} // function theme_myntcd_ip_yearly

/**
 * theme_myntcd_when: egyseges theme
 */
function theme_myntcd_ip_when($ip, $when, $rows = '', $start = '', $stop = '') {
	drupal_add_css(drupal_get_path('module', 'myntcd').'/myntcd.css');

	$output = '';
	if ($stop != '') {
		$date = $start.' - '.$stop;
	} else {
		$date = $start;
		$stop = $start;
	}
	drupal_set_title( t('!title (!date)', array('!title' => drupal_get_title(), '!date' => $date) ) );

	$output .= '<div class="ip_myntcd">'.t('IP Address: !IP', array('!IP' => $ip) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="'.url('myntcd/img/'.$ip.'/'.$when.'/'.$stop).'" alt="myntcd_'.$when.'_image" />', 'myntcd/'.$ip.'/'.$when.'/'.$stop, array('html' => TRUE) ).'</div>';

	$header = array(
		array('data' => t('Time')),
		array('data' => t('Type')),
		array('data' => t('In Packet'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out Packet'), 'class' => 'myntcd_header_right'),
		array('data' => t('Total Packet'), 'class' => 'myntcd_header_right'),
		array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
	);
	$output .= theme('table', $header, $rows);

	return $output;
} // function theme_myntcd_when()

/**
 * myntcd_iprange_list: list iprange
 */
function myntcd_iprange_list() {
	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');

	/** IP tartomanyok listazasa */
	$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS ip_range";
	$SQL .= " FROM {daily} GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
	$result = db_query($SQL);
	$rows = array();
	while ($row = db_fetch_array($result)) {
		if ( _myntcd_is_ip($row['ip_range'].'.1') ) {
			$rows[] = $row['ip_range'];
		}
	}

	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	return theme('myntcd_iprange_list', $rows);
} // function myntcd_iprange_list

/**
 * theme_myntcd_iprange_list
 */
function theme_myntcd_iprange_list($ipranges) {
	$header = array(
		array('data' => t('IP Address')),
		array('data' => t('Operations'), 'colspan' => '4'),
	);

	$rows = array();
	$rows[] = array(
		array('data' => l(t('All'), 'myntcd/iprange/all') ),
		array('data' => l(t('Daily'), 'myntcd/iprange/all') ),
		array('data' => l(t('Weekly'), 'myntcd/iprange/all/weekly') ),
		array('data' => l(t('Monthly'), 'myntcd/iprange/all/monthly') ),
		array('data' => l(t('Yearly'), 'myntcd/iprange/all/yearly') ),
	);
	foreach ($ipranges as $iprange) {
		$rows[] = array(
			array('data' => l($iprange.'.0', 'myntcd/iprange/'.$iprange.'.0') ),
			array('data' => l(t('Daily'), 'myntcd/iprange/'.$iprange.'.0') ),
			array('data' => l(t('Weekly'), 'myntcd/iprange/'.$iprange.'.0/weekly') ),
			array('data' => l(t('Monthly'), 'myntcd/iprange/'.$iprange.'.0/monthly') ),
			array('data' => l(t('Yearly'), 'myntcd/iprange/'.$iprange.'.0/yearly') ),
		);
	}

	return theme('table', $header, $rows);
} // function theme_myntcd_iprange_list

/**
 * myntcd_iprange_daily: iprange daily traffic
 */
function myntcd_iprange_daily($iprange, $date = '') {
	$output = '';

	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/daily');
		return;
	}

	if ($date == date('Y-m-d')) {
		$from = " FROM {now}";
	} else {
		$from = " FROM {daily}";
	}

	if ($iprange == 'all') {
		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS iprange";
		$SQL .= ", SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
		$SQL .= $from." WHERE date(date) = '%s' GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
		$result = db_query($SQL, $date);
		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'daily', 'iprange');
		$output .= theme('myntcd_iprange_daily', $rows, $iprange, $date);

	} elseif ( strrchr($iprange, '.') == '.0') {
		$iprange = substr($iprange, 0, strrpos($iprange, '.0'));
		if ( _myntcd_is_ip($iprange.'.0') ) {
			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			/** IP tartomanyhoz tartozo napi forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
			$SQL .= $from." WHERE date(date) = '%s' AND substring(ip,1,length(ip)-locate('.',reverse(ip))) = '%s' GROUP BY ip ORDER BY total DESC";
			$result = db_query($SQL, $date, $iprange);
			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			_myntcd_get_ip_rows($result, $rows, 'daily');
			$output .= theme('myntcd_iprange_daily', $rows, $iprange.'.0', $date);
		}
	} else {
		drupal_goto('myntcd/iprange');
	}
	return $output;
} // function myntcd_iprange_daily

/**
 * myntcd_iprange_weekly: iprange weekly traffic
 */
function myntcd_iprange_weekly($iprange, $date = '') {
	$output = '';

	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/weekly');
		return;
	}

	$start_week = date('Y-m-d', strtotime($date.' -1 week'));

	if ($iprange == 'all') {
		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		/** Seged tabla definialasa es feltoltese */
		_myntcd_traffic2tmptable($start_week, $date);

		$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS iprange";
		$SQL .= ", SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
		$SQL .= " FROM {tmp_table} GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
		$result = db_query($SQL);
		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'weekly', 'iprange');
		$output .= theme('myntcd_iprange_weekly', $rows, $iprange, $start_week, $date);

	} elseif ( strrchr($iprange, '.') == '.0') {
		$iprange = substr($iprange, 0, strrpos($iprange, '.0'));
		if ( _myntcd_is_ip($iprange.'.0') ) {
			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			/** Seged tabla definialasa es feltoltese */
			_myntcd_traffic2tmptable($start_week, $date);

			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
			$SQL .= " FROM {tmp_table} WHERE substring(ip,1,length(ip)-locate('.',reverse(ip))) = '%s' GROUP BY ip ORDER BY total DESC";
			$result = db_query($SQL, $iprange);
			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			_myntcd_get_ip_rows($result, $rows, 'weekly');
			$output .= theme('myntcd_iprange_weekly', $rows, $iprange.'.0', $start_week, $date);
		}
	} else {
		drupal_goto('myntcd/iprange');
	}
	return $output;
} // function myntcd_iprange_weekly

/**
 * myntcd_iprange_monthly: iprange monthly traffic
 */
function myntcd_iprange_monthly($iprange, $month = '') {
	$output = '';

	if ($month == '') {
		$month = date('Y-m');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])$/", $month)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/monthly');
	}

	$start_month = $month.'-01';
	if ( $month == date('Y-m') ) {
		$end_month = $month.date('-d');
	} else {
		$end_month = date('Y-m-d', strtotime('-1 day', strtotime('+1 month', strtotime($month."-01"))));
	}

	if ($iprange == 'all') {
		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		/** Seged tabla definialasa es feltoltese */
		_myntcd_traffic2tmptable($start_month, $end_month);

		$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS iprange";
		$SQL .= ", SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
		$SQL .= " FROM {tmp_table} GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
		$result = db_query($SQL);
		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'monthly', 'iprange');
		$output .= theme('myntcd_iprange_monthly', $rows, $iprange, $start_month, $end_month);

	} elseif ( strrchr($iprange, '.') == '.0') {
		$iprange = substr($iprange, 0, strrpos($iprange, '.0'));
		if ( _myntcd_is_ip($iprange.'.0') ) {
			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			/** Seged tabla definialasa es feltoltese */
			_myntcd_traffic2tmptable($start_month, $end_month);

			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
			$SQL .= " FROM {tmp_table} WHERE substring(ip,1,length(ip)-locate('.',reverse(ip))) = '%s' GROUP BY ip ORDER BY total DESC";
			$result = db_query($SQL, $iprange);
			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			_myntcd_get_ip_rows($result, $rows, 'monthly');
			$output .= theme('myntcd_iprange_monthly', $rows, $iprange, $start_month, $end_month);
		}
	} else {
		drupal_goto('myntcd/iprange');
	}
	return $output;
} // function myntcd_iprange_monthly

/**
 * myntcd_iprange_yearly: iprange yearly traffic
 */
function myntcd_iprange_yearly($iprange, $year = '') {
	$output = '';

	/** Eves toplista */
	if ($year == '') {
		$year = date('Y');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})$/", $year)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/yearly');
	}

	if ( $year == date('Y') ) {
		$start_year = date('Y-01-01');
		$stop_year = date('Y-m-d');
	} else {
		$start_year = $year.'-01-01';
		$stop_year = $year.'-12-31';
	}

	if ($iprange == 'all') {
		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		/** Seged tabla definialasa es feltoltese */
		_myntcd_traffic2tmptable($start_year, $end_year);

		$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS iprange";
		$SQL .= ", SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
		$SQL .= " FROM {tmp_table} GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
		$result = db_query($SQL);
		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'yearly', 'iprange');
		$output .= theme('myntcd_iprange_yearly', $rows, $iprange, $start_year, $stop_year);

	} elseif ( strrchr($iprange, '.') == '.0') {
		$iprange = substr($iprange, 0, strrpos($iprange, '.0'));
		if ( _myntcd_is_ip($iprange.'.0') ) {
			/** Kapcsolodas az SQL szerverhez */
			db_set_active('myntcd');

			/** Seged tabla definialasa es feltoltese */
			_myntcd_traffic2tmptable($start_year, $end_year);

			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
			$SQL .= " FROM {tmp_table} WHERE substring(ip,1,length(ip)-locate('.',reverse(ip))) = '%s' GROUP BY ip ORDER BY total DESC";
			$result = db_query($SQL, $iprange);
			/** Vissza valtas az alapertelmezett SQL szerverhez */
			db_set_active();

			_myntcd_get_ip_rows($result, $rows, 'yearly');
			$output .= theme('myntcd_iprange_yearly', $rows, $iprange.'.0', $start_year, $stop_year);
		}
	} else {
		drupal_goto('myntcd/iprange');
	}
	return $output;
} // function myntcd_iprange_yearly

/**
 * theme_myntcd_iprange_daily
 */
function theme_myntcd_iprange_daily($rows, $iprange, $date) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m-d', strtotime($date.' -1 day'));
	$output .= l(t('previous'), 'myntcd/iprange/'.$iprange.'/daily/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($date == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m-d', strtotime($date.' +1 day'));
		$output .= l(t('next'), 'myntcd/iprange/'.$iprange.'/daily/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';

	$output .= theme('myntcd_iprange_when', $rows, $iprange, $date);

	return $output;
} // function theme_myntcd_iprange_daily

/**
 * theme_myntcd_iprange_weekly
 */
function theme_myntcd_iprange_weekly($rows, $iprange, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m-d', strtotime($stop.' -1 week'));
	$output .= l(t('previous'), 'myntcd/iprange/'.$iprange.'/weekly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m-d', strtotime($stop.' +1 week'));
		$output .= l(t('next'), 'myntcd/iprange/'.$iprange.'/weekly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';

	$output .= theme('myntcd_iprange_when', $rows, $iprange, $start, $stop);

	return $output;
} // function theme_myntcd_iprange_monthly

/**
 * theme_myntcd_iprange_monthly
 */
function theme_myntcd_iprange_monthly($rows, $iprange, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m', strtotime($start.' -1 month'));
	$output .= l(t('previous'), 'myntcd/iprange/'.$iprange.'/monthly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m', strtotime($start.' +1 month'));
		$output .= l(t('next'), 'myntcd/iprange/'.$iprange.'/monthly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';

	$output .= theme('myntcd_iprange_when', $rows, $iprange, $start, $stop);

	return $output;
} // function theme_myntcd_iprange_monthly

/**
 * theme_myntcd_iprange_yearly
 */
function theme_myntcd_iprange_yearly($rows, $iprange, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y', strtotime($start.' -1 year'));
	$output .= l(t('previous'), 'myntcd/iprange/'.$iprange.'/yearly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y', strtotime($start.' +1 year'));
		$output .= l(t('next'), 'myntcd/iprange/'.$iprange.'/yearly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';

	$output .= theme('myntcd_iprange_when', $rows, $iprange, $start, $stop);

	return $output;
} // function theme_myntcd_iprange_yearly

/**
 * theme_myntcd_iprange_when
 */
function theme_myntcd_iprange_when($rows, $iprange, $start, $stop = '') {
	drupal_add_css(drupal_get_path('module', 'myntcd').'/myntcd.css');

	if ($stop != '') {
		$date = $start.' - '.$stop;
	} else {
		$date = $start;
	}

	if ($iprange == 'all') {
		$iprange = t('all');
	}

	drupal_set_title( t('IP Range traffic: !iprange (!date)', array('!iprange' => $iprange, '!date' => $date) ) );
// TODO: York: csak az utolsó oszlopnál adod meg a sortot a data meg a field mellé
	$header = array(
		array('data' => t('IP Address')),
		array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
	);
	$output .= '<div id = "myntcd_in_top_table">';
	$output .= theme('table', $header, $rows);
	$output .= '</div>';

	return $output;
} // function theme_myntcd_iprange_when

/*
 * myntcd_top: traffic toplist
 */
function myntcd_top() {
	/** Bekoszonto kepernyo */
	$date = date('Y-m-d');

	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');

	/** Napi Top lista */
	$order_by = 'total';
	$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
	$SQL .= " FROM {now} WHERE date(date) = '%s' GROUP BY ip, date(date) ORDER BY ".$order_by." DESC";
	$result = db_query_range($SQL, $date, 0, 20);

	$tables['total'] = array();
	/** Tablazat sorainak elkeszitese */
	_myntcd_get_ip_rows($result, $tables['daily'], 'daily');

	$start_month = date('Y-m-01');
	$start_year = date('Y-01-01');
	/** Seged tabla definialasa */
	$SQL = "CREATE TEMPORARY TABLE {tmp_table}";
	$SQL .= " ( `ip` varchar(15) default NULL, `date` DATE, `in_byte` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result = db_query($SQL);

	/** aktualis nap adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO {tmp_table} SELECT ip, date(date), SUM(in_byte), SUM(out_byte) FROM {now}";
	$SQL .= " WHERE date(date) = '%s' GROUP BY ip";
	$result = db_query($SQL, $date);

	/** aktualis ev adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO {tmp_table} SELECT ip, date, SUM(in_byte), SUM(out_byte) FROM {daily}";
	$SQL .= " WHERE date >= '%s' AND date <= '%s' GROUP BY ip, date";
	$result = db_query($SQL, $start_year, $date);

	/** Havi Top lista */
	$order_by = 'total';
	$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
	$SQL .= " FROM {tmp_table} WHERE date >= '%s' AND date <= '%s' GROUP BY ip  ORDER BY ".$order_by." DESC";
	$result = db_query_range($SQL, $start_month, $date, 0, 20);

	$tables['total'] = array();
	/** Tablazat sorainak elkeszitese */
	_myntcd_get_ip_rows($result, $tables['monthly'], 'monthly');

	/** Eves Top lista */
	$order_by = 'total';
	$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
	$SQL .= " FROM {tmp_table} WHERE date >= '%s' AND date <= 's' GROUP BY ip  ORDER BY ".$order_by." DESC";
	$result = db_query_range($SQL, $start_year, $date, 0, 20);
	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	$tables['total'] = array();
	/** Tablazat sorainak elkeszitese */
	_myntcd_get_ip_rows($result, $tables['yearly'], 'yearly');

	$output .= theme('myntcd_top', $tables);
	return $output;
} // function myntcd_top

/**
 * theme_myntcd_top
 */
function theme_myntcd_top($tables) {
	drupal_add_css(drupal_get_path('module', 'myntcd').'/myntcd.css');

	$output = '';

	$header = array(array('data' => t('IP Address')),
		array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
	);
	$output .= '<div class = "myntcd_top_label">'.t('Daily Top !num total byte', array('!num' => '20')).':</div>';
	$output .= '<div id = "myntcd_in_top_table">';
	$output .= theme('table', $header, $tables['daily']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t('Monthly Top !num total byte', array('!num' => '20')).':</div>';
	$output .= '<div id = "myntcd_out_top_table">';
	$output .= theme('table', $header, $tables['monthly']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t('Yearly Top !num total byte', array('!num' => '20')).':</div>';
	$output .= '<div id = "myntcd_total_top_table">';
	$output .= theme('table', $header, $tables['yearly']);
	$output .= '</div>';

	return $output;
} // function theme_myntcd_top()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye
 * @param rows tablazat sorai
 * @param when (daily/weekly/monthly/yearly)
 * @param date_format kiirt datum formatuma
 * @param as lekerdezes neve
 */
 function _myntcd_get_ip_rows($result, &$rows, $when, $as = 'ip') {
 		/** link elkeszitese, valamint tartomany helyes kiiratasa */
		if ($as != 'iprange') {
			$link = 'ip';
			$extra = '';
		} else {
			$link = 'iprange';
			$extra = '.0';
		}

	while ($row = db_fetch_array($result)) {
		if ( _myntcd_is_ip($row[$as].$extra) ) {

			/** link elkeszitese, valamint tartomany helyes kiiratasa */
			$row[$as] = l($row[$as].$extra, 'myntcd/'.$link.'/'.$row[$as].$extra.'/'.$when);
			/** kiszamolja az osszes forgalmat es azt hogy a teljes forgalom hany %-a a kimeno forgalom */
			if ($row['total']) {
				$row['rate'] = (round($row['out_byte']/$row['total'],2)*100).' %';
			} else {
				$row['rate'] = '0 %';
			}

			/** a teljes forgalom novelese */
			$total['in'] += $row['in_byte'];
			$total['out'] += $row['out_byte'];

			/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
			if ($row['in_byte'] <= $row['out_byte']) {
				$warrning = '_warrning';
			} else {
				$warrning = '';
			}
			/** tablazat soranak elkeszitese */
			$rows[] = array(
				array('data' => $row[$as], 'class' => 'myntcd_'.$as),
				array('data' => number_format(round($row['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_in_byte'),
				array('data' => number_format(round($row['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_out_byte'.$warrning),
				array('data' => number_format(round($row['total']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_byte'.$warrning),
				array('data' => $row['rate'], 'class' => 'myntcd_rate'.$warrning),
			);
		}
	}
} // function _myntcd_get_ip_rows()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye
 * @param rows tablazat sorainak elokeszitese
 * @param total osszesitet adatok
 * @param date_format kiirt datum formatuma
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 */
function _myntcd_get_ip_all_rows($result, &$rows, &$total, $date_format, $ip = '', $when = '') {
	while ($row = db_fetch_array($result)) {
		/** Linkelhetove alakitja a datumot */
		switch ($when) {
			case 'weekly':
			case 'monthly':
				$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
				$row['date'] = l($row['date'], 'myntcd/ip/'.$ip.'/daily/'.$row['date']);
			break;
			case 'yearly':
				$row['date'] = l(format_date(strtotime($row['date'].' 22:00'), 'custom', $date_format), 'myntcd/ip/'.$ip.'/monthly/'.date('Y-m', strtotime($row['date'])));
				break;

			default:
				$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
			break;
		}

		/** A teljes forgalom novelese */
		$total[0]['in_packet'] += $row['in_packet'];
		$total[0]['out_packet'] += $row['out_packet'];
		$total[0]['in_byte'] += $row['in_byte'];
		$total[0]['out_byte'] += $row['out_byte'];
		$total[$row['type']]['in_packet'] += $row['in_packet'];
		$total[$row['type']]['out_packet'] += $row['out_packet'];
		$total[$row['type']]['in_byte'] += $row['in_byte'];
		$total[$row['type']]['out_byte'] += $row['out_byte'];

		/** tablazat soranak elokeszitese */
		$rows[$row['date']][$row['type']] = array(
			type => $row['type'],
			in_packet => $row['in_packet'],
			out_packet => $row['out_packet'],
			total_packet => $row['in_packet']+$row['out_packet'],
			in_byte => $row['in_byte'],
			out_byte => $row['out_byte'],
			total_byte => $row['in_byte']+$row['out_byte'],
		);
	}
} // function _myntcd_get_ip_all_rows()

function _myntcd_get_ip_line(&$rows, $total) {
	/** Osszesitet adatok hozzafuzese a tablazathoz, osszesitve es tipusonkent */
	foreach (array(0, 6, 17, 1, -1) as $element) {
		if (array_key_exists($element, $total)) {
			/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
			if ($total[$element]['in_byte'] <= $total[$element]['out_byte']) {
				$warrning = '_warrning';
			} else {
				$warrning = '';
			}

			/** kiszamolja hogy a teljes forgalom hany %-a a kimeno forgalom */
			if ($total[$element]['out_byte']) {
				$total[$element]['rate'] = (round($total[$element]['out_byte']/($total[$element]['in_byte']+$total[$element]['out_byte']),2)*100).' %';
			} else {
				$total[$element]['rate'] = '0 %';
			}

			/** Sorok feliratozasa */
			if ($element == 0) {
				$date = t('Total traffic:');
				$type = '';
			} else {
				$date = '';
				$type = _myntcd_get_packet_type($element);
			}

			/** Tablazat sorai */
			$tl[] = array(
				array('data' => $date, 'class' => 'myntcd_total_total'),
				array('data' => $type, 'class' => 'myntcd_total_type'),
				array('data' => number_format($total[$element]['in_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_in_packet'),
				array('data' => number_format($total[$element]['out_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_out_packet'.$warrning),
				array('data' => number_format(($total[$element]['in_packet']+$total[$element]['out_packet']), 0, '', ' ').' db', 'class' => 'myntcd_total_total_packet'.$warrning),
				array('data' => number_format(round($total[$element]['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_in_byte'),
				array('data' => number_format(round($total[$element]['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_out_byte'.$warrning),
				array('data' => number_format(round(($total[$element]['in_byte']+$total[$element]['out_byte'])/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_total_byte'.$warrning),
				array('data' => $total[$element]['rate'], 'class' => 'myntcd_total_rate'.$warrning),
			);
		}
	}

	/** Vegig megy a tomb sorain */
	while (!is_null($key = key($rows) ) ) {
		$rows[$key][0]['date'] = $key;
		/** Osszesiti az adott datumhoz tartozo forgalmi adatokat */
		foreach (array(6, 17, 1, -1) as $element) {
			$rows[$key][0]['in_packet'] += $rows[$key][$element]['in_packet'];
			$rows[$key][0]['out_packet'] += $rows[$key][$element]['out_packet'];
			$rows[$key][0]['total_packet'] += $rows[$key][$element]['total_packet'];
			$rows[$key][0]['in_byte'] += $rows[$key][$element]['in_byte'];
			$rows[$key][0]['out_byte'] += $rows[$key][$element]['out_byte'];
			$rows[$key][0]['total_byte'] += $rows[$key][$element]['total_byte'];
		}

		/** Hozza fuzi a tablazat soraihoz a datumhoz tartozo adatokat */
		foreach (array(0, 6, 17, 1, -1) as $element) {
			/** A letezo forgalom tipus kerul feldolgozasra */
			if (array_key_exists($element, $rows[$key])) {
				/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
				if ($rows[$key][$element]['in_byte'] <= $rows[$key][$element]['out_byte']) {
					$warrning_byte = '_warrning';
				} else {
					$warrning_byte = '';
				}

				/** ha a kimeno csomag szam tul nagy akkor azt mas stilussal jeloljuk */
				if ($rows[$key][$element]['in_packet'] <= $rows[$key][$element]['out_packet']) {
					$warrning_packet = '_warrning';
				} else {
					$warrning_packet = '';
				}

				if ($rows[$key][$element]['total_byte']) {
					$rows[$key][$element]['rate'] = (round($rows[$key][$element]['out_byte']/$rows[$key][$element]['total_byte'],2)*100).' %';
				} else {
					$rows[$key][$element]['rate'] = '0 %';
				}

				$tl[] = array(
					array('data' => $rows[$key][$element]['date'], 'class' => 'myntcd_date'),
					array('data' => _myntcd_get_packet_type($rows[$key][$element]['type']), 'class' => 'myntcd_type'),
					array('data' => number_format($rows[$key][$element]['in_packet'], 0, '', ' ').' db', 'class' => 'myntcd_in_packet'),
					array('data' => number_format($rows[$key][$element]['out_packet'], 0, '', ' ').' db', 'class' => 'myntcd_out_packet'.$warrning_packet),
					array('data' => number_format($rows[$key][$element]['total_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_packet'.$warrning_packet),
					array('data' => number_format(round($rows[$key][$element]['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_in_byte'),
					array('data' => number_format(round($rows[$key][$element]['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_out_byte'.$warrning_byte),
					array('data' => number_format(round($rows[$key][$element]['total_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_byte'.$warrning_byte),
					array('data' => $rows[$key][$element]['rate'], 'class' => 'myntcd_rate'.$warrning_byte),
				);
			}
		}
		next($rows);
	}
	$rows = $tl;
} // function _myntcd_get_ip_line()

/**
 * _myntcd_ip2tmptable: Forgalmi adatok tablazatta alakitasa
 * @param db adatbazis kapcsoalt
 * @param ip ip cim
 * @param start forgalmi adatok osszegyujtesenek kezdeti ideje
 * @param stop forgalmi adatok osszegyujtesenek befejezesi ideje
 */
function _myntcd_ip2tmptable($ip, $start, $stop = '') {
	/** Seged tabla definialasa */
	if ($stop == '') {
		$stop = date('Y-m-d');
	}
	$SQL = "CREATE TEMPORARY TABLE {tmp_table}";
	$SQL .= " ( `ip` varchar(15) default NULL, `date` DATE, `type` int(3) NOT NULL default '0',";
	$SQL .= "  `in_packet` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `out_packet` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `in_byte` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result = db_query($SQL);

	/** aktualis nap adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO {tmp_table} SELECT ip, date(date), type, SUM(in_packet), SUM(out_packet), SUM(in_byte), SUM(out_byte)";
	$SQL .= " FROM now WHERE ip = '%s' AND date(date) = '%s' GROUP BY ip, type";
	$result = db_query($SQL, $ip, $stop);

	/** megadott intervallum adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO {tmp_table} SELECT ip, date, type, SUM(in_packet), SUM(out_packet), SUM(in_byte), SUM(out_byte) FROM daily";
	$SQL .= " WHERE ip = '%s' AND date >= '%s' AND date <= '%s' GROUP BY date, ip, type";
	$result = db_query($SQL, $ip, $start, $stop);

} // function _myntcd_ip2tmptable()

/**
 * _myntcd_traffic2tmptable: megadott intervallum forgalmat IP cimenkent osszegyujti
 * @param start megadott idoponttol
 * @param stop megadott idopontig
 */
function _myntcd_traffic2tmptable($start, $stop = '') {
	/** Seged tabla definialasa */
	if ($stop == '') {
		$stop = date('Y-m-d');
	}
	$SQL = "CREATE TEMPORARY TABLE {tmp_table}";
	$SQL .= " ( `ip` varchar(15) default NULL, `in_byte` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result = db_query($SQL);

	/** aktualis nap adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO tmp_table SELECT ip, SUM(in_byte), SUM(out_byte) FROM {now}";
	$SQL .= " WHERE date(date) = '%s' GROUP BY ip";
	$result = db_query($SQL, $stop);

	/** megadott ido intervallum adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO tmp_table SELECT ip, SUM(in_byte), SUM(out_byte) FROM {daily}";
	$SQL .= " WHERE date >= '%s' AND date <= '%s' GROUP BY ip";
	$result = db_query($SQL, $start, $stop);
} // function _myntcd_traffic2tmptable()

/**
 * myntcd_top_daily
 */
function myntcd_top_daily($date = '') {
	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/top/daily');
		return;
	}

	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');

	/** Napnak megfelelo adatbazis kivalasztasa */
	if ($date == date('Y-m-d')) {
		$from = " FROM {now}";
	} else {
		$from = " FROM {daily}";
	}

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		/** Top lista: forgalomnak megfelelo */
		$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
		$SQL .= $from." WHERE date(date) = '%s' GROUP BY ip, date(date) ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, $date, 0, 20);

		$tables[$table] = array();
		/** Tablazat sorainak elkeszitese */
		_myntcd_get_ip_rows($result, $tables[$table], 'daily');
	}

	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	$output .= theme('myntcd_top_daily', $tables, $date);

	return $output;
} // function myntcd_top_daily()

/**
 * myntcd_top_weekly
 */
function myntcd_top_weekly($date = '') {
	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/top/weekly');
		return;
	}

	$start_week = date('Y-m-d', strtotime($date.' -1 week'));

	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');

	/** Seged tabla definialasa es feltoltese */
	_myntcd_traffic2tmptable($start_week, $date);

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		/** Top lista: forgalomnak megfelelo */
		$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
		$SQL .= " FROM {tmp_table} GROUP BY ip ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, 0, 20);

		$tables[$table] = array();
		/** Tablazat sorainak elkeszitese */
		_myntcd_get_ip_rows($result, $tables[$table], 'weekly');
	}

	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	$output .= theme('myntcd_top_weekly', $tables, $start_week, $date);



	return $output;
} // function myntcd_top_weekly()

/**
 * myntcd_top_monthly
 */
function myntcd_top_monthly($month = '') {
	/** Havi toplista */
	if ($month == '') {
		$month = date('Y-m');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])$/", $month)) {
		drupal_goto('myntcd/top/monthly');
	}

	$start_month = $month.'-01';
	if ( $month == date('Y-m') ) {
		$end_month = $month.date('-d');
	} else {
		$end_month = date('Y-m-d', strtotime('-1 day', strtotime('+1 month', strtotime($month."-01"))));
	}

	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');

	/** Seged tabla definialasa es feltoltese */
	_myntcd_traffic2tmptable($start_month, $end_month);

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		/** Top lista: forgalomnak megfelelo */
		$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
		$SQL .= " FROM {tmp_table} GROUP BY ip ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, 0, 20);

		$tables[$table] = array();
		/** Tablazat sorainak elkeszitese */
		_myntcd_get_ip_rows($result, $tables[$table], 'monthly');
	}

	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	$output .= theme('myntcd_top_monthly', $tables, $start_month, $end_month);

	return $output;
} // function myntcd_top_monthly()

/**
 * myntcd_top_monthly
 */
function myntcd_top_yearly($year = '') {

	/** Eves toplista */
	if ($year == '') {
		$year = date('Y');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})$/", $year)) {
		drupal_goto('myntcd/top/yearly');
	}

	if ( $year == date('Y') ) {
		$start_year = date('Y-01-01');
		$stop_year = date('Y-m-d');
	} else {
		$start_year = $year.'-01-01';
		$stop_year = $year.'-12-31';
	}

	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');

	/** Seged tabla definialasa es feltoltese */
	_myntcd_traffic2tmptable($start_year, $stop_year);

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		/** Top lista: forgalomnak megfelelo */
		$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
		$SQL .= " FROM {tmp_table} GROUP BY ip ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, 0, 20);

		$tables[$table] = array();
		/** Tablazat sorainak elkeszitese */
		_myntcd_get_ip_rows($result, $tables[$table], 'yearly');
	}

	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	$output .= theme('myntcd_top_yearly', $tables, $start_year, $stop_year);

	return $output;
} // function myntcd_top_monthly()

/**
 * theme_myntcd_top_daily
 */
function theme_myntcd_top_daily($tables, $date) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m-d', strtotime($date.' -1 day'));
	$output .= l(t('previous'), 'myntcd/top/daily/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($date == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m-d', strtotime($date.' +1 day'));
		$output .= l(t('next'), 'myntcd/top/daily/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';
	$output .= theme('myntcd_top_when', $tables, 'Daily', $date);
	return $output;
} // function theme_myntcd_top_daily

/**
 * theme_myntcd_top_weekly
 */
function theme_myntcd_top_weekly($tables, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m-d', strtotime($stop.' -7 day'));
	$output .= l(t('previous'), 'myntcd/top/weekly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m-d', strtotime($stop.' +7 day'));
		$output .= l(t('next'), 'myntcd/top/weekly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';
	$output .= theme('myntcd_top_when', $tables, 'Weekly', $start, $stop);
	return $output;
} // function theme_myntcd_top_weekly

/**
 * theme_myntcd_top_monthly
 */
function theme_myntcd_top_monthly($tables, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y-m', strtotime($start.' -1 month'));
	$output .= l(t('previous'), 'myntcd/top/monthly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y-m', strtotime($start.' +1 month'));
		$output .= l(t('next'), 'myntcd/top/monthly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';
	$output .= theme('myntcd_top_when', $tables, 'Monthly', $start, $stop);
	return $output;
} // function theme_myntcd_top_monthly

/**
 * theme_myntcd_top_yearly
 */
function theme_myntcd_top_yearly($tables, $start, $stop) {
	$output = '<div class="myntcd-navigation clear-block">';

	$prev_date = date('Y', strtotime($start.' -1 year'));
	$output .= l(t('previous'), 'myntcd/top/yearly/'.$prev_date  ,array('attributes' => array('class' => 'myntcd-previous')) );

	if ($stop == date('Y-m-d')) {
		$output .= '<div class="-next"></div>';
	} else {
		$next_date = date('Y', strtotime($start.' +1 year'));
		$output .= l(t('next'), 'myntcd/top/yearly/'.$next_date  ,array('attributes' => array('class' => 'myntcd-next')) );
	}
	$output .= '</div>';
	$output .= theme('myntcd_top_when', $tables, 'Yearly', $start, $stop);
	return $output;
} // function theme_myntcd_top_yearly

/**
 * theme_myntcd_top_when
 */
function theme_myntcd_top_when($tables, $when, $start, $stop = '') {
	drupal_add_css(drupal_get_path('module', 'myntcd').'/myntcd.css');

	$output = '';

	if ($stop != '') {
		$date = $start.' - '.$stop;
	} else {
		$date = $start;
	}
	drupal_set_title( t($when.' Top !num (!date)', array('!num' => '20', '!date' => $date) ) );

	$header = array(array('data' => t('IP Address')),
		array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
		array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
	);
	$output .= '<div class = "myntcd_top_label">'.t($when.' Top !num in byte', array('!num' => '20')).':</div>';
	$output .= '<div id = "myntcd_in_top_table">';
	$output .= theme('table', $header, $tables['in']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t($when.' Top !num out byte', array('!num' => '20')).':</div>';
	$output .= '<div id = "myntcd_out_top_table">';
	$output .= theme('table', $header, $tables['out']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t($when.' Top !num total byte', array('!num' => '20')).':</div>';
	$output .= '<div id = "myntcd_total_top_table">';
	$output .= theme('table', $header, $tables['total']);
	$output .= '</div>';

	return $output;
} // function theme_myntcd_top_when

/*
 * myntcd_filter_blacklist
 */
function myntcd_filter_blacklist() {
	$bl = array();

	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');
	$SQL = "SELECT * FROM {filter} WHERE blacklist = 1 ORDER BY date DESC, ip";
	$result = db_query($SQL);

	while ($row = db_fetch_array($result)) {
		$bl[$row['ip']] = $row;
		$bl[$row['ip']]['disabled'] = FALSE;
	}

	$SQL = "SELECT * FROM {filter} WHERE blacklist = 0";
	$result = db_query($SQL);
	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	while ($row = db_fetch_array($result)) {
		if ( ( !empty($bl[$row['ip']]) ) && ( $bl[$row['ip']]['date'] <= $row['date'] ) ) {
			$bl[$row['ip']]['disabled'] = TRUE;
		}
	}

	$form = $ips = array();
	foreach ($bl as $ip => $bl_ip) {
		$i_p = str_replace('.', '_', $ip);
		$form[$i_p]['ip'] = array('#value' => l($ip, 'myntcd/ip/'.$ip));
		if ($bl_ip['date'] == '0000-00-00') {
			$bl_ip['date'] = t('for ever');
		}
		$form[$i_p]['date'] = array('#value' => $bl_ip['date']);
		$form[$i_p]['comment'] = array(
			'#type' => 'textfield',
			'#default_value' => $bl_ip['comment'],
			'#disabled' => $bl_ip['disabled'],
		);
		$ips[$i_p] = '';
	}

	$form['ips'] = array(
		'#type' => 'checkboxes',
		'#options' => $ips,
  );

  $form['white'] = array(
		'#type' => 'submit',
		'#value' => t('Add Whitelist'),
	);

	$form['save'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	$form['remove'] = array(
		'#type' => 'submit',
		'#value' => t('Delete'),
	);

	$form['#tree'] = TRUE;

	return $form;
}  // function myntcd_filter_blacklist

/*
 * theme_webform2pdf_download_pdf_form: webform2pdf_download_pdf_form of theme hook
 */
function theme_myntcd_filter_blacklist(&$form) {
	$output = '';
	$header = array(
		array('data' => t('IP Address') ),
		array('data' => t('End date') ),
		array('data' => t('Comment') ),
	);
	$hc = theme('table_select_header_cell');
	array_unshift($header, $hc );
	$rows = array();
	foreach ($form['ips']['#options'] as $ip => $empty) {
		if ($form[$ip]['comment']['#disabled']) {
			$form['ips'][$ip] ["#attributes"]["disabled"]= "disabled";
		}

		$row = array();
		$row[] = array('data' => drupal_render($form['ips'][$ip]), 'class' => 'checkbox' );
		$row[] = array('data' => drupal_render($form[$ip]['ip']) );
		$row[] = array('data' => drupal_render($form[$ip]['date']) );
		$row[] = array('data' => drupal_render($form[$ip]['comment']) );
		$rows[] = $row;
	}
	$output .= theme('table', $header, $rows);
	$output .= drupal_render($form);

	return $output;
}

function myntcd_filter_blacklist_submit($form, &$form_state) {
	if ( $form_state['values']['op'] == t('Save') ) {
		foreach ($form_state['values']['ips'] as $ip => $var) {
			if ( $form[$ip]['comment']['#default_value'] != $form_state['values'][$ip]['comment'] ) {
				/** Kapcsolodas az SQL szerverhez */
				db_set_active('myntcd');

				$SQL = "UPDATE {filter} SET comment = '%s' WHERE ip = '%s' AND blacklist = 1";
				$i_p = str_replace('_', '.', $ip);
				db_query($SQL, $form_state['values'][$ip]['comment'], $i_p);

				/** Vissza valtas az alapertelmezett SQL szerverhez */
				db_set_active();
			}
		}
	} elseif ( $form_state['values']['op'] == t('Delete') ) {
		$form_state['values']['ips'] = array_filter($form_state['values']['ips']);
		$ips = "'".str_replace('_', '.', implode("', '", $form_state['values']['ips']) )."'";

		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		$SQL = "DELETE FROM {filter} WHERE ip IN (".$ips.") AND blacklist = 1";
		db_query($SQL);

		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();
	} elseif ( $form_state['values']['op'] == t('Add Whitelist') ) {
		$form_state['values']['ips'] = array_filter($form_state['values']['ips']);
		$ips = "'".str_replace('_', '.', implode("', '", $form_state['values']['ips']) )."'";

		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		$SQL = "UPDATE {filter} SET date = '%s', blacklist = 0 WHERE ip IN (".$ips.") AND blacklist = 1";
		db_query($SQL, date('Y-m-d'));

		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();
	}
}

function myntcd_filter_whitelist() {
	$wl = array();

	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');
	$SQL = "SELECT * FROM {filter} WHERE blacklist = 0 ORDER BY date DESC, ip";
	$result = db_query($SQL);

	while ($row = db_fetch_array($result)) {
		$wl[$row['ip']] = $row;
		$wl[$row['ip']]['disabled'] = FALSE;
	}

	$SQL = "SELECT * FROM {filter} WHERE blacklist = 1";
	$result = db_query($SQL);
	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();

	while ($row = db_fetch_array($result)) {
		if ( ( !empty($wl[$row['ip']]) ) && ( $wl[$row['ip']]['date'] < $row['date'] ) ) {
			$wl[$row['ip']]['disabled'] = TRUE;
		}
	}

	$form = $ips = array();
	foreach ($wl as $ip => $wl_ip) {
		$i_p = str_replace('.', '_', $ip);
		$form[$i_p]['ip'] = array('#value' => l($ip, 'myntcd/ip/'.$ip));
		if ($wl_ip['date'] == '0000-00-00') {
			$wl_ip['date'] = t('for ever');
		}
		$form[$i_p]['date'] = array('#value' => $wl_ip['date']);
		$form[$i_p]['comment'] = array(
			'#type' => 'textfield',
			'#default_value' => $wl_ip['comment'],
			'#disabled' => $wl_ip['disabled'],
		);
		$ips[$i_p] = '';
	}

	$form['ips'] = array(
		'#type' => 'checkboxes',
		'#options' => $ips,
  );

	$form['save'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	$form['remove'] = array(
		'#type' => 'submit',
		'#value' => t('Delete'),
	);

	$form['#tree'] = TRUE;

	return $form;
}

/*
 * theme_webform2pdf_download_pdf_form: webform2pdf_download_pdf_form of theme hook
 */
function theme_myntcd_filter_whitelist($form) {
	$output = '';
	$header = array(
		array('data' => t('IP Address') ),
		array('data' => t('End date') ),
		array('data' => t('Comment') ),
	);
	$hc = theme('table_select_header_cell');
	array_unshift($header, $hc );
	$rows = array();
	foreach ($form['ips']['#options'] as $ip => $empty) {
		if ($form[$ip]['comment']['#disabled']) {
			$form['ips'][$ip] ["#attributes"]["disabled"]= "disabled";
		}
		$row = array();
		$row[] = array('data' => drupal_render($form['ips'][$ip]), 'class' => 'checkbox' );
		$row[] = array('data' => drupal_render($form[$ip]['ip']) );
		$row[] = array('data' => drupal_render($form[$ip]['date']) );
		$row[] = array('data' => drupal_render($form[$ip]['comment']) );
		$rows[] = $row;
	}
	$output .= theme('table', $header, $rows);
	$output .= drupal_render($form);

	return $output;
}

function myntcd_filter_whitelist_submit($form, &$form_state) {
	if ( $form_state['values']['op'] == t('Save') ) {
		foreach ($form_state['values']['ips'] as $ip => $var) {
			if ( $form[$ip]['comment']['#default_value'] != $form_state['values'][$ip]['comment'] ) {
				/** Kapcsolodas az SQL szerverhez */
				db_set_active('myntcd');

				$SQL = "UPDATE {filter} SET comment = '%s' WHERE ip = '%s' AND blacklist = 0";
				$i_p = str_replace('_', '.', $ip);
				db_query($SQL, $form_state['values'][$ip]['comment'], $i_p);

				/** Vissza valtas az alapertelmezett SQL szerverhez */
				db_set_active();
			}
		}
	} elseif ( $form_state['values']['op'] == t('Delete') ) {
		$form_state['values']['ips'] = array_filter($form_state['values']['ips']);
		$ips = "'".str_replace('_', '.', implode("', '", $form_state['values']['ips']) )."'";

		/** Kapcsolodas az SQL szerverhez */
		db_set_active('myntcd');

		$SQL = "DELETE FROM {filter} WHERE ip IN (".$ips.") AND blacklist = 0";
		db_query($SQL);

		/** Vissza valtas az alapertelmezett SQL szerverhez */
		db_set_active();
	}
}



function myntcd_filter_add() {
	$form['filter_ip'] = array(
		'#type' => 'textfield',
		'#title' => t('IP Address'),
		'#size' => 20,
		'#maxlength' => 15,
		'#required' => TRUE,
	);

	$form['filter_type'] = array(
		'#type' => 'select',
		'#title' => t('Type'),
		'#options' => array(1 => t('Blacklist'), 0 => t('Whitelist')),
		'#required' => FALSE,
	);

	$form['filter_time'] = array(
		'#type' => 'select',
		'#title' => t('Time interval'),
		'#options' => array('1' => '1 '.t('day'), '2' => '2 '.t('day'), '5' => '5 '.t('day'), '7' => '1 '.t('week'), '14' => '2 '.t('week'), '30' => '1 '.t('month'), '-1' => t('for ever')),
		'#required' => FALSE,
	);

	$form['filter_comment'] = array(
		'#type' => 'textfield',
		'#title' => t('Comment'),
		'#size' => 20,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save')
	);

	return $form;
}

function myntcd_filter_add_validate($form, &$form_state) {
	if (!_myntcd_is_ip($form_state['values']['filter_ip'])) {
		form_set_error('filter_ip', t('Is not IP address.'));
	}
}

function myntcd_filter_add_submit($form, &$form_state) {
	/** Kapcsolodas az SQL szerverhez */
	db_set_active('myntcd');

	if ($form_state['values']['filter_time'] == '-1') {
		$form_state['values']['filter_time'] = '0000-00-00';
	} else {
		$form_state['values']['filter_time'] = date('Y-m-d', strtotime('+'.$form_state['values']['filter_time'].' day'));
	}
	$SQL = "INSERT INTO {filter} (ip, blacklist, date, comment) VALUES ('%s', %d, '%s', '%s')";
	db_query($SQL, $form_state['values']['filter_ip'], $form_state['values']['filter_type'], $form_state['values']['filter_time'], $form_state['values']['filter_comment']);

	/** Vissza valtas az alapertelmezett SQL szerverhez */
	db_set_active();
}



/**
 * RRD adatbazisbol keszit kepet es kuldi a kimenetre
 * @param ip
 * @param title kep cime
 * @param start grafikon kezdesi ideje
 * @param stop grafikon befejezesi ideje
 */
function _myntcd_get_rrd_image_myntcd($ip, $title, $start, $end) {
	$rrd_dir = variable_get('myntcd_rrd_dir', '/usr/share/myntcd/rrd');
	$rrd_cmd = variable_get('myntcd_rrd_cmd', '/usr/bin/rrdtool');

	/** .png kimenet beallitasa */
	drupal_set_header('Content-Type: image/png');
	if (is_file($rrd_dir.'/'.$ip.'.rrd')) {
		$error = $out = '';
		$rrdcmd = "$rrd_cmd graph - --imgformat 'PNG'";
		$rrdcmd .= " --start '$start' --end '$end'";
		$rrdcmd .= " --vertical-label 'byte / sec' --title '$title'  ";
		$rrdcmd .= " --alt-y-mrtg --lazy -c \"MGRID#ee0000\"";
		$rrdcmd .= " -c \"GRID#000000\" 'DEF:A=$rrd_dir/$ip.rrd:in:AVERAGE'";
		$rrdcmd .= " 'DEF:B=$rrd_dir/$ip.rrd:out:AVERAGE' 'CDEF:C=A,B,+'";
		$rrdcmd .= " 'LINE1:A#00FF00:".t('In')."' 'GPRINT:A:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'LINE1:B#0000FF:".t('Out')."' 'GPRINT:B:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'COMMENT:".t('Total')."\:' 'GPRINT:C:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		/** Parancs futtatasa es az eredmeny kiiratasa a kimentre */
		passthru($rrdcmd);
		die;
	}
} // function _myntcd_get_rrd_image_myntcd()

/**
 * myntcd_img: rrd grafikont jelenit meg egy adott ip-hez
 */
function myntcd_img($ip, $type, $end = '') {
	/** Utolso idopont meghatarozasa */
	if ($end == '') {
		$end = strtotime('now');
	} else {
		if ($type != 'yearly') {
//			$end = strtotime($end.' '.date('H:i:s'));
			$end = strtotime($end.' 23:59:59');
		} else {
			$end = strtotime($end);
		}
	}
	/** Kep tipusanak megfelelo kezdesi idopont meghatarozasa */
	switch ($type) {
		default:
		case 'daily':
			$start = strtotime('-1 day', $end);
			$title = $ip.' ('.date('Y-m-d', $end).')';
		break;
		case 'weekly':
			$start = strtotime('-1 week', $end);
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $end).')';
		break;
		case 'monthly':
			$start = strtotime('-1 month', $end);
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $end).')';
		break;
		case 'yearly':
			$start = strtotime('-1 year', $end);
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $end).')';
		break;
	}
	/** Kep elkeszitese */
	$img = _myntcd_get_rrd_image_myntcd($ip, $title, $start, $end);
} // function myntcd_img

/**
 * Vissza adja a csomag tipusanak nevet
 * @param type csomag tipusa
 * @return csomag tipus neve
 */
function _myntcd_get_packet_type($type) {
	switch ($type) {
		case "-1":
			#OTHER
			$type = t('Other');
		break;
		case "1":
			#ICMP
			$type = t('ICMP');
		break;
		case "6":
			#TCP
			$type = t('TCP');
		break;
		case "17":
			#UDP
			$type = t('UDP');
		break;
	}
	return $type;
} // function _myntcd_get_packet_type()

/**
 * Ellenorzi a datum formatumot
 * @param date text
 * @return boolean
 */
function _myntcd_chk_date($date) {
	if (preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])-(0[1-9]|[12][[:digit:]]|3[01])$/", $date)) {
		return true;
	} else {
		return false;
	}
} // function _myntcd_chk_date()

/**
 * Ellenorzi az ip formatumot
 * @param ip text
 * @return boolean
 */
function _myntcd_is_ip($ip) {
	$num = "(25[0-5]|2[0-4]\d|[01]?\d\d|\d)";
	return preg_match("/^$num\\.$num\\.$num\\.$num$/", $ip);
} // function _myntcd_is_ip()

