<?php

/**
 * @file
 * Monitoring the users network traffic flow.
 *
 *
 * My Network Traffic Counter Daemon
 * Created / Modify on 2009.01.02. / 2013.02.22.
 */

/**
 * Implementation of hook_help().
 * Display help and module information
 * @param section which section of the site we're displaying help
 * @return text - help text for section
 */
// function myntcd_help($path, $arg) {
// 	$output = '';
// 	switch ($path) {
// 		case "admin/help#description":
// 			$output = t("My Network Traffic Counter Daemon");
// 		break;
// 	}
// 	return $output;
// } // function myntcd_help()

/**
 * Implementation of hook_init().
 * Connect the external database.
 */
function myntcd_init() {
	$myntcd_database = array(
	    'database' => variable_get('myntcd_db'),
	    'username' => variable_get('myntcd_user'),
	    'password' => variable_get('myntcd_pwd'),
	    'host' => variable_get('myntcd_server'),
	    'port' => variable_get('myntcd_port'),
	    'driver' => variable_get('myntcd_server_type'),
	  );
	  Database::addConnectionInfo('myntcd', 'default', $myntcd_database);
} // function myntcd_init

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the myntcd module
 */
function myntcd_permission() {
	return array(
		'my traffic' => array(
			'title' => t('The user can view the traffic of your own.'),
		),
		'traffic manager' => array(
			'title' => t('Traffic manager'),
		),
		'traffic administer' => array(
			'title' => t('traffic administer'),
		),
		'myntcd administer' => array(
			'title' => t('myntcd administer'),
		),
	);
} // function myntcd_permission()

/**
 * Implements hook_menu().
 * @return the menu items.
 */
function myntcd_menu() {
	$items = array();

	//Administrator menus, System admin
	$items['admin/config/sysadmin/myntcd'] = array(
		'title' => 'Myntcd settings',
		'description' => 'Configure My Network Traffic Counter Daemon web base frontend',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_settings'),
		'access arguments' => array('myntcd administer'),
		'file' => 'myntcd.admin.inc',
	);

	// Sajat IP adatainak lekerdezese
	$items['my_traffic'] = array(
		'title' => 'My Traffic',
		'page callback' => 'myntcd_my_traffic',
		'access arguments' => array('my traffic'),
		'weight' => 0,
	);

	$items['my_traffic/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_my_traffic',
		'access arguments' => array('my traffic'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['my_traffic/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('daily'),
		'access arguments' => array('my traffic'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('weekly'),
		'access arguments' => array('my traffic'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('monthly'),
		'access arguments' => array('my traffic'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['my_traffic/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_my_traffic',
		'page arguments' => array('yearly'),
		'access arguments' => array('my traffic'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// IP-k adminisztralasa
	$items['myntcd'] = array(
		'title' => 'Myntcd',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_search_form'),
		'access arguments' => array('traffic manager'),
		'weight' => 1,
		'type' => MENU_NORMAL_ITEM,
	);

	// IP-hez kapcsolodo kep megjelenitese
	$items['myntcd/img'] = array(
		'title' => 'Img',
		'page callback' => 'myntcd_img',
		'access arguments' => array('traffic manager'),
		'type' => MENU_CALLBACK,
		'weight' => 1,
	);

	// IP forgalmi adatai
	$items['myntcd/ip/%'] = array(
		'title' => '!ip',
		'title arguments' => array('!ip' => 2),
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 1,
		'type' => MENU_CALLBACK,
	);
	$items['myntcd/ip/%/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_ip',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/ip/%/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_ip_daily',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_ip_weekly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_ip_monthly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/ip/%/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_ip_yearly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// IP tartomanyok
	$items['myntcd/iprange'] = array(
		'title' => 'IP Ranges',
		'page callback' => 'myntcd_iprange_list',
		'access arguments' => array('traffic manager'),
		'weight' => 3,
		'type' => MENU_NORMAL_ITEM,
	);

	// IP tartomanyok
	$items['myntcd/iprange/%'] = array(
		'title' => '!iprange',
		'title arguments' => array('!iprange' => 2),
		'page callback' => 'myntcd_iprange_daily',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 3,
	);

	$items['myntcd/iprange/%/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_iprange_daily',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_iprange_weekly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_iprange_monthly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/iprange/%/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_iprange_yearly',
		'page arguments' => array(2),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// Top lista
	$items['myntcd/top'] = array(
		'title' => 'Top Lists',
		'page callback' => 'myntcd_top',
		'access arguments' => array('traffic manager'),
		'weight' => 5,
	);

	$items['myntcd/top/summary'] = array(
		'title' => 'Summary',
		'page callback' => 'myntcd_top',
		'access arguments' => array('traffic manager'),
		'weight' => 0,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/top/daily'] = array(
		'title' => 'Daily',
		'page callback' => 'myntcd_top_daily',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 2,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/weekly'] = array(
		'title' => 'Weekly',
		'page callback' => 'myntcd_top_weekly',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/monthly'] = array(
		'title' => 'Monthly',
		'page callback' => 'myntcd_top_monthly',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/top/yearly'] = array(
		'title' => 'Yearly',
		'page callback' => 'myntcd_top_yearly',
		'page arguments' => array(3),
		'access arguments' => array('traffic manager'),
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

	// IP cim szuresek kezelese
	$items['myntcd/filter'] = array(
		'title' => 'Filter',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_blacklist'),
		'access arguments' => array('traffic administer'),
		'weight' => 7,
	);

	$items['myntcd/filter/blacklist'] = array(
		'title' => 'Blacklist',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_blacklist'),
		'access arguments' => array('traffic administer'),
		'weight' => 2,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);

	$items['myntcd/filter/whitelist'] = array(
		'title' => 'Whitelist',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_whitelist'),
		'access arguments' => array('traffic administer'),
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);

	$items['myntcd/filter/new'] = array(
		'title' => 'Add filter',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('myntcd_filter_add'),
		'access arguments' => array('traffic administer'),
		'weight' => 6,
		'type' => MENU_LOCAL_TASK,
	);

	return $items;
} // function myntcd_menu()

/**
 * Implementation of hook_theme()
 */
function myntcd_theme() {
	return array(
		'myntcd_ip' => array(
			'variables' => array(
				'ip' => NULL,
				'path' => NULL,
			),
		),
		'myntcd_tables' => array(
			'variables' => array(
				'rows' => NULL,
				'ip' => NULL,
				'when' => NULL,
				'start' => NULL,
				'stop' => NULL,
				'path' => NULL,
			),
		),
		'myntcd_filter_blacklist' => array(
			'render element' => 'form',
		),
		'myntcd_filter_whitelist' => array(
			'render element' => 'form',
		),
	);
}

/**
 * myntcd_my_traffic: sajat forgalom megjelenitese
 * @param when (daily/weekly/monthly/yearly)
 * @param date monthly eseten kapott datum
 * @return build tomb, amiben a tablazatok megjelenitesehez vannak infok
 */
function myntcd_my_traffic($when = '', $date = '') {
	$output = '';

	// Kliens gep IP cime
	$my_ip = $_SERVER['REMOTE_ADDR'];

	switch ($when) {
		case '':
			$date = date('Y-m-d');

			_myntcd_set_title($my_ip);

			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			$SQL = "SELECT * FROM filter WHERE ip = :ip AND date >= :date AND blacklist = 1";
			$result = db_query($SQL, array(':ip' => $my_ip, ':date' => $date));

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			// if ($filter = db_fetch_array($result)) {
			if ($filter = $result->fetchAssoc()) {
				drupal_set_message(
					t(
						'The IP address transfer blocking: !date',
						array('!date' => $filter['date'].'23:59:59')
					),
				'warning');
			}

			// Bekoszonto kepernyo
			$build['myntcd_my_traffic'] = array(
			  '#theme' => 'myntcd_ip',
			  '#ip' => $my_ip,
			  '#path' => 'my_traffic',
			);
			return $build;
			break;
		case 'daily':
		// Napi forgalom
			$date = date('Y-m-d');

			_myntcd_set_title($my_ip, $date);

			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			// A mai nap forgalmi adatai orankenti bontasban
			$SQL = "SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM now ";
			$SQL .= "WHERE ip = :ip AND date(date) = :date GROUP BY hour(date) ORDER BY date DESC";
			$result = db_query($SQL, array(':ip' => $my_ip, ':date' => $date));

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			// Tablazat sorainak elkeszitese
			_myntcd_get_my_rows($result, $rows, $total, 'H:00');

			// Osszes napi forgalom hozza fuzese a tablazathoz
			_myntcd_get_my_totlal_line($rows, $total);

			$build['myntcd_daily_my_traffic'] = array(
			  '#theme' => 'myntcd_tables',
			  '#when' => 'daily',
			  '#rows' => $rows,
			  '#start' => $date,
			  '#stop' => '',
			  '#ip' => $my_ip,
			  '#path' => 'my_traffic',
			);
			return $build;
			break;
		case 'weekly':
		// Heti forgalom
			$date = date('Y-m-d');
			$start_week = date('Y-m-d', strtotime('-1 week +1 day'));

			_myntcd_set_title($my_ip, $start_week, $date);

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;

			_myntcd_myip2tmptable($my_ip, $start_week, $date);

			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			$SQL = "SELECT date, in_byte, out_byte FROM tmp_table ORDER BY date DESC";
			$result = db_query($SQL);

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			// Tablazat sorainak elkesitese
			_myntcd_get_my_rows($result, $rows, $total, 'Y-m-d');

			// Osszes heti forgalom hozza fuzese a tablazathoz
			_myntcd_get_my_totlal_line($rows, $total);

			$build['myntcd_weekly_my_traffic'] = array(
			  '#theme' => 'myntcd_tables',
			  '#when' => 'weekly',
			  '#rows' => $rows,
			  '#start' => $start_week,
			  '#stop' => $date,
			  '#ip' => $my_ip,
			  '#path' => 'my_traffic',
			);
			return $build;
			break;
		case 'monthly':
		// Havi forgalom
			if ($date == '') {
				$date = date('Y-m-01');
			}
			if (!_myntcd_chk_date($date)) {
				drupal_goto('my_traffic/monthly');
			} else {
				$date = date('Y-m-01', strtotime($date));
			}

			if (strtotime('now') < strtotime($date.' +1 month')) {
				$end_month = date('Y-m-d');
			} else {
				$end_month = date('Y-m-d', strtotime($date.' +1 month -1 day'));
			}

			_myntcd_set_title($my_ip, $date, $end_month);

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;

			_myntcd_myip2tmptable($my_ip, $date, $end_month);

			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			$SQL = "SELECT date, in_byte, out_byte FROM tmp_table ORDER BY date DESC";
			$result = db_query($SQL);

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			// Tablazat sorainak elkesitese
			_myntcd_get_my_rows($result, $rows, $total, 'Y-m-d');

			// Osszes havi forgalom hozza fuzese a tablazathoz
			_myntcd_get_my_totlal_line($rows, $total);

			$build['myntcd_monthly_my_traffic'] = array(
			  '#theme' => 'myntcd_tables',
			  '#when' => 'monthly',
			  '#rows' => $rows,
			  '#start' => $date,
			  '#stop' => $end_month,
			  '#ip' => $my_ip,
			  '#path' => 'my_traffic',
			);
			return $build;
			break;
		case 'yearly':
		// Eves forgalom
			$date = date('Y-m-d');
			$start_year = date('Y-01-01');

			_myntcd_set_title($my_ip, date('Y'));

			$rows = $total = array();
			$total['in'] = $total['out'] = 0;

			_myntcd_myip2tmptable($my_ip, $start_year, $date);

			// Kapcsolodas az SQL szerverhez
			db_set_active('myntcd');

			$SQL = "SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte ";
			$SQL .= "FROM tmp_table GROUP BY month(date) ORDER BY date DESC";
			$result = db_query($SQL);

			// Vissza valtas az alapertelmezett SQL szerverhez
			db_set_active();

			// Tablazat sorainak elkeszitese
			_myntcd_get_my_rows($result, $rows, $total, 'Y. F', 1);

			// Eves forgalom hozza fuzese a tablazathoz
			_myntcd_get_my_totlal_line($rows, $total);

			$build['myntcd_yearly_my_traffic'] = array(
			  '#theme' => 'myntcd_tables',
			  '#when' => 'yearly',
			  '#rows' => $rows,
			  '#start' => $start_year,
			  '#stop' => '',
			  '#ip' => $my_ip,
			  '#path' => 'my_traffic',
			);
			return $build;
			break;
		default:
			drupal_goto('my_traffic');
			break;
	}
} // function my_traffic_myntcd()

/**
 * _myntcd_myip2tmptable: Forgalmi adatok tablazatta alakitasa
 * @param db adatbazis kapcsoalt
 * @param ip ip cim
 * @param start forgalmi adatok osszegyujtesenek kezdeti ideje
 * @param stop forgalmi adatok osszegyujtesenek befejezesi ideje
 */
function _myntcd_myip2tmptable($ip, $start, $stop = '') {
	// Seged tabla definialasa
	if ($stop == '') {
		$stop = date('Y-m-d');
	}

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	$SQL = "CREATE TEMPORARY TABLE tmp_table ";
	$SQL .= "( `ip` varchar(39) default NULL, `date` DATE, ";
	$SQL .= " `in_byte` bigint(20) unsigned NOT NULL default '0', ";
	$SQL .= " `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result = db_query($SQL);

	// aktualis nap adatainak betoltese a seged tablaba
	$SQL = "INSERT INTO tmp_table SELECT ip, date(date), SUM(in_byte), SUM(out_byte) ";
	$SQL .= "FROM now WHERE ip = :ip AND date(date) = :stop GROUP BY date(date)";
	$result = db_query($SQL, array(':ip' => $ip, ':stop' => $stop));

	// megadott intervallum adatainak betoltese a seged tablaba
	$SQL = "INSERT INTO tmp_table SELECT ip, date, SUM(in_byte), SUM(out_byte) ";
	$SQL .= "FROM daily WHERE ip = :ip AND date >= :start AND date <= :stop GROUP BY date";
	$result = db_query($SQL, array(':ip' => $ip, ':start' => $start, ':stop' => $stop));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

} // function _myntcd_ip2tmptable()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye
 * @param rows tablazat sorai
 * @param total osszesitet adatok
 * @param date_format kiirt datum formatuma
 * @param link(0/1) kiirt datum linkelve legyen-e
 */
function _myntcd_get_my_rows(&$result, &$rows, &$total, $date_format, $link = 0) {
	while ($row = $result->fetchAssoc()) {
		// Atalakitja a datumot a kert formatumra
		if ($link) {
			$row['date'] = l(
				format_date(strtotime($row['date']), 'custom', $date_format),
				'my_traffic/monthly/'.date('Y-m-01', strtotime($row['date']))
			);
		} else {
			$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
		}

		// kiszamolja az osszes forgalmat es azt hogy a teljes forgalom hany %-a a kimeno forgalom
		$row['total_byte'] = $row['in_byte'] + $row['out_byte'];
		if ($row['total_byte']) {
			$row['rate'] = (round($row['out_byte'] / $row['total_byte'], 2) * 100).' %';
		} else {
			$row['rate'] = '0 %';
		}

		// a teljes forgalom novelese
		$total['in'] += $row['in_byte'];
		$total['out'] += $row['out_byte'];

		// ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk
		if ($row['in_byte'] <= $row['out_byte']) {
			$warrning = '_warrning';
		} else {
			$warrning = '';
		}
		// tablazat soranak elkeszitese
		$rows[] = array(
			array('data' => $row['date'], 'class' => 'myntcd_date'),
			array('data' => _myntcd_convert_bytes_to_hrf($row['in_byte']), 'class' => 'myntcd_in_byte'),
			array('data' => _myntcd_convert_bytes_to_hrf($row['out_byte']), 'class' => 'myntcd_out_byte'.$warrning),
			array('data' => _myntcd_convert_bytes_to_hrf($row['total_byte']), 'class' => 'myntcd_total_byte'.$warrning),
			array('data' => $row['rate'], 'class' => 'myntcd_rate'.$warrning),
		);
	}
} // function _myntcd_get_my_rows()

/**
 * Teljes forgalom adatanak hozzafuzese a tablazat elejehez
 * @param rows tablazat sorai
 * @param total osszesitet adatok
 */
function _myntcd_get_my_totlal_line(&$rows, $total) {
	// ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk
	if ($total['in'] <= $total['out']) {
		$warrning = '_warrning';
	} else {
		$warrning = '';
	}

	// Osszes napi forgalom hozza fuzese a tablazathoz
	if ($total['in'] + $total['out']) {
		if ($total['out']) {
			$total['rate'] = (round($total['out'] / ($total['in'] + $total['out']), 2) * 100).' %';
		} else {
			$total['rate'] = '0 %';
		}

		$row = array(
			array('data' => t('Total traffic:'), 'class' => 'myntcd_total'),
			array('data' => _myntcd_convert_bytes_to_hrf($total['in']), 'class' => 'myntcd_total_in_byte'),
			array('data' => _myntcd_convert_bytes_to_hrf($total['out']), 'class' => 'myntcd_total_out_byte'.$warrning),
			array('data' => _myntcd_convert_bytes_to_hrf($total['in'] + $total['out']), 'class' => 'myntcd_total_total_byte'.$warrning),
			array('data' => $total['rate'], 'class' => 'myntcd_total_rate'.$warrning),
		);
		// Osszes napi forgalom hozza adasa a tablazat elejehez
		array_unshift($rows, $row);
	}
} // function _myntcd_get_my_totlal_line()

/**
 * Keresesi oldal, ahol ip cimekre lehet keresni
 * @param form
 * @param form_state
 * @return form az oldal megjelenitesehez szukseges adatotkkal ter vissza
 */
function myntcd_search_form($form, &$form_state) {
	// ip kereses
	$form['ip'] = array(
		'#type' => 'textfield',
		'#title' => t('Ip address'),
		'#size' => 45,
		'#maxlength' => 39,
		'#required' => FALSE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Jump'),
	);

	return $form;
} // myntcd_search()

/**
 * Ha keresobe beirt ip cim validalasa
 * @param form
 * @param form_state
 */
function myntcd_search_form_validate($form, &$form_state) {
	if (!_myntcd_is_ip($form_state['values']['ip'])) {
		form_set_error('ip', t('Is not IP address.'));
	}
} // myntcd_search_validate()

/**
 * myntcd_search_submit: az adott ip cim oldalara ugrik
 * @param form
 * @param form_state
 */
function myntcd_search_form_submit($form, &$form_state) {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	$SQL = "SELECT ip FROM now WHERE ip = :ip";
	$result = db_query_range($SQL, 0, 1, array(':ip' => $form_state['values']['ip']));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	if ( $ip = $result->fetchAssoc()) {
		drupal_goto('myntcd/ip/'.$form_state['values']['ip']);
	}
}

/**
 * myntcd_ip: IP traffic summary
 * @param ip
 */
function myntcd_ip($ip) {
	if (_myntcd_is_ip($ip)) {
		$build['myntcd_ip'] = array(
		  '#theme' => 'myntcd_ip',
		  '#ip' => $ip,
		  '#path' => 'myntcd/ip/'.$ip,
		);
		return $build;
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip

/**
 * theme_myntcd_ip: IP traffic summary
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return adott oldallal ter vissza
 */
function theme_myntcd_ip($variables) {
	$ip = $variables['ip'];
	$path = $variables['path'];
	$output = '';

	$output .= '<div class="myntcd_rrd_img">';
	$output .= l(
		'<img src="'.url('myntcd/img/'.$ip.'/daily').'" alt="myntcd_daily_image" />',
		$path.'/daily',
		array('html' => TRUE)
	);
	$output .= '</div>';

	$output .= '<div class="myntcd_rrd_img">';
	$output .= l(
		'<img src="'.url('myntcd/img/'.$ip.'/weekly').'" alt="myntcd_weekly_image" />',
		$path.'/weekly',
		array('html' => TRUE)
	);
	$output .= '</div>';

	$output .= '<div class="myntcd_rrd_img">';
	$output .= l(
		'<img src="'.url('myntcd/img/'.$ip.'/monthly').'" alt="myntcd_monthly_image" />',
		$path.'/monthly',
		array('html' => TRUE)
	);
	$output .= '</div>';

	$output .= '<div class="myntcd_rrd_img">';
	$output .= l(
		'<img src="'.url('myntcd/img/'.$ip.'/yearly').'" alt="myntcd_yearly_image" />',
		$path.'/yearly',
		array('html' => TRUE)
	);
	$output .= '</div>';

	return $output;
} // function theme_myntcd_ip

/**
 * myntcd_ip_daily: IP daily traffic
 * @param ip ip cim
 * @param date kapott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_ip_daily($ip, $date = '') {
	if (_myntcd_is_ip($ip)) {
		if ($date == '') {
			$date = date('Y-m-d');
		} elseif (!_myntcd_chk_date($date)) {
			drupal_goto('myntcd/ip/'.$ip.'/daily');
		}

		_myntcd_set_title($ip, $date);

		// utolso nap masik tablaba van
		if ($date == date('Y-m-d')) {
			$from = "FROM now";
		} else {
			$from = "FROM daily";
		}
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		// A mai nap forgalmi adatai orankenti bontasban
		$SQL = "SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet, ";
		$SQL .= "SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte ".$from." ";
		$SQL .= "WHERE ip = :ip AND date(date) = :date GROUP BY hour(date), type ORDER BY date DESC";
		$result = db_query($SQL, array(':ip' => $ip, ':date' => $date));

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$rows = $total = array();
		$total['in'] = $total['out'] = 0;
		// Tablazat sorainak elokeszitese
		_myntcd_get_ip_all_rows($result, $rows, $total, 'H:00', $ip, 'daily');

		// Ha nem aktualis nap van egyszerubb tablazat kell
		if ($date != date('Y-m-d')) {
			$rows = array();
		}
		// Napi forgalom hozza fuzese a tablazathoz
		_myntcd_get_ip_line($rows, $total);

		$build['myntcd_ip_daily'] = array(
		  '#theme' => 'myntcd_tables',
		  '#ip' => $ip,
		  '#when' => 'daily',
		  '#rows' => $rows,
		  '#start' => $date,
		  '#stop' => '',
		  '#path' => 'myntcd/ip',
		);
		return $build;
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_daily

/**
 * myntcd_ip_weekly: IP weekly traffic
 * @param ip ip cim
 * @param date kapott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_ip_weekly($ip, $date = '') {
	if (_myntcd_is_ip($ip)) {
		if ($date == '') {
			$date = date('Y-m-d');
		} elseif (!_myntcd_chk_date($date)) {
			drupal_goto('myntcd/ip/'.$ip.'/weekly');
			return;
		}

		$start_week = date('Y-m-d', strtotime($date.' -1 week +1 day'));

		_myntcd_set_title($ip, $start_week, $date);

		// forgalmi adatok betoltese az atmenti tablaba
		_myntcd_ip2tmptable($ip, $start_week, $date);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet, ";
		$SQL .= "SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table ";
		$SQL .= "GROUP BY date, ip, type ORDER BY date DESC";
		$result = db_query($SQL);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$rows = $total = array();
		// Tablazat sorainak elokeszitese
		_myntcd_get_ip_all_rows($result, $rows, $total, 'Y-m-d', $ip, 'weekly');
		// Heti forgalom hozza fuzese a tablazathoz
		_myntcd_get_ip_line($rows, $total);

		$build['myntcd_ip_weekly'] = array(
		  '#theme' => 'myntcd_tables',
		  '#ip' => $ip,
		  '#when' => 'weekly',
		  '#rows' => $rows,
		  '#start' => $start_week,
		  '#stop' => $date,
		  '#path' => 'myntcd/ip',
		);
		return $build;
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_weekly

/**
 * myntcd_ip_monthly: IP monthly traffic
 * @param ip ip cim
 * @param month kapott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_ip_monthly($ip, $month = '') {
	if (_myntcd_is_ip($ip)) {
		if ($month == '') {
			$month = date('Y-m');
		} elseif (!preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])$/", $month)) {
			drupal_goto('myntcd/ip/'.$ip.'/monthly');
		}

		$start_month = $month.'-01';
		if ( $month == date('Y-m') ) {
			$end_month = $month.date('-d');
		} else {
			$end_month = date('Y-m-d', strtotime('-1 day', strtotime('+1 month', strtotime($month."-01"))));
		}

		_myntcd_set_title($ip, $start_month, $end_month);

		// forgalmi adatok betoltese az atmenti tablaba
		_myntcd_ip2tmptable($ip, $start_month, $end_month);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet, ";
		$SQL .= "SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table ";
		$SQL .= "GROUP BY date, ip, type ORDER BY date DESC";
		$result = db_query($SQL);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$rows = $total = array();
		// Tablazat sorainak elokeszitese
		_myntcd_get_ip_all_rows($result, $rows, $total, 'Y-m-d', $ip, 'monthly');
		// Heti forgalom hozza fuzese a tablazathoz
		_myntcd_get_ip_line($rows, $total);

		$build['myntcd_ip_monthly'] = array(
		  '#theme' => 'myntcd_tables',
		  '#ip' => $ip,
		  '#when' => 'monthly',
		  '#rows' => $rows,
		  '#start' => $start_month,
		  '#stop' => $end_month,
		  '#path' => 'myntcd/ip',
		);
		return $build;
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_monthly

/**
 * myntcd_ip_yearly: IP yearly traffic
 * @param ip ip cim
 * @param year kapott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_ip_yearly($ip, $year = '') {
	if (_myntcd_is_ip($ip)) {
		if ($year == '') {
			$year = date('Y');
		} elseif (!preg_match("/^([123456789][[:digit:]]{3})$/", $year)) {
			drupal_goto('myntcd/ip/'.$ip.'/yearly');
		}

		if ( $year == date('Y') ) {
			$start_year = date('Y-01-01');
			$stop_year = date('Y-m-d');
		} else {
			$start_year = $year.'-01-01';
			$stop_year = $year.'-12-31';
		}

		_myntcd_set_title($ip, $start_year, $stop_year);

		// forgalmi adatok betoltese az atmenti tablaba
		_myntcd_ip2tmptable($ip, $start_year, $stop_year);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet, ";
		$SQL .= "SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table ";
		$SQL .= "GROUP BY month(date), ip, type ORDER BY date DESC";
		$result = db_query($SQL);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$rows = $total = array();
		// Tablazat sorainak elokeszitese
		_myntcd_get_ip_all_rows($result, $rows, $total, 'Y. F', $ip, 'yearly');
		// Heti forgalom hozza fuzese a tablazathoz
		_myntcd_get_ip_line($rows, $total);

		$build['myntcd_ip_yearly'] = array(
		  '#theme' => 'myntcd_tables',
		  '#ip' => $ip,
		  '#when' => 'yearly',
		  '#rows' => $rows,
		  '#start' => $start_year,
		  '#stop' => $stop_year,
		  '#path' => 'myntcd/ip',
		);
		return $build;
	} else {
		drupal_goto('myntcd');
	}
} // function myntcd_ip_yearly

/**
 * theme_myntcd_when: egyseges theme
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return adott oldallal ter vissza
 */
function theme_myntcd_tables($variables) {

	$ip = $variables['ip'];
	$when = $variables['when'];
	$rows = $variables['rows'];
	$start = $variables['start'];
	$stop = $variables['stop'];
	$path = $variables['path'];

	$output = '';

	if ($path == 'myntcd/ip' || $path == 'myntcd/iprange' || $path == 'myntcd/top') {
		$output .= _myntcd_navigation($ip, $when, $start, $stop, $path);
	}
	if ($path == 'myntcd/ip' || $path == 'my_traffic') {
		$output .= '<div class="myntcd_rrd_img">';
		$output .= '<img src="'.url('myntcd/img/'.$ip.'/'.$when.'/'.$start.'/'.$stop).'" alt="myntcd_'.$when.'_image" />';
		$output .= '</div>';
	}

	if ($path == 'myntcd/ip') {
		$header = array(
			array('data' => t('Time')),
			array('data' => t('Type')),
			array('data' => t('In Packet'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out Packet'), 'class' => 'myntcd_header_right'),
			array('data' => t('Total Packet'), 'class' => 'myntcd_header_right'),
			array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
		);
	} elseif ($path == 'myntcd/iprange_list') {
		$header = array(
			array('data' => t('IP Address')),
			array('data' => t('Operations'), 'colspan' => '4'),
		);
	} else {
		if ($path == 'my_traffic') {
			$first_column = 'Time';
		} else {
			$first_column = 'IP Address';
		}

		$header = array(
			array('data' => t($first_column)),
			array('data' => t('In Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Total Byte'), 'class' => 'myntcd_header_right'),
			array('data' => t('Out%'), 'class' => 'myntcd_header_right'),
		);
	}

	if ($path == 'myntcd/top_all' || $path == 'myntcd/top') {
		$output .= '<div class = "myntcd_top_label">';
		if ($path == 'myntcd/top_all') {
			$output .= t('Daily Top !num total byte', array('!num' => '20'));
		} else {
			$output .= t(' Top !num in byte', array('!num' => '20'));
		}
		$output .= ':</div>';

		$output .= '<div class = "myntcd_top_table">';
		if ($path == 'myntcd/top_all') {
			$table = $rows['daily'];
		} else {
			$table = $rows['in'];
		}
		$output .= theme('table', array('header' => $header, 'rows' => $table, 'empty' => t('No content available.')));
		$output .= '</div>';

		$output .= '<div class = "myntcd_top_label">';
		if ($path == 'myntcd/top_all') {
			$output .= t('Weekly Top !num total byte', array('!num' => '20'));
		} else {
			$output .= t(' Top !num out byte', array('!num' => '20'));
		}
		$output .= ':</div>';

		$output .= '<div class = "myntcd_top_table">';
		if ($path == 'myntcd/top_all') {
			$table = $rows['weekly'];
		} else {
			$table = $rows['out'];
		}
		$output .= theme('table', array('header' => $header, 'rows' => $table, 'empty' => t('No content available.')));
		$output .= '</div>';

		$output .= '<div class = "myntcd_top_label">';
		if ($path == 'myntcd/top_all') {
			$output .= t('Monthly Top !num total byte', array('!num' => '20'));
		} else {
			$output .= t(' Top !num total byte', array('!num' => '20'));
		}
		$output .= ':</div>';

		$output .= '<div class = "myntcd_top_table">';
		if ($path == 'myntcd/top_all') {
			$table = $rows['monthly'];
		} else {
			$table = $rows['total'];
		}
		$output .= theme('table', array('header' => $header, 'rows' => $table, 'empty' => t('No content available.')));
		$output .= '</div>';

		if ($path == 'myntcd/top_all') {
			$output .= '<div class = "myntcd_top_label">';
			$output .= t('Yearly Top !num total byte', array('!num' => '20'));
			$output .= ':</div>';

			$output .= '<div class = "myntcd_top_table">';
			$output .= theme('table', array('header' => $header, 'rows' => $rows['yearly'], 'empty' => t('No content available.')));
			$output .= '</div>';
		}
	} else {
		if ($path == 'myntcd/iprange') {
			$output .= '<div class = "myntcd_top_table">';
		}
		$output .= theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No content available.')));
		if ($path == 'myntcd/iprange') {
			$output .= '</div>';
		}
	}

	return $output;
} // function theme_myntcd_when()

/**
 * Navigacios linkeket allitja elo
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 * @param start forgalmi adatok kezdeti ideje
 * @param stop forgalmi adatok befejezesi ideje
 * @param path megadott utvonal reszlet, ami itt kiegeszul
 * @return a legeneralt linkek html kodjaval ter vissza
 */
function _myntcd_navigation($ip, $when, $start, $stop, $path) {
	$output = '';

	switch ($when) {
		case 'daily':
			$minus_date = $start.' -1 day';
			$plus_date = $start.' +1 day';
			$show_next_date = $start;
			$date_format = 'Y-m-d';
			break;
		case 'weekly':
			$minus_date = $stop.' -7 day';
			$plus_date = $stop.' +7 day';
			$show_next_date = $stop;
			$date_format = 'Y-m-d';
			break;
		case 'monthly':
			$minus_date = $start.' -1 month';
			$plus_date = $start.' +1 month';
			$show_next_date = $stop;
			$date_format = 'Y-m';
			break;
		case 'yearly':
			$minus_date = $start.' -1 year';
			$plus_date = $start.' +1 year';
			$show_next_date = $stop;
			$date_format = 'Y';
			break;
	}

	$output .= '<div class="myntcd-navigation clear-block">';

	$prev_date = date($date_format, strtotime($minus_date));
	if ($ip != '') {
		$full_path = $path.'/'.$ip.'/'.$when;
	} else {
		$full_path = $path.'/'.$when;
	}
	$output .= l(
		t('previous'),
		$full_path.'/'.$prev_date,
		array('attributes' => array('class' => 'myntcd-previous'))
	);

	if ($show_next_date == date('Y-m-d')) {
		$output .= '<span class="myntcd-next-grey">'.t('next').'</span>';
	} else {
		$next_date = date($date_format, strtotime($plus_date));
		$output .= l(
			t('next'),
			$full_path.'/'.$next_date,
			array('attributes' => array('class' => 'myntcd-next'))
		);
	}
	$output .= '</div><br />';

	return $output;
}

/**
 * A fejlecen megjeleno szoveget kesziti el
 * @param ip ip cim
 * @param start forgalmi adatok kezdeti ideje
 * @param stop forgalmi adatok befejezesi ideje
 * @return az oldalhoz megfelelo fejleccel ter vissza
 */
function _myntcd_set_title($ip, $start = '', $stop = '') {
	if ($start != '') {
		if ($stop != '') {
			$date = $start.' - '.$stop;
		} else {
			$date = $start;
		}
		if (!_myntcd_is_ip($ip)) {
			return drupal_set_title(t('!when Top !num (!date)', array('!when' => $ip, '!num' => '20', '!date' => $date)));
		} else {
			return drupal_set_title(t('!title (!date)', array('!title' => $ip, '!date' => $date)));
		}
	} else {
		return drupal_set_title(t('!title', array('!title' => $ip)));
	}
}

/**
 * myntcd_iprange_list: list iprange
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_iprange_list() {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// IP tartomanyok listazasa
	$SQL = "SELECT iprange FROM ipranges ORDER BY iprange ASC";
	$result = db_query($SQL);

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$rows = array();
	$rows[] = array(
		array('data' => l(t('All'), 'myntcd/iprange/all') ),
		array('data' => l(t('Daily'), 'myntcd/iprange/all') ),
		array('data' => l(t('Weekly'), 'myntcd/iprange/all/weekly') ),
		array('data' => l(t('Monthly'), 'myntcd/iprange/all/monthly') ),
		array('data' => l(t('Yearly'), 'myntcd/iprange/all/yearly') ),
	);

	while ($row = $result->fetchAssoc()) {
		if ( _myntcd_is_ip($row['iprange']) ) {
			$rows[] = array(
				array('data' => l($row['iprange'], 'myntcd/iprange/'.$row['iprange']) ),
				array('data' => l(t('Daily'), 'myntcd/iprange/'.$row['iprange']) ),
				array('data' => l(t('Weekly'), 'myntcd/iprange/'.$row['iprange'].'/weekly') ),
				array('data' => l(t('Monthly'), 'myntcd/iprange/'.$row['iprange'].'/monthly') ),
				array('data' => l(t('Yearly'), 'myntcd/iprange/'.$row['iprange'].'/yearly') ),
			);
		}
	}

	$build['myntcd_iprange_list'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => '',
	  '#when' => 'all',
	  '#rows' => $rows,
	  '#start' => '',
	  '#stop' => '',
	  '#path' => 'myntcd/iprange_list',
	);
	return $build;
} // function myntcd_iprange_list

/**
 * myntcd_iprange_daily: iprange daily traffic
 * @param iprange adott ip tartomany
 * @param date datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_iprange_daily($iprange, $date = '') {
	$output = '';

	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/daily');
		return;
	}

	_myntcd_set_title($iprange, $date);

	if ($date == date('Y-m-d')) {
		$nowordaily = "now";
	} else {
		$nowordaily = "daily";
	}

	if ($iprange == 'all') {
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT ipranges.ipr_id, ipranges.iprange, SUM($nowordaily.in_byte) AS in_byte, ";
		$SQL .= "SUM($nowordaily.out_byte) AS out_byte, SUM($nowordaily.in_byte) + SUM($nowordaily.out_byte) AS total ";
		$SQL .= "FROM $nowordaily, ipranges WHERE ipranges.ipr_id = $nowordaily.ipr_id AND date($nowordaily.date) = :date ";
		$SQL .= "GROUP BY ipranges.ipr_id ORDER BY $nowordaily.ip";
		$result = db_query($SQL, array(':date' => $date));

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'daily', 'iprange');

	} elseif ( _myntcd_is_ip($iprange) ) {
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		// IP tartomanyhoz tartozo napi forgalom
		$SQL = "SELECT ipranges.iprange, $nowordaily.ip, SUM( $nowordaily.in_byte ) AS in_byte, SUM( $nowordaily.out_byte ) AS out_byte, ";
		$SQL .= "SUM( $nowordaily.in_byte ) + SUM( $nowordaily.out_byte ) AS total ";
		$SQL .= "FROM $nowordaily, ipranges WHERE ipranges.ipr_id = $nowordaily.ipr_id AND date( $nowordaily.date ) = :date AND ipranges.iprange = :iprange ";
		$SQL .= "GROUP BY $nowordaily.ip ORDER BY total DESC";
		$result = db_query($SQL, array(':date' => $date, ':iprange' => $iprange));

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'daily');

	} else {
		drupal_goto('myntcd/iprange');
	}

	$build['myntcd_iprange_daily'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => $iprange,
	  '#when' => 'daily',
	  '#rows' => $rows,
	  '#start' => $date,
	  '#stop' => '',
	  '#path' => 'myntcd/iprange',
	);
	return $build;
} // function myntcd_iprange_daily

/**
 * myntcd_iprange_weekly: iprange weekly traffic
 * @param iprange adott ip tartomany
 * @param date datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_iprange_weekly($iprange, $date = '') {
	$output = '';

	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/weekly');
		return;
	}

	$start_week = date('Y-m-d', strtotime($date.' -1 week'));

	_myntcd_set_title($iprange, $start_week, $date);

	if ($iprange == 'all') {

		// Seged tabla definialasa es feltoltese
		_myntcd_traffic2tmptable($start_week, $date);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT ipranges.ipr_id, ipranges.iprange, SUM(tmp_table.in_byte) AS in_byte, ";
		$SQL .= "SUM(tmp_table.out_byte) AS out_byte, SUM(tmp_table.in_byte) + SUM(tmp_table.out_byte) AS total ";
		$SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id ";
		$SQL .= "GROUP BY ipranges.ipr_id ORDER BY tmp_table.ip";
		$result = db_query($SQL);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'weekly', 'iprange');

	} elseif ( _myntcd_is_ip($iprange) ) {

		// Seged tabla definialasa es feltoltese
		_myntcd_traffic2tmptable($start_week, $date);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT ipranges.iprange, tmp_table.ip, SUM( tmp_table.in_byte ) AS in_byte, SUM( tmp_table.out_byte ) AS out_byte, ";
		$SQL .= "SUM( tmp_table.in_byte ) + SUM( tmp_table.out_byte ) AS total ";
		$SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id AND ipranges.iprange = :iprange ";
		$SQL .= "GROUP BY tmp_table.ip ORDER BY total DESC";
		$result = db_query($SQL, array(':iprange' => $iprange));

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'weekly');

	} else {
		drupal_goto('myntcd/iprange');
	}

	$build['myntcd_iprange_weekly'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => $iprange,
	  '#when' => 'weekly',
	  '#rows' => $rows,
	  '#start' => $start_week,
	  '#stop' => $date,
	  '#path' => 'myntcd/iprange',
	);
	return $build;
} // function myntcd_iprange_weekly

/**
 * myntcd_iprange_monthly: iprange monthly traffic
 * @param iprange adott ip tartomany
 * @param date datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_iprange_monthly($iprange, $month = '') {
	$output = '';

	if ($month == '') {
		$month = date('Y-m');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])$/", $month)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/monthly');
	}

	$start_month = $month.'-01';
	if ( $month == date('Y-m') ) {
		$end_month = $month.date('-d');
	} else {
		$end_month = date('Y-m-d', strtotime('-1 day', strtotime('+1 month', strtotime($month."-01"))));
	}

	_myntcd_set_title($iprange, $start_month, $end_month);

	if ($iprange == 'all') {
		// Seged tabla definialasa es feltoltese
		_myntcd_traffic2tmptable($start_month, $end_month);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT ipranges.ipr_id, ipranges.iprange, SUM(tmp_table.in_byte) AS in_byte, ";
		$SQL .= "SUM(tmp_table.out_byte) AS out_byte, SUM(tmp_table.in_byte) + SUM(tmp_table.out_byte) AS total ";
		$SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id ";
		$SQL .= "GROUP BY ipranges.ipr_id ORDER BY tmp_table.ip";
		$result = db_query($SQL);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'monthly', 'iprange');

	} elseif ( _myntcd_is_ip($iprange) ) {
		// Seged tabla definialasa es feltoltese
		_myntcd_traffic2tmptable($start_month, $end_month);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT ipranges.iprange, tmp_table.ip, SUM( tmp_table.in_byte ) AS in_byte, SUM( tmp_table.out_byte ) AS out_byte, ";
		$SQL .= "SUM( tmp_table.in_byte ) + SUM( tmp_table.out_byte ) AS total ";
		$SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id AND ipranges.iprange = :iprange ";
		$SQL .= "GROUP BY tmp_table.ip ORDER BY total DESC";
		$result = db_query($SQL, array(':iprange' => $iprange));

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'monthly');

	} else {
		drupal_goto('myntcd/iprange');
	}

	$build['myntcd_iprange_monthly'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => $iprange,
	  '#when' => 'monthly',
	  '#rows' => $rows,
	  '#start' => $start_month,
	  '#stop' => $end_month,
	  '#path' => 'myntcd/iprange',
	);
	return $build;
} // function myntcd_iprange_monthly

/**
 * myntcd_iprange_yearly: iprange yearly traffic
 * @param iprange adott ip tartomany
 * @param date datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_iprange_yearly($iprange, $year = '') {
	$output = '';

	// Eves toplista
	if ($year == '') {
		$year = date('Y');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})$/", $year)) {
		drupal_goto('myntcd/iprange/'.$iprange.'/yearly');
	}

	if ( $year == date('Y') ) {
		$start_year = date('Y-01-01');
		$stop_year = date('Y-m-d');
	} else {
		$start_year = $year.'-01-01';
		$stop_year = $year.'-12-31';
	}

	_myntcd_set_title($iprange, $start_year, $stop_year);

	if ($iprange == 'all') {
		// Seged tabla definialasa es feltoltese
		_myntcd_traffic2tmptable($start_year, $stop_year);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT ipranges.ipr_id, ipranges.iprange, SUM(tmp_table.in_byte) AS in_byte, ";
		$SQL .= "SUM(tmp_table.out_byte) AS out_byte, SUM(tmp_table.in_byte) + SUM(tmp_table.out_byte) AS total ";
		$SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id ";
		$SQL .= "GROUP BY ipranges.ipr_id ORDER BY tmp_table.ip";
		$result = db_query($SQL);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'yearly', 'iprange');

	} elseif ( _myntcd_is_ip($iprange) ) {
		// Seged tabla definialasa es feltoltese
		_myntcd_traffic2tmptable($start_year, $stop_year);

		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		$SQL = "SELECT ipranges.iprange, tmp_table.ip, SUM( tmp_table.in_byte ) AS in_byte, SUM( tmp_table.out_byte ) AS out_byte, ";
		$SQL .= "SUM( tmp_table.in_byte ) + SUM( tmp_table.out_byte ) AS total ";
		$SQL .= "FROM tmp_table, ipranges WHERE ipranges.ipr_id = tmp_table.ipr_id AND ipranges.iprange = :iprange ";
		$SQL .= "GROUP BY tmp_table.ip ORDER BY total DESC";
		$result = db_query($SQL, array(':iprange' => $iprange));

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		_myntcd_get_ip_rows($result, $rows, 'yearly');

	} else {
		drupal_goto('myntcd/iprange');
	}

	$build['myntcd_iprange_yearly'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => $iprange,
	  '#when' => 'yearly',
	  '#rows' => $rows,
	  '#start' => $start_year,
	  '#stop' => $stop_year,
	  '#path' => 'myntcd/iprange',
	);
	return $build;
} // function myntcd_iprange_yearly

/**
 * myntcd_top: traffic toplist
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_top() {
	// Bekoszonto kepernyo
	$date = date('Y-m-d');

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// Napi Top lista
	$order_by = 'total';
	$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
	$SQL .= "FROM now WHERE date(date) = :date GROUP BY ip, date(date) ORDER BY ".$order_by." DESC";
	$result = db_query_range($SQL, 0, 20, array(':date' => $date));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$tables['total'] = array();
	// Tablazat sorainak elkeszitese
	_myntcd_get_ip_rows($result, $tables['daily'], 'daily');

	if (date('Y-m-d', strtotime($date.' -1 week')) < date('Y-m-01')) {
		$start_week = date('Y-m-01');
	} else {
		$start_week = date('Y-m-d', strtotime($date.' -1 week'));
	}
	$start_month = date('Y-m-01');
	$start_year = date('Y-01-01');

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// Seged tabla definialasa
	$SQL = "CREATE TEMPORARY TABLE tmp_table ";
	$SQL .= "( `ip` varchar(39) default NULL, `date` DATE, `in_byte` bigint(20) unsigned NOT NULL default '0', ";
	$SQL .= "`out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result = db_query($SQL);

	$SQL = "INSERT INTO tmp_table SELECT ip, date(date), SUM(in_byte), SUM(out_byte) FROM now ";
	$SQL .= "WHERE date(date) = :date GROUP BY ip";
	$result = db_query($SQL, array(':date' => $date));

	// aktualis ev adatainak betoltese a seged tablaba
	$SQL = "INSERT INTO tmp_table SELECT ip, date, SUM(in_byte), SUM(out_byte) FROM daily ";
	$SQL .= "WHERE date >= :start_year AND date <= :date GROUP BY ip, date";
	$result = db_query($SQL, array(':start_year' => $start_year, ':date' => $date));

	// Heti Top lista
	$order_by = 'total';
	$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
	$SQL .= "FROM tmp_table WHERE date >= :start_week AND date <= :date GROUP BY ip  ORDER BY ".$order_by." DESC";
	$result = db_query_range($SQL, 0, 20, array(':start_week' => $start_week, ':date' => $date));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$tables['total'] = array();
	// Tablazat sorainak elkeszitese
	_myntcd_get_ip_rows($result, $tables['weekly'], 'weekly');

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// Havi Top lista
	$order_by = 'total';
	$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
	$SQL .= "FROM tmp_table WHERE date >= :start_month AND date <= :date GROUP BY ip  ORDER BY ".$order_by." DESC";
	$result = db_query_range($SQL, 0, 20, array(':start_month' => $start_month, ':date' => $date));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$tables['total'] = array();
	// Tablazat sorainak elkeszitese
	_myntcd_get_ip_rows($result, $tables['monthly'], 'monthly');

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	// Eves Top lista
	$order_by = 'total';

	$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
	$SQL .= "FROM tmp_table WHERE date >= :start_year AND date <= :date GROUP BY ip  ORDER BY ".$order_by." DESC";
	$result = db_query_range($SQL, 0, 20, array(':start_year' => $start_year, ':date' => $date));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$tables['total'] = array();
	// Tablazat sorainak elkeszitese
	_myntcd_get_ip_rows($result, $tables['yearly'], 'yearly');

	$build['myntcd_top'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => '',
	  '#when' => 'all',
	  '#rows' => $tables,
	  '#start' => '',
	  '#stop' => '',
	  '#path' => 'myntcd/top_all',
	);
	return $build;
} // function myntcd_top

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye
 * @param rows tablazat sorai
 * @param when (daily/weekly/monthly/yearly)
 * @param date_format kiirt datum formatuma
 * @param as lekerdezes neve
 */
function _myntcd_get_ip_rows($result, &$rows, $when, $as = 'ip') {
		// link elkeszitese, valamint tartomany helyes kiiratasa
		if ($as != 'iprange') {
			$link = 'ip';
		} else {
			$link = 'iprange';
		}

	// while ($row = db_fetch_array($result)) {
	while ($row = $result->fetchAssoc()) {
		if ( _myntcd_is_ip($row[$as]) ) {

			// link elkeszitese, valamint tartomany helyes kiiratasa
			$row[$as] = l($row[$as], 'myntcd/'.$link.'/'.$row[$as].'/'.$when);
			// kiszamolja az osszes forgalmat es azt hogy a teljes forgalom hany %-a a kimeno forgalom
			if ($row['total']) {
				$row['rate'] = (round($row['out_byte'] / $row['total'], 2) * 100).' %';
			} else {
				$row['rate'] = '0 %';
			}

			// ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk
			if ($row['in_byte'] <= $row['out_byte']) {
				$warrning = '_warrning';
			} else {
				$warrning = '';
			}

			// tablazat soranak elkeszitese
			$rows[] = array(
				array('data' => $row[$as], 'class' => 'myntcd_'.$as),
				array('data' => _myntcd_convert_bytes_to_hrf($row['in_byte']), 'class' => 'myntcd_in_byte'),
				array('data' => _myntcd_convert_bytes_to_hrf($row['out_byte']), 'class' => 'myntcd_out_byte'.$warrning),
				array('data' => _myntcd_convert_bytes_to_hrf($row['total']), 'class' => 'myntcd_total_byte'.$warrning),
				array('data' => $row['rate'], 'class' => 'myntcd_rate'.$warrning),
			);
		}
	}
} // function _myntcd_get_ip_rows()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye
 * @param rows tablazat sorainak elokeszitese
 * @param total osszesitet adatok
 * @param date_format kiirt datum formatuma
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 */
function _myntcd_get_ip_all_rows($result, &$rows, &$total, $date_format, $ip = '', $when = '') {
	while ($row = $result->fetchAssoc()) {
		// Linkelhetove alakitja a datumot
		switch ($when) {
			case 'weekly':
			case 'monthly':
				$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
				$row['date'] = l($row['date'], 'myntcd/ip/'.$ip.'/daily/'.$row['date']);
			break;
			case 'yearly':
				$row['date'] = l(
					format_date(strtotime($row['date'].' 22:00'), 'custom', $date_format),
					'myntcd/ip/'.$ip.'/monthly/'.date('Y-m', strtotime($row['date']))
				);
				break;

			default:
				$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
			break;
		}

		// a teljes forgalom novelese
		$total[0]['in_packet'] += $row['in_packet'];
		$total[0]['out_packet'] += $row['out_packet'];
		$total[0]['in_byte'] += $row['in_byte'];
		$total[0]['out_byte'] += $row['out_byte'];
		$total[$row['type']]['in_packet'] += $row['in_packet'];
		$total[$row['type']]['out_packet'] += $row['out_packet'];
		$total[$row['type']]['in_byte'] += $row['in_byte'];
		$total[$row['type']]['out_byte'] += $row['out_byte'];

		// tablazat soranak elokeszitese
		$rows[$row['date']][$row['type']] = array(
			'type' => $row['type'],
			'in_packet' => $row['in_packet'],
			'out_packet' => $row['out_packet'],
			'total_packet' => $row['in_packet'] + $row['out_packet'],
			'in_byte' => $row['in_byte'],
			'out_byte' => $row['out_byte'],
			'total_byte' => $row['in_byte'] + $row['out_byte'],
		);
	}
} // function _myntcd_get_ip_all_rows()

/**
 * Csomaginfok szerinti feldolgozas
 * @param rows tablazat sorainak elokeszitese
 * @param total osszesitet adatok
 */
function _myntcd_get_ip_line(&$rows, $total) {
	// Osszesitet adatok hozzafuzese a tablazathoz, osszesitve es tipusonkent
	foreach (array(0, 6, 17, 1, -1) as $element) {
		if (array_key_exists($element, $total)) {
			// ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk
			if ($total[$element]['in_byte'] <= $total[$element]['out_byte']) {
				$warrning = '_warrning';
			} else {
				$warrning = '';
			}

			// kiszamolja hogy a teljes forgalom hany %-a a kimeno forgalom
			if ($total[$element]['out_byte']) {
				$total[$element]['rate'] = (round($total[$element]['out_byte'] / ($total[$element]['in_byte'] + $total[$element]['out_byte']), 2) * 100).' %';
			} else {
				$total[$element]['rate'] = '0 %';
			}

			// Sorok feliratozasa
			if ($element == 0) {
				$date = t('Total traffic:');
				$type = '';
			} else {
				$date = '';
				$type = _myntcd_get_packet_type($element);
			}

			// Tablazat sorai
			$tl[] = array(
				array('data' => $date, 'class' => 'myntcd_total_total'),
				array('data' => $type, 'class' => 'myntcd_total_type'),
				array('data' => number_format($total[$element]['in_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_in_packet'),
				array('data' => number_format($total[$element]['out_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_out_packet'.$warrning),
				array('data' => number_format(($total[$element]['in_packet'] + $total[$element]['out_packet']), 0, '', ' ').' db', 'class' => 'myntcd_total_total_packet'.$warrning),
				array('data' => _myntcd_convert_bytes_to_hrf($total[$element]['in_byte']), 'class' => 'myntcd_total_in_byte'),
				array('data' => _myntcd_convert_bytes_to_hrf($total[$element]['out_byte']), 'class' => 'myntcd_total_out_byte'.$warrning),
				array('data' => _myntcd_convert_bytes_to_hrf($total[$element]['in_byte'] + $total[$element]['out_byte']), 'class' => 'myntcd_total_total_byte'.$warrning),
				array('data' => $total[$element]['rate'], 'class' => 'myntcd_total_rate'.$warrning),
			);
		}
	}

	// Vegig megy a tomb sorain
	while (!is_null($key = key($rows))) {
		$rows[$key][0]['date'] = $key;
		// Osszesiti az adott datumhoz tartozo forgalmi adatokat
		foreach (array(6, 17, 1, -1) as $element) {
			$rows[$key][0]['in_packet'] += $rows[$key][$element]['in_packet'];
			$rows[$key][0]['out_packet'] += $rows[$key][$element]['out_packet'];
			$rows[$key][0]['total_packet'] += $rows[$key][$element]['total_packet'];
			$rows[$key][0]['in_byte'] += $rows[$key][$element]['in_byte'];
			$rows[$key][0]['out_byte'] += $rows[$key][$element]['out_byte'];
			$rows[$key][0]['total_byte'] += $rows[$key][$element]['total_byte'];
		}

		// Hozza fuzi a tablazat soraihoz a datumhoz tartozo adatokat
		foreach (array(0, 6, 17, 1, -1) as $element) {
			// A letezo forgalom tipus kerul feldolgozasra
			if (array_key_exists($element, $rows[$key])) {
				// ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk
				if ($rows[$key][$element]['in_byte'] <= $rows[$key][$element]['out_byte']) {
					$warrning_byte = '_warrning';
				} else {
					$warrning_byte = '';
				}

				// ha a kimeno csomag szam tul nagy akkor azt mas stilussal jeloljuk
				if ($rows[$key][$element]['in_packet'] <= $rows[$key][$element]['out_packet']) {
					$warrning_packet = '_warrning';
				} else {
					$warrning_packet = '';
				}

				if ($rows[$key][$element]['total_byte']) {
					$rows[$key][$element]['rate'] = (round($rows[$key][$element]['out_byte'] / $rows[$key][$element]['total_byte'], 2) * 100).' %';
				} else {
					$rows[$key][$element]['rate'] = '0 %';
				}

				$tl[] = array(
					array('data' => $rows[$key][$element]['date'], 'class' => 'myntcd_date'),
					array('data' => _myntcd_get_packet_type($rows[$key][$element]['type']), 'class' => 'myntcd_type'),
					array('data' => number_format($rows[$key][$element]['in_packet'], 0, '', ' ').' db', 'class' => 'myntcd_in_packet'),
					array('data' => number_format($rows[$key][$element]['out_packet'], 0, '', ' ').' db', 'class' => 'myntcd_out_packet'.$warrning_packet),
					array('data' => number_format($rows[$key][$element]['total_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_packet'.$warrning_packet),
					array('data' => _myntcd_convert_bytes_to_hrf($rows[$key][$element]['in_byte']), 'class' => 'myntcd_in_byte'),
					array('data' => _myntcd_convert_bytes_to_hrf($rows[$key][$element]['out_byte']), 'class' => 'myntcd_out_byte'.$warrning_byte),
					array('data' => _myntcd_convert_bytes_to_hrf($rows[$key][$element]['total_byte']), 'class' => 'myntcd_total_byte'.$warrning_byte),
					array('data' => $rows[$key][$element]['rate'], 'class' => 'myntcd_rate'.$warrning_byte),
				);
			}
		}
		next($rows);
	}
	$rows = $tl;
} // function _myntcd_get_ip_line()

/**
 * _myntcd_ip2tmptable: Forgalmi adatok tablazatta alakitasa
 * @param ip ip cim
 * @param start forgalmi adatok osszegyujtesenek kezdeti ideje
 * @param stop forgalmi adatok osszegyujtesenek befejezesi ideje
 */
function _myntcd_ip2tmptable($ip, $start, $stop = '') {
	// Seged tabla definialasa
	if ($stop == '') {
		$stop = date('Y-m-d');
	}

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	$SQL = "CREATE TEMPORARY TABLE tmp_table ";
	$SQL .= "( `ip` varchar(39) default NULL, `date` DATE, `type` int(3) NOT NULL default '0', ";
	$SQL .= " `in_packet` bigint(20) unsigned NOT NULL default '0', ";
	$SQL .= " `out_packet` bigint(20) unsigned NOT NULL default '0', ";
	$SQL .= " `in_byte` bigint(20) unsigned NOT NULL default '0', ";
	$SQL .= " `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result = db_query($SQL);

	// aktualis nap adatainak betoltese a seged tablaba
	$SQL = "INSERT INTO tmp_table SELECT ip, date(date), type, SUM(in_packet), SUM(out_packet), SUM(in_byte), SUM(out_byte) ";
	$SQL .= "FROM now WHERE ip = :ip AND date(date) = :stop GROUP BY ip, type";
	$result = db_query($SQL, array(':ip' => $ip, ':stop' => $stop));

	// megadott intervallum adatainak betoltese a seged tablaba
	$SQL = "INSERT INTO tmp_table SELECT ip, date, type, SUM(in_packet), SUM(out_packet), SUM(in_byte), SUM(out_byte) ";
	$SQL .= "FROM daily WHERE ip = :ip AND date >= :start AND date <= :stop GROUP BY date, ip, type";
	$result = db_query($SQL, array(':ip' => $ip, ':start' => $start, ':stop' => $stop));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

} // function _myntcd_ip2tmptable()

/**
 * _myntcd_traffic2tmptable: megadott intervallum forgalmat IP cimenkent osszegyujti
 * @param start megadott idoponttol
 * @param stop megadott idopontig
 */
function _myntcd_traffic2tmptable($start, $stop = '') {
	// Seged tabla definialasa
	if ($stop == '') {
		$stop = date('Y-m-d');
	}

	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	$SQL = "CREATE TEMPORARY TABLE tmp_table ";
	$SQL .= "( `ip` varchar(39) default NULL, ";
	$SQL .= "`ipr_id` smallint(5) unsigned NOT NULL, ";
	$SQL .= "`in_byte` bigint(20) unsigned NOT NULL default '0', ";
	$SQL .= " `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result = db_query($SQL);

	// aktualis nap adatainak betoltese a seged tablaba
	$SQL = "INSERT INTO tmp_table SELECT ip, ipr_id, SUM(in_byte), SUM(out_byte) FROM now ";
	$SQL .= "WHERE date(date) = :stop GROUP BY ip";
	$result = db_query($SQL, array(':stop' => $stop));

	// megadott ido intervallum adatainak betoltese a seged tablaba
	$SQL = "INSERT INTO tmp_table SELECT ip, ipr_id, SUM(in_byte), SUM(out_byte) FROM daily ";
	$SQL .= "WHERE date >= :start AND date <= :stop GROUP BY ip";
	$result = db_query($SQL, array(':start' => $start, ':stop' => $stop));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

} // function _myntcd_traffic2tmptable()

/**
 * myntcd_top_daily
 * @param date adott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_top_daily($date = '') {
	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/top/daily');
		return;
	}

	_myntcd_set_title(t('Daily'), $date);

	// Napnak megfelelo adatbazis kivalasztasa
	if ($date == date('Y-m-d')) {
		$from = "FROM now";
	} else {
		$from = "FROM daily";
	}

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		// Top lista: forgalomnak megfelelo
		$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
		$SQL .= $from." WHERE date(date) = :date GROUP BY ip, date(date) ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, 0, 20, array(':date' => $date));

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();


		$tables[$table] = array();
		// Tablazat sorainak elkeszitese
		_myntcd_get_ip_rows($result, $tables[$table], 'daily');
	}

	$build['myntcd_top_daily'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => '',
	  '#when' => 'daily',
	  '#rows' => $tables,
	  '#start' => $date,
	  '#stop' => '',
	  '#path' => 'myntcd/top',
	);
	return $build;
} // function myntcd_top_daily()

/**
 * myntcd_top_weekly
 * @param date adott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_top_weekly($date = '') {
	if ($date == '') {
		$date = date('Y-m-d');
	} elseif (!_myntcd_chk_date($date)) {
		drupal_goto('myntcd/top/weekly');
		return;
	}

	$start_week = date('Y-m-d', strtotime($date.' -1 week +1 day'));

	_myntcd_set_title(t('Weekly'), $start_week, $date);

	// Seged tabla definialasa es feltoltese
	_myntcd_traffic2tmptable($start_week, $date);

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		// Top lista: forgalomnak megfelelo
		$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
		$SQL .= "FROM tmp_table GROUP BY ip ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, 0, 20);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$tables[$table] = array();
		// Tablazat sorainak elkeszitese
		_myntcd_get_ip_rows($result, $tables[$table], 'weekly');
	}

	$build['myntcd_top_weekly'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => '',
	  '#when' => 'weekly',
	  '#rows' => $tables,
	  '#start' => $start_week,
	  '#stop' => $date,
	  '#path' => 'myntcd/top',
	);
	return $build;
} // function myntcd_top_weekly()

/**
 * myntcd_top_monthly
 * @param month adott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_top_monthly($month = '') {
	// Havi toplista
	if ($month == '') {
		$month = date('Y-m');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])$/", $month)) {
		drupal_goto('myntcd/top/monthly');
	}

	$start_month = $month.'-01';
	if ( $month == date('Y-m') ) {
		$end_month = $month.date('-d');
	} else {
		$end_month = date('Y-m-d', strtotime('-1 day', strtotime('+1 month', strtotime($month."-01"))));
	}

	_myntcd_set_title(t('Monthly'), $start_month, $end_month);

	// Seged tabla definialasa es feltoltese
	_myntcd_traffic2tmptable($start_month, $end_month);

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		// Top lista: forgalomnak megfelelo
		$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
		$SQL .= "FROM tmp_table GROUP BY ip ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, 0, 20);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$tables[$table] = array();
		// Tablazat sorainak elkeszitese
		_myntcd_get_ip_rows($result, $tables[$table], 'monthly');
	}

	$build['myntcd_top_monthly'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => '',
	  '#when' => 'monthly',
	  '#rows' => $tables,
	  '#start' => $start_month,
	  '#stop' => $end_month,
	  '#path' => 'myntcd/top',
	);
	return $build;
} // function myntcd_top_monthly()

/**
 * myntcd_top_yearly
 * @param year adott datum
 * @return build tomb, amiben a tablazat megjelenitesehez vannak infok
 */
function myntcd_top_yearly($year = '') {

	// Eves toplista
	if ($year == '') {
		$year = date('Y');
	} elseif (!preg_match("/^([123456789][[:digit:]]{3})$/", $year)) {
		drupal_goto('myntcd/top/yearly');
	}

	if ( $year == date('Y') ) {
		$start_year = date('Y-01-01');
		$stop_year = date('Y-m-d');
	} else {
		$start_year = $year.'-01-01';
		$stop_year = $year.'-12-31';
	}

	_myntcd_set_title(t('Yearly'), $start_year, $stop_year);

	// Seged tabla definialasa es feltoltese
	_myntcd_traffic2tmptable($start_year, $stop_year);

	$traffic = array('out_byte' => 'out', 'in_byte' => 'in', 'total' => 'total' );
	foreach ($traffic as $order_by => $table) {
		// Kapcsolodas az SQL szerverhez
		db_set_active('myntcd');

		// Top lista: forgalomnak megfelelo
		$SQL = "SELECT ip, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte, SUM(in_byte) + SUM(out_byte) AS total ";
		$SQL .= "FROM tmp_table GROUP BY ip ORDER BY ".$order_by." DESC";
		$result = db_query_range($SQL, 0, 20);

		// Vissza valtas az alapertelmezett SQL szerverhez
		db_set_active();

		$tables[$table] = array();
		// Tablazat sorainak elkeszitese
		_myntcd_get_ip_rows($result, $tables[$table], 'yearly');
	}

	$build['myntcd_top_yearly'] = array(
	  '#theme' => 'myntcd_tables',
	  '#ip' => '',
	  '#when' => 'yearly',
	  '#rows' => $tables,
	  '#start' => $start_year,
	  '#stop' => $stop_year,
	  '#path' => 'myntcd/top',
	);
	return $build;
} // function myntcd_top_monthly()

/**
 * A feketelistan levo ip cimek megjelenitese
 * @param form
 * @param form_state
 * @return form az oldal megjelenitesehez szukseges adatotkkal ter vissza
 */
function myntcd_filter_blacklist($form, &$form_state) {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	$SQL = "SELECT * FROM filter WHERE blacklist = 1 ORDER BY date DESC, ip";
	$result = db_query($SQL);

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$form['table']['#tree'] = TRUE;

	while ($row = $result->fetchAssoc()) {
		$form['table'][$row['ip']] = array(
			'chk' => array(
				'#type' => 'checkbox',
			),
			'ip_address' => array(
				'#type' => 'link',
				'#title' => $row['ip'],
				'#href' => 'myntcd/ip/'.$row['ip'],
			),
			'end_date' => array(
				'#markup' => $row['date'] == '0000-00-00' ? t('for ever') : $row['date'],
			),
			'comment' => array(
				'#type' => 'textfield',
				'#default_value' => $row['comment'],
			),
		);
	}

  $form['white'] = array(
		'#type' => 'submit',
		'#value' => t('Add Whitelist'),
	);

	$form['save'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	$form['remove'] = array(
		'#type' => 'submit',
		'#value' => t('Delete'),
	);

	return $form;
}

/**
 * A feketelista megjelenitse
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return egy segedfugvenyt hiv meg
 */
function theme_myntcd_filter_blacklist($variables) {
	return _myntcd_filter_tables($variables);
}

/**
 * A felekete és feher listat kesziti el
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return adott oldallal ter vissza
 */
function _myntcd_filter_tables($variables) {
	$form = $variables['form'];
	$output = '';
	$rows = array();
	foreach (element_children($form['table']) as $ip) {
		$rows[] = array(
		  'data' => array(
		  	drupal_render($form['table'][$ip]['chk']),
		    drupal_render($form['table'][$ip]['ip_address']),
		    drupal_render($form['table'][$ip]['end_date']),
		    drupal_render($form['table'][$ip]['comment']),
		  ),
		);
	}

	$header = array(
		'ip_address' => t('IP Address'),
		'end_date' => t('End date'),
		'comment' => t('Comment'),
	);

	// Add a "Select all" checkbox.
	drupal_add_js('misc/tableselect.js');
	array_unshift($header, array('class' => array('select-all')));

	$output .= theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No content available.')));
	$output .= drupal_render_children($form);

	return $output;
}

/**
 * A feketelistan elvegzett modositasokat dolgozza fel
 * @param form
 * @param form_state
 */
function myntcd_filter_blacklist_submit($form, &$form_state) {
	if ( $form_state['values']['op'] == t('Save') ) {
		foreach ($form_state['values']['table'] as $ip => $items) {
			if ($items['chk']) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				$SQL = "UPDATE filter SET comment = :comment WHERE ip = :ip AND blacklist = 1";
				db_query($SQL, array(':comment' => $items['comment'], ':ip' => $ip));

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			}
		}
	} elseif ( $form_state['values']['op'] == t('Delete') ) {
		foreach ($form_state['values']['table'] as $ip => $items) {
			if ($items['chk']) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				$SQL = "DELETE FROM filter WHERE ip = :ip AND blacklist = 1";
				db_query($SQL, array(':ip' => $ip));

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			}
		}
	} elseif ( $form_state['values']['op'] == t('Add Whitelist') ) {
		foreach ($form_state['values']['table'] as $ip => $items) {
			if ($items['chk']) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				$SQL = "UPDATE filter SET blacklist = 0 WHERE ip = :ip AND blacklist = 1";
				db_query($SQL, array(':ip' => $ip));

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			}
		}
	}
}

/**
 * A feherlistan levo ip cimek megjelenitese
 * @param form
 * @param form_state
 * @return form az oldal megjelenitesehez szukseges adatotkkal ter vissza
 */
function myntcd_filter_whitelist($form, &$form_state) {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	$SQL = "SELECT * FROM filter WHERE blacklist = 0 ORDER BY date DESC, ip";
	$result = db_query($SQL);

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();

	$form['table']['#tree'] = TRUE;
	while ($row = $result->fetchAssoc()) {
		$form['table'][$row['ip']] = array(
			'chk' => array(
				'#type' => 'checkbox',
			),
			'ip_address' => array(
				'#type' => 'link',
				'#title' => $row['ip'],
				'#href' => 'myntcd/ip/'.$row['ip'],
			),
			'end_date' => array(
				'#markup' => $row['date'] == '0000-00-00' ? t('for ever') : $row['date'],
			),
			'comment' => array(
				'#type' => 'textfield',
				'#default_value' => $row['comment'],
			),
		);
	}

	$form['save'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);

	$form['remove'] = array(
		'#type' => 'submit',
		'#value' => t('Delete'),
	);

	return $form;
}

/**
 * A feherlista megjelenitse
 * @param variables a smikeleshez szukseges adatokat tartalmazza
 * @return egy segedfugvenyt hiv meg
 */
function theme_myntcd_filter_whitelist($variables) {
	return _myntcd_filter_tables($variables);
}

/**
 * A feherlistan elvegzett modositasokat dolgozza fel
 * @param form
 * @param form_state
 */
function myntcd_filter_whitelist_submit($form, &$form_state) {
	if ( $form_state['values']['op'] == t('Save') ) {
		foreach ($form_state['values']['table'] as $ip => $items) {
			if ($items['chk']) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				$SQL = "UPDATE filter SET comment = :comment WHERE ip = :ip AND blacklist = 0";
				db_query($SQL, array(':comment' => $items['comment'], ':ip' => $ip));

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			}
		}
	} elseif ( $form_state['values']['op'] == t('Delete') ) {
		foreach ($form_state['values']['table'] as $ip => $items) {
			if ($items['chk']) {
				// Kapcsolodas az SQL szerverhez
				db_set_active('myntcd');

				$SQL = "DELETE FROM filter WHERE ip =:ip AND blacklist = 0";
				db_query($SQL, array(':ip' => $ip));

				// Vissza valtas az alapertelmezett SQL szerverhez
				db_set_active();
			}
		}
	}
}

/**
 * Fel lehet venni a feher es fekete listakra ip cimeket
 * @param form
 * @param form_state
 * @return form az oldal megjelenitesehez szukseges adatotkkal ter vissza
 */
function myntcd_filter_add($form, &$form_state) {
	$form['filter_ip'] = array(
		'#type' => 'textfield',
		'#title' => t('IP Address'),
		'#size' => 20,
		'#maxlength' => 39,
		'#required' => TRUE,
	);

	$form['filter_type'] = array(
		'#type' => 'select',
		'#title' => t('Type'),
		'#options' => array(1 => t('Blacklist'), 0 => t('Whitelist')),
		'#required' => FALSE,
	);

	$form['filter_time'] = array(
		'#type' => 'radios',
		'#title' => t('Time interval'),
		'#default_value' => '1',
		'#options' => array(
		    '1' => t('day'),
		    '7' => t('week'),
		    '30' => t('month'),
		    '-1' => t('for ever')
		),
		'#required' => FALSE,
	);

	$form['filter_time_interval'] = array(
		'#type' => 'textfield',
		'#default_value' => '1',
		'#size' => 20,
		'#required' => TRUE,
	);

	$form['filter_comment'] = array(
		'#type' => 'textfield',
		'#title' => t('Comment'),
		'#size' => 20,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save')
	);

	return $form;
}

/**
 * A filter oldalon megadott adatokat validalja
 * @param form
 * @param form_state
 */
function myntcd_filter_add_validate($form, &$form_state) {
	if (!_myntcd_is_ip($form_state['values']['filter_ip'])) {
		form_set_error('filter_ip', t('Is not IP address.'));
	}
	if (!is_numeric($form_state['values']['filter_time_interval'])) {
		form_set_error('filter_time_interval', t('Time interval is not numeric.'));
	}
}

/**
 * Feldolgozza a valtozasokat
 * @param form
 * @param form_state
 */
function myntcd_filter_add_submit($form, &$form_state) {
	// Kapcsolodas az SQL szerverhez
	db_set_active('myntcd');

	if ($form_state['values']['filter_time'] == '-1') {
		$filtertime = '0000-00-00';
	} else {
		$filtertime = $form_state['values']['filter_time'] * $form_state['values']['filter_time_interval'];
		$filtertime = date('Y-m-d', strtotime('+'.$filtertime.' day'));
	}

	$SQL = "INSERT INTO filter (ip, blacklist, date, comment) VALUES (:ip, :blacklist, :date, :comment)";
	db_query($SQL, array(':ip' => $form_state['values']['filter_ip'], ':blacklist' => $form_state['values']['filter_type'], ':date' => $filtertime, ':comment' => $form_state['values']['filter_comment']));

	// Vissza valtas az alapertelmezett SQL szerverhez
	db_set_active();
}

/**
 * RRD adatbazisbol keszit kepet es kuldi a kimenetre
 * @param ip
 * @param title kep cime
 * @param start grafikon kezdesi ideje
 * @param stop grafikon befejezesi ideje
 */
function _myntcd_get_rrd_image_myntcd($ip, $title, $start, $end) {
	$rrd_dir = variable_get('myntcd_rrd_dir', '/usr/local/myntcd/rrd');
	$rrd_cmd = variable_get('myntcd_rrd_cmd', '/usr/bin/rrdtool');

	// .png kimenet beallitasa
	drupal_add_http_header('Content-Type', 'image/png');
	if (is_file($rrd_dir.'/'.$ip.'.rrd')) {
		$error = $out = '';
		$rrdcmd = "$rrd_cmd graph - --imgformat 'PNG' --width 500";
		$rrdcmd .= " --start '$start' --end '$end'";
		$rrdcmd .= " --vertical-label 'byte / sec' --title '$title'  ";
		$rrdcmd .= " --alt-y-mrtg --lazy -c \"MGRID#ee0000\"";
		$rrdcmd .= " -c \"GRID#000000\" 'DEF:A=$rrd_dir/".str_replace(':', '\:', $ip).".rrd:in:AVERAGE'";
		$rrdcmd .= " 'DEF:B=$rrd_dir/".str_replace(':', '\:', $ip).".rrd:out:AVERAGE' 'CDEF:C=A,B,+'";
		$rrdcmd .= " 'LINE1:A#00FF00:".t('In')."' 'GPRINT:A:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'LINE1:B#0000FF:".t('Out')."' 'GPRINT:B:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'COMMENT:".t('Total')."\:' 'GPRINT:C:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		// Parancs futtatasa es az eredmeny kiiratasa a kimentre
		passthru($rrdcmd);
		die;
	}
} // function _myntcd_get_rrd_image_myntcd()

/**
 * myntcd_img: rrd grafikont jelenit meg egy adott ip-hez
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 * @param start forgalmi adatok kezdeti ideje
 * @param stop forgalmi adatok befejezesi ideje
 */
function myntcd_img($ip, $when, $start = '', $stop = '') {
	// Utolso idopont meghatarozasa
	if ($stop == '') {
		if ($when == 'daily') {
			if ($start != '' && strtotime($start) < strtotime('now')) {
				$stop = strtotime('+1 day', strtotime($start));
			} else {
				$stop = strtotime('now');
			}
		} else {
			$stop = strtotime('now');
		}
	} else {
		if ($when != 'yearly') {
//			$end = strtotime($end.' '.date('H:i:s'));
			$stop = strtotime($stop.' 23:59:59');
		} else {
			$stop = strtotime($stop);
		}
	}
	if ($start != '') {
		$start = strtotime($start);
	}
	// Kep tipusanak megfelelo kezdesi idopont meghatarozasa
	switch ($when) {
		default:
		case 'daily':
			if ($start == '') {
				$start = strtotime('-1 day', $stop);
				$title = $ip.' ('.date('Y-m-d', $stop).')';
			} else {
				$title = $ip.' ('.date('Y-m-d', $start).')';
			}
		break;
		case 'weekly':
			if ($start == '') {
				$start = strtotime('-1 week +1 day', $stop);
			}
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $stop).')';
		break;
		case 'monthly':
			if ($start == '') {
				$start = strtotime('-1 month', $stop);
			}
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $stop).')';
		break;
		case 'yearly':
			if ($start == '') {
				$start = strtotime('-1 year', $stop);
			}
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $stop).')';
		break;
	}
	// Kep elkeszitese
	$img = _myntcd_get_rrd_image_myntcd($ip, $title, $start, $stop);
} // function myntcd_img

/**
 * Vissza adja a csomag tipusanak nevet
 * @param type csomag tipusa
 * @return csomag tipus neve
 */
function _myntcd_get_packet_type($type) {
	switch ($type) {
		case "-1":
			#OTHER
			$type = t('Other');
		break;
		case "1":
			#ICMP
			$type = t('ICMP');
		break;
		case "6":
			#TCP
			$type = t('TCP');
		break;
		case "17":
			#UDP
			$type = t('UDP');
		break;
	}
	return $type;
} // function _myntcd_get_packet_type()

/**
 * Ellenorzi a datum formatumot
 * @param date text
 * @return boolean
 */
function _myntcd_chk_date($date) {
	if (preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])-(0[1-9]|[12][[:digit:]]|3[01])$/", $date)) {
		return TRUE;
	} else {
		return FALSE;
	}
} // function _myntcd_chk_date()

/**
 * Ellenorzi az ip formatumot
 * @param ip text
 * @return boolean
 */
function _myntcd_is_ip($ip) {
	$num = "(25[0-5]|2[0-4]\d|[01]?\d\d|\d)";
	//$num = "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)";

	$ipv4regexp = "/^$num\.$num\.$num\.$num$/";

	$ipv6regexp = "/^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|";
	$ipv6regexp .= "((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|";
	$ipv6regexp .= ":((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|";
	$ipv6regexp .= "(:(((:[0-9A-Fa-f]{1,4}){1,7})|";
	$ipv6regexp .= "((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/";

	if (preg_match($ipv4regexp, $ip)) {
		return 1;
	} elseif (preg_match($ipv6regexp, $ip)) {
		return 1;
	} else {
		return 0;
	}
} // function _myntcd_is_ip()

/**
 * Convert Bytes to human readable format
 * A tablazatokbol kiolvasott byte erteketek konvertalja olvashatobb formara
 * @param bytes az adatbazisbol kiolvasott adat
 * @return convertedbytes olvashatobb format ad vissza
 */
function _myntcd_convert_bytes_to_hrf($bytes) {
	$finish = FALSE;
	$exponent = 1;
	// mertekegysegek: byte, kilobyte, megabyte, gigabyte, terrabyte, petabyte, exabyte, zettabyte, yottabyte, brontobyte, geopbyte
	$units = array('B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');
	while($finish != TRUE) {
		// Ha a lefelekerekitve a byte-okat elosszuk a 1024^kitevo-vel az egyenlo nullaval
		if (floor($bytes / pow(1024, $exponent)) == 0) {
			// Ha a kitevo 1, vagyis a byte-okat 1024-el osztva az ertek egyenlo nulla, akkor byte lesz az erteke
			if ($exponent == 1) {
				$convertedbytes = $bytes.' &nbsp;&nbsp;'.$units[$exponent - 1];
			} else { // Ha a kitevo nagyobb mint 1
				// akkor atalakitjuk a szamot a megfelelo formara es hozzarakjuk a mertekegyseget
				$convertedbytes = number_format(round($bytes / pow(1024, $exponent - 1), 2), 2, '.', ' ').' '.$units[$exponent - 1];
			}
			$finish = TRUE;
		}
		// Ha meg nem nulla az ertek akkor noveljuk a kitevot
		$exponent++;
	}
	return $convertedbytes;
}
