#!/bin/sh
#
# /etc/init.d/myntcd start/stop/restart myntcd
#
#cd /etc/init.d majd update-rc.d -f myntcd defaults

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/myntc/bin/myntcd
PIDFILE=/usr/local/myntc/bin/myntcd.pid
CONFIG=/usr/local/myntc/etc/myntcd.conf
NAME=myntcd
DESC="My Network Traffic Counter"

test -x $DAEMON || exit 0
test -r $CONFIG || exit 0

case "$1" in
  start)
    echo -n "Starting $DESC: $NAME"
    start-stop-daemon --start --quiet --exec $DAEMON
    echo "."
    ;;
  stop)
    echo -n "Stopping $DESC: $NAME"
    start-stop-daemon --stop --quiet  --pidfile $PIDFILE
    echo "."
    ;;
  force-reload|reload)
    echo -n "Restarting $DESC: $NAME reload"
    start-stop-daemon --stop --pidfile $PIDFILE --signal USR1
    echo "."
    ;;
  restart)
    echo -n "Reloading $DESC: $NAME stop"
    start-stop-daemon --stop --quiet  --pidfile $PIDFILE
    echo -n ". start"
    sleep 3
    start-stop-daemon --start --quiet  --exec $DAEMON
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start | stop | restart | force-reload | reload}"
    exit 1
esac

exit 0
