#!/bin/sh

### BEGIN INIT INFO                                                                                                               
# Provides:             myntcd                                                                                                    
# Required-Start:       $local_fs $remote_fs $network $syslog                                                                     
# Required-Stop:        $local_fs $remote_fs $network $syslog                                                                     
# Default-Start:        2 3 4 5                                                                                                   
# Default-Stop:         0 1 6                                                                                                     
# Short-Description:    start/stop myntcd                                                                                         
### END INIT INFO

#
# /etc/init.d/myntcd start/stop/restart
#
# Debian:
# cd /etc/init.d majd update-rc.d -f myntcd defaults

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/myntcd/bin/myntcd
PIDFILE=/usr/local/myntcd/bin/myntcd.pid
CONFIG=/usr/local/etc/myntcd/myntcd.conf
NAME=myntcd
DESC="My Network Traffic Counter"

test -x $DAEMON || exit 0
test -r $CONFIG || exit 0

case "$1" in
  start)
    echo -n "$DESC: $NAME Starting..."
    start-stop-daemon --start --quiet --exec $DAEMON
    echo "\t[OK]"
    ;;
  stop)
    echo -n "$DESC: $NAME Stopping..."
    start-stop-daemon --stop --quiet  --pidfile $PIDFILE
    echo "\t[OK]"
    ;;
  force-reload|reload)
    echo -n "$DESC: $NAME Reloading..."
    start-stop-daemon --stop --pidfile $PIDFILE --signal USR1
    echo "\t[OK]"
    ;;
  restart)
    echo "$DESC: $NAME Restarting..."
    start-stop-daemon --stop --quiet  --pidfile $PIDFILE
    echo "Stop\t[OK]"
    sleep 3
    start-stop-daemon --start --quiet  --exec $DAEMON
    echo "Start\t[OK]"
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start | stop | restart | force-reload | reload}"
    exit 1
esac

exit 0
