<?php
/*
 * Created on 2006.02.18.
 */
 
include_once 'DB.php';

/** Szerver adatok betoltese */
if ( (arg(0) == 'myntcd') || (arg(0) == 'my_traffic') ) {
	global $myntcd_server;
	$myntcd_server = array(
		'phptype'  => variable_get('myntcd_server_type', 'mysql'),
		'hostspec' => variable_get('myntcd_server', 'localhost'),
		'port'     => variable_get('myntcd_port', '3306'),
		'database' => variable_get('myntcd_db', 'traffic'),
		'username' => variable_get('myntcd_user', 'user'),
		'password' => variable_get('myntcd_pwd', 'password'),
	);
} 
 
/**
 * Display help and module information
 * @param section which section of the site we're displaying help
 * @return help text for section
 */
function myntcd_help($section='') {
	$output = '';

	switch ($section) {
	case "admin/modules#description":
		$output = t("My Network Traffic Counter Daemon");
		break;
	}
	return $output;
} // function myntcd_help()

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the myntcd module
 */
function myntcd_perm() {
	return array('my traffic', 'traffic manager', 'traffic administer');
} // function myntcd_perm()

/**
 * myntcd_menu: menus
 */
function myntcd_menu($may_cache) {
	$items = array();

	if ($may_cache) {
		/** Sajat IP adatainak lekerdezese */
		$items[] = array('path' => 'my_traffic',
			'title' => t('My Traffic'),
			'callback' => 'myntcd_my_traffic',
			'access' => user_access('my traffic'),
			'weight' => 1);
		$items[] = array('path' => 'my_traffic/daily',
			'title' => t('Daily'),
			'callback' => 'myntcd_my_traffic',
			'callback arguments' => array('daily'),
			'access' => user_access('my traffic'),
			'weight' => 2);
		$items[] = array('path' => 'my_traffic/weekly',
			'title' => t('Weekly'),
			'callback' => 'myntcd_my_traffic',
			'callback arguments' => array('weekly'),
			'access' => user_access('my traffic'),
			'weight' => 4);
		$items[] = array('path' => 'my_traffic/monthly',
			'title' => t('Monthly'),
			'callback' => 'myntcd_my_traffic',
			'callback arguments' => array('monthly'),
			'access' => user_access('my traffic'),
			'weight' => 6);
		$items[] = array('path' => 'my_traffic/yearly',
			'title' => t('Yearly'),
			'callback' => 'myntcd_my_traffic',
			'callback arguments' => array('yearly'),
			'access' => user_access('my traffic'),
			'weight' => 8);

		/** Sajat IP-hez sajat kep */
		$items[] = array('path' => 'myntcd/myimg',
			'title' => t('MyImg'),
			'callback' => 'myntcd_myimg',
			'access' => user_access('my traffic'),
			'type' => 'MENU_CALLBACK',
			'weight' => 1);

		/** IP-k adminisztralasa */
		$items[] = array('path' => 'myntcd',
			'title' => t('Myntcd'),
			'callback' => 'myntcd_myntcd',
			'access' => user_access('traffic manager'),
			'weight' => 1);

		/** IP-hez kapcsolodo kep megjelenitese */
		$items[] = array('path' => 'myntcd/img',
			'title' => t('Img'),
			'callback' => 'myntcd_img',
			'access' => user_access('traffic manager'),
			'type' => 'MENU_CALLBACK',
			'weight' => 1);

		/** IP tartomanyok */ 
		$items[] = array('path' => 'myntcd/iprange',
			'title' => t('IP Ranges'),
			'callback' => 'myntcd_iprange',
			'callback arguments' => array(0),
			'access' => user_access('traffic manager'),
			'weight' => 3);
		/** IP tartomanyok osszevonva */
		$items[] = array('path' => 'myntcd/iprange/all',
			'title' => t('All'),
			'callback' => 'myntcd_iprange',
			'callback arguments' => array(1),
			'access' => user_access('traffic manager'),
			'weight' => 2);
		$items[] = array('path' => 'myntcd/iprange/all/daily',
			'title' => t('Daily'),
			'access' => user_access('traffic manager'),
			'weight' => 2);
		$items[] = array('path' => 'myntcd/iprange/all/weekly',
			'title' => t('Weekly'),
			'access' => user_access('traffic manager'),
			'weight' => 4);
		$items[] = array('path' => 'myntcd/iprange/all/monthly',
			'title' => t('Monthly'),
			'access' => user_access('traffic manager'),
			'weight' => 6);
		$items[] = array('path' => 'myntcd/iprange/all/yearly',
			'title' => t('Yearly'),
			'access' => user_access('traffic manager'),
			'weight' => 8);

		/** Top lista */
		$items[] = array('path' => 'myntcd/top',
			'title' => t('Top Lists'),
			'callback' => 'myntcd_top',
			'access' => user_access('traffic manager'),
			'weight' => 5);
		$items[] = array('path' => 'myntcd/top/daily',
			'title' => t('Daily'),
			'callback' => 'myntcd_top',
			'callback arguments' => array('daily'),
			'access' => user_access('traffic manager'),
			'weight' => 2);
		$items[] = array('path' => 'myntcd/top/weekly',
			'title' => t('Weekly'),
			'callback' => 'myntcd_top',
			'callback arguments' => array('weekly'),
			'access' => user_access('traffic manager'),
			'weight' => 4);
		$items[] = array('path' => 'myntcd/top/monthly',
			'title' => t('Monthly'),
			'callback' => 'myntcd_top',
			'callback arguments' => array('monthly'),
			'access' => user_access('traffic manager'),
			'weight' => 6);
		$items[] = array('path' => 'myntcd/top/yearly',
			'title' => t('Yearly'),
			'callback' => 'myntcd_top',
			'callback arguments' => array('yearly'),
			'access' => user_access('traffic manager'),
			'weight' => 8);

		/** IP cim szuresek kezelese */
		$items[] = array('path' => 'myntcd/filter',
			'title' => t('Filter'),
			'callback' => 'myntcd_filter',
			'access' => user_access('traffic administer'),
			'weight' => 7);
	} else {
		/** Az almenuk akkor generalodnak ha a myntcd menu kivalasztasra kerult */
		if (arg(0) == 'myntcd') {
			/** ha az elso parameter IP */
			if ( _myntcd_is_ip(arg(1)) ) {
				$items[] = array('path' => 'myntcd/'.arg(1),
					'title' => arg(1),
					'callback' => 'myntcd_myntcd',
					'callback arguments' => array(arg(1)),
					'access' => user_access('traffic manager'),
					'weight' => 1);
				$items[] = array('path' => 'myntcd/'.arg(1).'/daily',
					'title' => t('Daily'),
					'access' => user_access('traffic manager'),
					'weight' => 2);
				$items[] = array('path' => 'myntcd/'.arg(1).'/weekly',
					'title' => t('Weekly'),
					'access' => user_access('traffic manager'),
					'weight' => 4);
				$items[] = array('path' => 'myntcd/'.arg(1).'/monthly',
					'title' => t('Monthly'),
					'access' => user_access('traffic manager'),
					'weight' => 6);
				$items[] = array('path' => 'myntcd/'.arg(1).'/yearly',
					'title' => t('Yearly'),
					'access' => user_access('traffic manager'),
					'weight' => 8);
			/** ha az elso parameter iprange */
			} elseif (arg(1) == 'iprange') {
				/** ha az elso parameter iprange */
				if ( (arg(2) == '') || (_myntcd_is_ip(arg(2))) || (arg(2) == 'all') ) {
					global $myntcd_server;
				
					$db =& DB::connect($myntcd_server);
					if (DB::isError($db)) {
						drupal_set_message( t($db->getMessage()), 'error' );
						return " ";
					}
					$db->setFetchMode(DB_FETCHMODE_ASSOC);

					/** IP tartomanyok listazasa */
					$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS ip_range";
					$SQL .= " FROM daily GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
					$result =& $db->query($SQL);

					/** IP tartomanyok menuk */
					while ($row =& $result->fetchRow()) {
						$items[] = array('path' => 'myntcd/iprange/'.$row['ip_range'].'.0',
							'title' => $row['ip_range'].'.0',
							'callback' => 'myntcd_iprange',
							'callback arguments' => array($row['ip_range']),
							'access' => user_access('traffic manager'),
							'weight' => 4);
						$items[] = array('path' => 'myntcd/iprange/'.$row['ip_range'].'.0/daily',
							'title' => t('Daily'),
							'access' => user_access('traffic manager'),
							'weight' => 2);
						$items[] = array('path' => 'myntcd/iprange/'.$row['ip_range'].'.0/weekly',
							'title' => t('Weekly'),
							'access' => user_access('traffic manager'),
							'weight' => 4);
						$items[] = array('path' => 'myntcd/iprange/'.$row['ip_range'].'.0/monthly',
							'title' => t('Monthly'),
							'access' => user_access('traffic manager'),
							'weight' => 6);
						$items[] = array('path' => 'myntcd/iprange/'.$row['ip_range'].'.0/yearly',
							'title' => t('Yearly'),
							'access' => user_access('traffic manager'),
							'weight' => 8);
					}
				}
			}
		} 
	}
	return $items;
} // function myntcd_menu()

/**
 * Settings for the myntcd module
 * @return form contents for this module
 */
function myntcd_settings() {
	// only administrators can access this function
	if (!user_access('traffic administer')) {
		drupal_access_denied();
		return;
	}

	/** Myntcd SQL szerver bealitasa */
	$form['myntcd_sql_server'] = array(
		'#type' => 'fieldset',
		'#title' => t('Sql Server Settings'),
		'#collapsible' => TRUE,
		'#collapsed' => false,
	);

	$sql_server_type['mysql'] = 'MySql';
	$sql_server_type['mysqli'] = 'MySqli';
	$sql_server_type['pgsql'] = 'PostgreSQL';
	$form['myntcd_sql_server']['myntcd_type'] = array(
		'#type' => 'radios',
		'#title' => t('Type'),
		'#default_value' => variable_get('myntcd_server_type', mysql),
		'#options' => $sql_server_type,
		'#description' => '',);

	$form['myntcd_sql_server']['myntcd_server'] = array(
		'#type' => 'textfield',
		'#title' => t('Host'),
		'#default_value' => variable_get('myntcd_server', localhost),
		'#description' => '',
		'#maxlength' => '200', '#size' => '30');

	$form['myntcd_sql_server']['myntcd_port'] = array(
		'#type' => 'textfield',
		'#title' => t('Port'),
		'#default_value' => variable_get('myntcd_port', 3306),
		'#description' => '',
		'#maxlength' => '5', '#size' => '5');

	$form['myntcd_sql_server']['myntcd_db'] = array(
		'#type' => 'textfield',
		'#title' => t('Database name'),
		'#default_value' => variable_get('myntcd_db', traffic),
		'#description' => '',
		'#size' => '10');

	$form['myntcd_sql_server']['myntcd_user'] = array(
		'#type' => 'textfield',
		'#title' => t('Username'),
		'#default_value' => variable_get('myntcd_user', user),
		'#description' => '',
		'#size' => '10');

	$form['myntcd_sql_server']['myntcd_pwd'] = array(
		'#type' => 'textfield',
		'#title' => t('Password'),
		'#default_value' => variable_get('myntcd_pwd', password),
		'#description' => '',
		'#size' => '10');

	/** RRD adatbazis hasznalatahoz szukseges beallitasok */
	$form['myntcd_rrd'] = array(
		'#type' => 'fieldset',
		'#title' => t('RRD Tool settings'),
		'#collapsible' => TRUE,
		'#collapsed' => false,
	);

	$form['myntcd_rrd']['myntcd_rrd_cmd'] = array(
		'#type' => 'textfield',
		'#title' => t('RRD command'),
		'#default_value' => variable_get('myntcd_rrd_cmd', '/usr/bin/rrdtool'),
		'#description' => '',
		'#maxlength' => '200', '#size' => '30');

	$form['myntcd_rrd']['myntcd_rrd_dir'] = array(
		'#type' => 'textfield',
		'#title' => t('RRD file dir'),
		'#default_value' => variable_get('myntcd_rrd_dir', '/usr/share/myntcd/rrd'),
		'#description' => '',
		'#maxlength' => '200', '#size' => '30');

	return $form;
} // function myntcd_settins()

/**
 * Ellenorzi a datum formatumot
 * @param date text
 * @return boolean
 */
function _myntcd_chk_date($date) {
	if (preg_match("/^([123456789][[:digit:]]{3})-(0[1-9]|1[012])-(0[1-9]|[12][[:digit:]]|3[01])$/", $date)) {
		return true;
	} else {
		return false;
	}
} // function _myntcd_chk_date()

/**
 * Ellenorzi az ip formatumot
 * @param ip text
 * @return boolean
 */
function _myntcd_is_ip($ip) {
	$num = "(25[0-5]|2[0-4]\d|[01]?\d\d|\d)";
	return preg_match("/^$num\\.$num\\.$num\\.$num$/", $ip);
} // function _myntcd_is_ip()

/**
 * Vissza adja a csomag tipusanak nevet
 * @param type csomag tipusa
 * @return csomag tipus neve
 */
function _myntcd_get_packet_type($type) {
	switch ($type) {
		case "-1":
			#OTHER
			$type = t('Other');
		break;
		case "1":
			#ICMP
			$type = t('ICMP');
		break;
		case "6":
			#TCP
			$type = t('TCP');
		break;
		case "17":
			#UDP
			$type = t('UDP');
		break;
	}
	return $type;
} // function _myntcd_get_packet_type()


/**
 * RRD adatbazisbol keszit kepet es kuldi a kimenetre
 * @param ip
 * @param title kep cime
 * @param start grafikon kezdesi ideje
 * @param stop grafikon befejezesi ideje
 */
function _myntcd_get_rrd_image_myntcd($ip, $title, $start, $end) {
	$rrd_dir = variable_get('myntcd_rrd_dir', '/usr/share/myntcd/rrd');
	$rrd_cmd = variable_get('myntcd_rrd_cmd', '/usr/bin/rrdtool');

	/** .png kimenet beallitasa */
	drupal_set_header('Content-Type: image/png');
	if (is_file($rrd_dir.'/'.$ip.'.rrd')) {
		$error = $out = '';
		$rrdcmd = "$rrd_cmd graph - --imgformat 'PNG'";
		$rrdcmd .= " --start '$start' --end '$end'";
		$rrdcmd .= " --vertical-label 'byte / sec' --title '$title'  ";
		$rrdcmd .= " --alt-y-mrtg --lazy -c \"MGRID#ee0000\"";
		$rrdcmd .= " -c \"GRID#000000\" 'DEF:A=$rrd_dir/$ip.rrd:in:AVERAGE'";
		$rrdcmd .= " 'DEF:B=$rrd_dir/$ip.rrd:out:AVERAGE' 'CDEF:C=A,B,+'";
		$rrdcmd .= " 'LINE1:A#00FF00:".t('In')."' 'GPRINT:A:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:A:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'LINE1:B#0000FF:".t('Out')."' 'GPRINT:B:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:B:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		$rrdcmd .= " 'COMMENT:".t('Total')."\:' 'GPRINT:C:MIN:(min=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:AVERAGE:ave=%.0lf %s'";
		$rrdcmd .= " 'GPRINT:C:MAX:max=%.0lf %s)' 'COMMENT:\\n'";
		/** Parancs futtatasa es az eredmeny kiiratasa a kimentre */
		passthru($rrdcmd);
		return;
	}
} // function _myntcd_get_rrd_image_myntcd()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye 
 * @param rows tablazat sorai
 * @param total osszesitet adatok
 * @param date_format kiirt datum formatuma
 * @param link(0/1) kiirt datum linkelve legyen-e 
 */
function _myntcd_get_my_rows($result, &$rows, &$total, $date_format, $link = 0) {
	while ($row =& $result->fetchRow()) {
		/** Atalakitja a datumot a kert formatumra */
		if ($link) {
			$row['date'] = l(format_date(strtotime($row['date']), 'custom', $date_format), 'my_traffic/monthly/'.date('Y-m-01', strtotime($row['date'])));
		} else {
			$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
		}

		/** kiszamolja az osszes forgalmat es azt hogy a teljes forgalom hany %-a a kimeno forgalom */
		$row['total_byte'] = $row['in_byte']+$row['out_byte'];
		if ($row['total_byte']) {
			$row['rate'] = (round($row['out_byte']/$row['total_byte'],2)*100).' %';
		} else {
			$row['rate'] = '0 %';
		}

		/** a teljes forgalom novelese */
		$total['in'] += $row['in_byte'];
		$total['out'] += $row['out_byte'];
		
		/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
		if ($row['in_byte'] <= $row['out_byte']) {
			$warrning = '_warrning';
		} else {
			$warrning = '';
		}
		/** tablazat soranak elkeszitese */
		$rows[] = array(
			array('data' => $row['date'], 'class' => 'myntcd_date'),
			array('data' => number_format(round($row['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_in_byte'),
			array('data' => number_format(round($row['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_out_byte'.$warrning),
			array('data' => number_format(round($row['total_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_byte'.$warrning),
			array('data' => $row['rate'], 'class' => 'myntcd_rate'.$warrning),
		);
	}
} // function _myntcd_get_my_rows()

/**
 * Teljes forgalom adatanak hozzafuzese a tablazat elejehez
 * @param rows tablazat sorai
 * @param total osszesitet adatok
 */
function _myntcd_get_my_totlal_line(&$rows, $total) {
	/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
	if ($total['in'] <= $total['out']) {
		$warrning = '_warrning';
	} else {
		$warrning = '';
	}

	/** Osszes napi forgalom hozza fuzese a tablazathoz */
	if ($total['in']+$total['out']) {
		if ($total['out']) {
			$total['rate'] = (round($total['out']/($total['in']+$total['out']),2)*100).' %';
		} else {
			$total['rate'] = '0 %';
		}

		$row = array(
			array('data' => t('Total traffic:'), 'class' => 'myntcd_total'),
			array('data' => number_format(round($total['in']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_in_byte'),
			array('data' => number_format(round($total['out']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_out_byte'.$warrning),
			array('data' => number_format(round(($total['in']+$total['out'])/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_total_byte'.$warrning),
			array('data' => $total['rate'], 'class' => 'myntcd_total_rate'.$warrning),
		);
		/** Osszes napi forgalom hozza adasa a tablazat elejehez */
		array_unshift($rows, $row);
	}
} // function _myntcd_get_my_totlal_line()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye 
 * @param rows tablazat sorai
 * @param when (daily/weekly/monthly/yearly)
 * @param date_format kiirt datum formatuma
 * @param as lekerdezes neve 
 */
 function _myntcd_get_ip_rows($result, &$rows, $when, $as = 'ip') {
	while ($row =& $result->fetchRow()) {
		/** link elkeszitese, valamint tartomany helyes kiiratasa */
		if ($as != 'ip_range') {
			$row[$as] = l($row[$as], 'myntcd/'.$row[$as].'/'.$when);
		} else {
			$row[$as] = l($row[$as].'.0', 'myntcd/iprange/'.$row[$as].'.0/'.$when);
		}

		/** kiszamolja az osszes forgalmat es azt hogy a teljes forgalom hany %-a a kimeno forgalom */
		if ($row['total']) {
			$row['rate'] = (round($row['out_byte']/$row['total'],2)*100).' %';
		} else {
			$row['rate'] = '0 %';
		}

		/** a teljes forgalom novelese */
		$total['in'] += $row['in_byte'];
		$total['out'] += $row['out_byte'];
		
		/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
		if ($row['in_byte'] <= $row['out_byte']) {
			$warrning = '_warrning';
		} else {
			$warrning = '';
		}
		/** tablazat soranak elkeszitese */
		$rows[] = array(
			array('data' => $row[$as], 'class' => 'myntcd_'.$as),
			array('data' => number_format(round($row['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_in_byte'),
			array('data' => number_format(round($row['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_out_byte'.$warrning),
			array('data' => number_format(round($row['total']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_byte'.$warrning),
			array('data' => $row['rate'], 'class' => 'myntcd_rate'.$warrning),
		);
	}
} // function _myntcd_get_ip_rows()

/**
 * Feldolgozza a mysql lekerdezes sorait
 * @param result lekerdezes eredmenye 
 * @param rows tablazat sorainak elokeszitese
 * @param total osszesitet adatok
 * @param date_format kiirt datum formatuma
 * @param ip ip cim 
 * @param when (daily/weekly/monthly/yearly)
 */
function _myntcd_get_ip_all_rows($result, &$rows, &$total, $date_format, $ip = '', $when = '') {
	while ($row =& $result->fetchRow()) {
		/** Linkelhetove alakitja a datumot */
		switch ($when) {
			case 'weekly':
			case 'monthly':
				$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
				$row['date'] = l($row['date'], 'myntcd/'.$ip.'/daily/'.$row['date']);
			break;
			case 'yearly':
				$row['date'] = l(format_date(strtotime($row['date']), 'custom', $date_format), 'myntcd/'.$ip.'/monthly/'.date('Y-m-01', strtotime($row['date'])));
			break;
		
			default:
				$row['date'] = format_date(strtotime($row['date']), 'custom', $date_format);
			break;
		}

		/** A teljes forgalom novelese */
		$total[0]['in_packet'] += $row['in_packet'];
		$total[0]['out_packet'] += $row['out_packet'];
		$total[0]['in_byte'] += $row['in_byte'];
		$total[0]['out_byte'] += $row['out_byte'];
		$total[$row['type']]['in_packet'] += $row['in_packet'];
		$total[$row['type']]['out_packet'] += $row['out_packet'];
		$total[$row['type']]['in_byte'] += $row['in_byte'];
		$total[$row['type']]['out_byte'] += $row['out_byte'];
		
		/** tablazat soranak elokeszitese */
		$rows[$row['date']][$row['type']] = array(
			type => $row['type'], in_packet => $row['in_packet'],
			out_packet => $row['out_packet'], total_packet => $row['in_packet']+$row['out_packet'],
			in_byte => $row['in_byte'], out_byte => $row['out_byte'], total_byte => $row['in_byte']+$row['out_byte'],
		);
	}
} // function _myntcd_get_ip_all_rows()

/**
 * Forgalmi adatok tablazatta alakitasa
 * @param rows tablazat sorai
 * @param total osszesitet adatok
 */
function _myntcd_get_ip_line(&$rows, $total) {
	/** Osszesitet adatok hozzafuzese a tablazathoz, osszesitve es tipusonkent */
	foreach (array(0, 6, 17, 1, -1) as $element) {
		if (array_key_exists($element, $total)) {
			/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
			if ($total[$element]['in_byte'] <= $total[$element]['out_byte']) {
				$warrning = '_warrning';
			} else {
				$warrning = '';
			}
		
			/** kiszamolja hogy a teljes forgalom hany %-a a kimeno forgalom */
			if ($total[$element]['out_byte']) {
				$total[$element]['rate'] = (round($total[$element]['out_byte']/($total[$element]['in_byte']+$total[$element]['out_byte']),2)*100).' %';
			} else {
				$total[$element]['rate'] = '0 %';
			}

			/** Sorok feliratozasa */
			if ($element == 0) {
				$date = t('Total traffic:');
				$type = '';
			} else {
				$date = '';
				$type = _myntcd_get_packet_type($element);
			}

			/** Tablazat sorai */
			$tl[] = array(
				array('data' => $date, 'class' => 'myntcd_total_total'),
				array('data' => $type, 'class' => 'myntcd_total_type'),
				array('data' => number_format($total[$element]['in_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_in_packet'),
				array('data' => number_format($total[$element]['out_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_out_packet'.$warrning),
				array('data' => number_format(($total[$element]['in_packet']+$total[$element]['out_packet']), 0, '', ' ').' db', 'class' => 'myntcd_total_total_packet'.$warrning),
				array('data' => number_format(round($total[$element]['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_in_byte'),
				array('data' => number_format(round($total[$element]['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_out_byte'.$warrning),
				array('data' => number_format(round(($total[$element]['in_byte']+$total[$element]['out_byte'])/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_total_byte'.$warrning),
				array('data' => $total[$element]['rate'], 'class' => 'myntcd_total_rate'.$warrning),
			);
		}
	}

	/** Vegig megy a tomb sorain */
	while (!is_null($key = key($rows) ) ) {
		$rows[$key][0]['date'] = $key;
		/** Osszesiti az adott datumhoz tartozo forgalmi adatokat */
		foreach (array(6, 17, 1, -1) as $element) {
			$rows[$key][0]['in_packet'] += $rows[$key][$element]['in_packet'];
			$rows[$key][0]['out_packet'] += $rows[$key][$element]['out_packet'];
			$rows[$key][0]['total_packet'] += $rows[$key][$element]['total_packet'];
			$rows[$key][0]['in_byte'] += $rows[$key][$element]['in_byte'];
			$rows[$key][0]['out_byte'] += $rows[$key][$element]['out_byte'];
			$rows[$key][0]['total_byte'] += $rows[$key][$element]['total_byte'];
		}

		/** Hozza fuzi a tablazat soraihoz a datumhoz tartozo adatokat */
		foreach (array(0, 6, 17, 1, -1) as $element) {
			/** A letezo forgalom tipus kerul feldolgozasra */
			if (array_key_exists($element, $rows[$key])) {
				/** ha a kimeno forgalom tul nagy akkor azt mas stilussal jeloljuk */
				if ($rows[$key][$element]['in_byte'] <= $rows[$key][$element]['out_byte']) {
					$warrning_byte = '_warrning';
				} else {
					$warrning_byte = '';
				}

				/** ha a kimeno csomag szam tul nagy akkor azt mas stilussal jeloljuk */
				if ($rows[$key][$element]['in_packet'] <= $rows[$key][$element]['out_packet']) {
					$warrning_packet = '_warrning';
				} else {
					$warrning_packet = '';
				}

				if ($rows[$key][$element]['total_byte']) {
					$rows[$key][$element]['rate'] = (round($rows[$key][$element]['out_byte']/$rows[$key][$element]['total_byte'],2)*100).' %';
				} else {
					$rows[$key][$element]['rate'] = '0 %';
				}
				
				$tl[] = array(
					array('data' => $rows[$key][$element]['date'], 'class' => 'myntcd_date'),
					array('data' => _myntcd_get_packet_type($rows[$key][$element]['type']), 'class' => 'myntcd_type'),
					array('data' => number_format($rows[$key][$element]['in_packet'], 0, '', ' ').' db', 'class' => 'myntcd_in_packet'),
					array('data' => number_format($rows[$key][$element]['out_packet'], 0, '', ' ').' db', 'class' => 'myntcd_out_packet'.$warrning_packet),
					array('data' => number_format($rows[$key][$element]['total_packet'], 0, '', ' ').' db', 'class' => 'myntcd_total_packet'.$warrning_packet),
					array('data' => number_format(round($rows[$key][$element]['in_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_in_byte'),
					array('data' => number_format(round($rows[$key][$element]['out_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_out_byte'.$warrning_byte),
					array('data' => number_format(round($rows[$key][$element]['total_byte']/1024/1024,2), 2, '.', ' ').' MB', 'class' => 'myntcd_total_byte'.$warrning_byte),
					array('data' => $rows[$key][$element]['rate'], 'class' => 'myntcd_rate'.$warrning_byte),
				);
			}
		}
		next($rows);
	}
	$rows = $tl;
} // function _myntcd_get_ip_line()

/**
 * _myntcd_ip2tmptable: Forgalmi adatok tablazatta alakitasa
 * @param db adatbazis kapcsoalt
 * @param ip ip cim
 * @param start forgalmi adatok osszegyujtesenek kezdeti ideje
 * @param stop forgalmi adatok osszegyujtesenek befejezesi ideje
 */
 function _myntcd_ip2tmptable(&$db, $ip, $start, $stop = '') {
	/** Seged tabla definialasa */
	if ($stop == '') {
		$stop = date('Y-m-d');
	}
	$SQL = "CREATE TEMPORARY TABLE tmp_table";
	$SQL .= " ( `ip` varchar(15) default NULL, `date` DATE, `type` int(3) NOT NULL default '0',";
	$SQL .= "  `in_packet` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `out_packet` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `in_byte` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result =& $db->query($SQL);
	if (DB::isError($result)) {
		drupal_set_message( t($result->getMessage()), 'error' );
		return " ";
	}

	/** aktualis nap adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO tmp_table SELECT ip, date(date), type, SUM(in_packet), SUM(out_packet), SUM(in_byte), SUM(out_byte)";
	$SQL .= " FROM now WHERE ip = ? AND date(date) = ? GROUP BY ip, type";
	$result =&$db->query($SQL, array($ip, $stop));
	if (DB::isError($result)) {
		die($result->getMessage());
	}

	/** megadott intervallum adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO tmp_table SELECT ip, date, type, SUM(in_packet), SUM(out_packet), SUM(in_byte), SUM(out_byte) FROM daily";
	$SQL .= " WHERE ip = ? AND date >= ? AND date <= ? GROUP BY date, ip, type";
	$result =&$db->query($SQL, array($ip, $start, $stop));
	if (DB::isError($result)) {
		die($result->getMessage());
	}
} // function _myntcd_ip2tmptable()

/**
 * myntcd_myntcd: Forgalmi adatok
 * @param ip ip cim
 * @param when (daily/weekly/monthly/yearly)
 * @param date mikor
 */
function myntcd_myntcd($ip = '', $when = '', $date = '') {
	global $myntcd_server;
	theme_add_style($path = 'modules/myntcd/style.css', $media = 'all');

	/** Kapcsolodas az SQL szerverhez */
	$db =& DB::connect($myntcd_server);
	if (DB::isError($db)) {
		drupal_set_message( t($db->getMessage()), 'error' );
		return " ";
	}
	$db->setFetchMode(DB_FETCHMODE_ASSOC);

	$output = '';

	/** ha IP az IP */
	if (_myntcd_is_ip($ip)) {
		switch ($when) {
			case '':
				$output .= theme('myntcd_ip', $ip);
			break;
			case 'daily':
			/** Napi forgalom */
				if ($date == '') {
					$date = date('Y-m-d');
				}
				if (!_myntcd_chk_date($date)) {
					drupal_goto('myntcd/'.$ip.'/daily');
				}
				/** utolso nap masik tablaba van */
				if ($date == date('Y-m-d')) {
					$from = " FROM now";
				} else {
					$from = " FROM daily";
				}
				/** A mai nap forgalmi adatai orankenti bontasban */
				$sql = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet,';
				$sql .= ' SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte';
				$sql .= $from." WHERE ip='".$ip."' AND date(date) = '".$date."' GROUP BY hour(date), type ORDER BY date DESC";
				$result =& $db->query($sql);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				
				$rows = $total = array();
				$total['in'] = $total['out'] = 0;
				/** Tablazat sorainak elokeszitese */
				_myntcd_get_ip_all_rows($result, &$rows, &$total, 'H:00', $ip, $when);

				/** Ha nem aktualis nap van egyszerubb tablazat kell */
				if ($date != date('Y-m-d')) {
					$rows = array();
				}
				/** Napi forgalom hozza fuzese a tablazathoz */
				_myntcd_get_ip_line($rows, $total);
				$output .= theme('myntcd_daily', $ip, $rows, $date);
			break;
	
			case 'weekly':
			/** Heti forgalom */
				if ($date != '') {
					drupal_goto('myntcd/'.$ip.'/weekly');
				}
				$date = date('Y-m-d');
				$start_week = date('Y-m-d', strtotime('-1 week'));
				
				/** forgalmi adatok betoltese az atmenti tablaba */
				_myntcd_ip2tmptable($db, $ip, $start_week, $date);
	
				$sql = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet,';
				$sql .= ' SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table';
				$sql .= " GROUP BY date, ip, type ORDER BY date DESC";
				$result =& $db->query($sql);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				
				$rows = $total = array();
				/** Tablazat sorainak elokeszitese */
				_myntcd_get_ip_all_rows($result, &$rows, &$total, 'Y-m-d', $ip, $when);
				/** Heti forgalom hozza fuzese a tablazathoz */
				_myntcd_get_ip_line($rows, $total);
				$output .= theme('myntcd_weekly', $ip, $rows, $start_week, $date);
			break;
	
			case 'monthly':
			/** Havi forgalom */
				if ($date == '') {
					$date = date('Y-m-01');
				}
				if (!_myntcd_chk_date($date)) {
					drupal_goto('myntcd/'.$ip.'/monthly');
				} else {
					$date = date('Y-m-01', strtotime($date));
				}
	
				if (strtotime('now') < strtotime($date.' +1 month')) {
					$end_month = date('Y-m-d');
				} else {
					$end_month = date('Y-m-d', strtotime($date.' +1 month -1 day'));
				}
				/** forgalmi adatok betoltese az atmenti tablaba */
				_myntcd_ip2tmptable($db, $ip, $date, $end_month);
	
				$sql = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet,';
				$sql .= ' SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table';
				$sql .= " GROUP BY date, ip, type ORDER BY date DESC";
				$result =& $db->query($sql);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				
				$rows = $total = array();
				/** Tablazat sorainak elokeszitese */
				_myntcd_get_ip_all_rows($result, &$rows, &$total, 'Y-m-d', $ip, $when);
				/** havi forgalom hozza fuzese a tablazathoz */
				_myntcd_get_ip_line($rows, $total);
				$output .= theme('myntcd_monthly', $ip, $rows, $date, $end_month);
			break;
	
			case 'yearly':
			/** Eves forgalom */
				if ($date != '') {
					drupal_goto('myntcd/'.$ip.'/yearly');
				}
				$date = date('Y-m-d');
				$start_year = date('Y-01-01');

				/** forgalmi adatok betoltese az atmenti tablaba */
				_myntcd_ip2tmptable($db, $ip, $start_year, $date);
	
				$sql = 'SELECT date, type, SUM(in_packet) AS in_packet, SUM(out_packet) AS out_packet,';
				$sql .= ' SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM tmp_table';
				$sql .= " GROUP BY month(date), ip, type ORDER BY date DESC";
				$result =& $db->query($sql);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				
				$rows = $total = array();
				/** Tablazat sorainak elokeszitese */
				_myntcd_get_ip_all_rows($result, &$rows, &$total, 'Y. F', $ip, $when);
				/** Eves forgalom hozza fuzese a tablazathoz */
				_myntcd_get_ip_line($rows, $total);
				$output .= theme('myntcd_yearly', $ip, $rows, date('Y'));
			break;
		
			default:
				drupal_goto('myntcd');
			break;
		}
	} elseif($ip == '') {
		/** ip kereses */
		$form = array();
		$form['myntcd_ip'] = array(
			'#type' => 'textfield',
			'#title' => t('Ip address'),
			'#size' => 20,
			'#maxlength' => 15,
			'#required' => false,
		);
		$form['submit'] = array('#type' => 'submit', '#value' => t('Search'));
		$output .= drupal_get_form('myntcd_myntcd', $form); 
	}
	return $output;
} // function myntcd_myntcd()

/**
 * myntcd_myntcd_submit
 */
function myntcd_myntcd_submit($form_id, $form) {
	if (_myntcd_is_ip($form['myntcd_ip'])) {
		drupal_goto('myntcd/'.$form['myntcd_ip']);
	}
} // myntcd_myntcd_submit()

/**
 * theme_myntcd_when: egyseges theme
 */
function theme_myntcd_when($ip, $when, $rows = '', $start = '', $stop = '') {
	$output = '';
	if ($stop != '') {
		$date = $start.' - '.$stop;
	} else {
		$date = $start;
		$stop = $start;
	}
	drupal_set_title(t('%title traffic', array('%title' => drupal_get_title())).' ('.$date.')');

	$output .= '<div class="ip_myntcd">'.t('IP: %IP', array('%IP' => $ip) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/img/'.$ip.'/'.$when.'/'.$stop.'" alt="myntcd_'.$when.'_image" />', 'myntcd/'.$ip.'/'.$when.'/'.$stop, array(), NULL, NULL, FALSE, TRUE).'</div>';

	$header = array(array('data' => t('Time')),
		array('data' => t('Type')),
		array('data' => t('In Packet')),
		array('data' => t('Out Packet')),
		array('data' => t('Total Packet')),
		array('data' => t('In Byte')),
		array('data' => t('Out Byte')),
		array('data' => t('Total Byte')),
		array('data' => t('Out%')),
	);
	$output .= theme('table', $header, $rows);

	return $output;
} // function theme_myntcd_when()

/**
 * theme_myntcd_daily
 */
function theme_myntcd_daily($ip, $rows, $date) {
	return theme('myntcd_when', $ip, 'daily', $rows, $date);
} // function theme_myntcd_daily()

/**
 * theme_myntcd_weekly
 */
function theme_myntcd_weekly($ip, $rows, $start, $stop) {
	return theme('myntcd_when', $ip, 'weekly', $rows, $start, $stop);
} // function theme_myntcd_weekly()

/**
 * theme_myntcd_monthly
 */
function theme_myntcd_monthly($ip, $rows, $start, $stop) {
	return theme('myntcd_when', $ip, 'monthly', $rows, $start, $stop);
} // function theme_myntcd_monthly()

/**
 * theme_myntcd_yearly
 */
function theme_myntcd_yearly($ip, $rows, $date) {
	return theme('myntcd_when', $ip, 'yearly', $rows, $date);
} // function theme_myntcd_yearly()

/**
 * theme_myntcd_ip
 */
function theme_myntcd_ip($ip) {
	$output = '';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/img/'.$ip.'/daily" alt="myntcd_daily_image" />', 'myntcd/'.$ip.'/daily', array(), NULL, NULL, FALSE, TRUE).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/img/'.$ip.'/weekly" alt="myntcd_weekly_image" />', 'myntcd/'.$ip.'/weekly', array(), NULL, NULL, FALSE, TRUE).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/img/'.$ip.'/monthly" alt="myntcd_monthly_image" />', 'myntcd/'.$ip.'/monthly', array(), NULL, NULL, FALSE, TRUE).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/img/'.$ip.'/yearly" alt="myntcd_yearly_image" />', 'myntcd/'.$ip.'/yearly', array(), NULL, NULL, FALSE, TRUE).'</div>';
	
	return $output;
} // function theme_myntcd_ip()

/**
 * myntcd_img: rrd grafikont jelenit meg egy adott ip-hez 
 */
function myntcd_img($ip, $type, $end = '') {
	/** Utolso idopont meghatarozasa */
	if ($end == '') {
		$end = strtotime('now');
	} else {
		$end = strtotime($end.' '.date('H:i:s'));
	}
	/** Kep tipusanak megfelelo kezdesi idopont meghatarozasa */
	switch ($type) {
		default:
		case 'daily':
			$start = strtotime('-1 day', $end);
			$title = $ip.' ('.date('Y-m-d', $end).')'; 
		break;
		case 'weekly':
			$start = strtotime('-1 week', $end);
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $end).')'; 
		break;
		case 'monthly':
			$start = strtotime('-1 month', $end);
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $end).')'; 
		break;
		case 'yearly':
			$start = strtotime('-1 year', $end);
			$title = $ip.' ('.date('Y-m-d', $start).' - '.date('Y-m-d', $end).')'; 
		break;
	}
	/** Kep elkeszitese */
	$img = _myntcd_get_rrd_image_myntcd($ip, $title, $start, $end);
} // function myntcd_img()

/** 
 * myntcd_my_traffic: sajat forgalom megjelenitese
 */
function myntcd_my_traffic($when = '', $date = '') {
	global $myntcd_server;
	theme_add_style($path = 'modules/myntcd/style.css', $media = 'all');

	/** Kapcsolodas az SQL szerverhez */
	$db =& DB::connect($myntcd_server);
	if (DB::isError($db)) {
		drupal_set_message( t($db->getMessage()), 'error' );
		return " ";
	}
	$db->setFetchMode(DB_FETCHMODE_ASSOC);

	/** Kliens gep IP cime */
	$my_ip = $_SERVER['REMOTE_ADDR'];
	switch ($when) {
		case '':
			/** Bekoszonto kepernyo */
			$output .= theme('myntcd_my_traffic');
		break;
		case 'daily':
		/** Napi forgalom */
			$date = date('Y-m-d');
			/** A mai nap forgalmi adatai orankenti bontasban */
			$sql = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM now WHERE';
			$sql .= " ip='".$my_ip."' AND date(date) = '".$date."' GROUP BY hour(date) ORDER BY date DESC";
			$result =& $db->query($sql);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, &$rows, &$total, 'H:00');

			/** Osszes napi forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);
			$output .= theme('myntcd_daily_my_traffic', $rows);
		break;

		case 'weekly':
		/** Heti forgalom */
			if ($date != '') {
				drupal_goto('myntcd/top/weekly');
			}
			$date = date('Y-m-d');
			$start_week = date('Y-m-d', strtotime('-1 week'));

			$sql = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM now WHERE';
			$sql .= " ip='".$my_ip."' AND date(date) = '".$date."' GROUP BY date(date) ORDER BY date DESC";
			$result =& $db->query($sql);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, &$rows, &$total, 'Y-m-d');


			$sql = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM daily WHERE';
			$sql .= " ip='".$my_ip."' AND date > '".$start_week."' AND date <= '".$date."' GROUP BY date ORDER BY date DESC";
			$result =& $db->query($sql);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			/** Tablazat sorainak elkesitese */
			_myntcd_get_my_rows($result, &$rows, &$total, 'Y-m-d');

			if ($total['in_byte'] <= $total['out_byte']) {
				$warrning = 'warrning';
			} else {
				$warrning = '';
			}

			/** Osszes heti forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);
			$output .= theme('myntcd_weekly_my_traffic', $rows);
		break;

		case 'monthly':
		/** Havi forgalom */
			if ($date == '') {
				$date = date('Y-m-01');
			}
			if (!_myntcd_chk_date($date)) {
				drupal_goto('myntcd/top/monthly');
			} else {
				$date = date('Y-m-01', strtotime($date));
			}

			if (strtotime('now') < strtotime($date.' +1 month')) {
				$end_month = date('Y-m-d');
			} else {
				$end_month = date('Y-m-d', strtotime($date.' +1 month -1 day'));
			}
			$sql = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM now WHERE';
			$sql .= " ip='".$my_ip."' AND date(date) = '".$end_month."' GROUP BY date(date) ORDER BY date DESC";
			$result =& $db->query($sql);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, &$rows, &$total, 'Y-m-d');


			$sql = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM daily WHERE';
			$sql .= " ip='".$my_ip."' AND date >= '".$date."' AND date <= '".$end_month."' GROUP BY date ORDER BY date DESC";
			$result =& $db->query($sql);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			/** Tablazat sorainak elkesitese */
			_myntcd_get_my_rows($result, &$rows, &$total, 'Y-m-d');

			if ($total['in_byte'] <= $total['out_byte']) {
				$warrning = 'warrning';
			} else {
				$warrning = '';
			}

			/** Osszes havi forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);

			$output .= theme('myntcd_monthly_my_traffic', $rows, $date, $end_month);
		break;

		case 'yearly':
		/** Eves forgalom */
			if ($date != '') {
				drupal_goto('myntcd/top/yearly');
			}
			$date = date('Y-m-d');
			$start_year = date('Y-01-01');
			$sql = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM now WHERE';
			$sql .= " ip='".$my_ip."' AND date(date) = '".$date."' GROUP BY date(date) ORDER BY date DESC";
			$result =& $db->query($sql);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$rows = $total = array();
			$total['in'] = $total['out'] = 0;
			/** Tablazat sorainak elkesitese */
			_myntcd_get_my_rows($result, &$day, &$total, 'Y. F', 1);

			$sql = 'SELECT date, SUM(in_byte) AS in_byte, SUM(out_byte) AS out_byte FROM daily WHERE';
			$sql .= " ip='".$my_ip."' AND date >= '".$start_year."' GROUP BY month(date) ORDER BY date DESC";
			$result =& $db->query($sql);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_my_rows($result, &$rows, &$total, 'Y. F', 1);

			if ($total['in_byte'] <= $total['out_byte']) {
				$warrning = 'warrning';
			} else {
				$warrning = '';
			}

			/** Aktualis honaphoz az aktualis nap forgalmi adatainak hozza adasa */
			if (count($rows)) {
				if ($rows[0][0]['data'] == $day[0][0]['data']) {
					$rows[0][1]['data'] = str_replace(' ', '', rtrim($rows[0][1]['data'], ' MB')) + str_replace(' ', '', rtrim($day[0][1]['data'], ' MB'));
					$rows[0][2]['data'] = str_replace(' ', '', rtrim($rows[0][2]['data'], ' MB')) + str_replace(' ', '', rtrim($day[0][2]['data'], ' MB'));
					$rows[0][3]['data'] = str_replace(' ', '', rtrim($rows[0][3]['data'], ' MB')) + str_replace(' ', '', rtrim($day[0][3]['data'], ' MB'));
					/** 0-val osztas ellen */
					if ($rows[0][3]['data']) {
						$rows[0][4]['data'] = (round($rows[0][2]['data']/$rows[0][3]['data'],2)*100).' %';
					} else {
						$rows[0][4]['data'] = '0 %';
					}
		
					$rows[0][1]['data'] = number_format($rows[0][1]['data'], 2, '.', ' ').' MB';
					$rows[0][2]['data'] = number_format($rows[0][2]['data'], 2, '.', ' ').' MB';
					$rows[0][3]['data'] = number_format($rows[0][3]['data'], 2, '.', ' ').' MB';
				} else {
					if (count($day)) {
						array_unshift($rows, $day[0]);
					}
				} 
			}

			/** Eves forgalom hozza fuzese a tablazathoz */
			_myntcd_get_my_totlal_line($rows, $total);

			$output .= theme('myntcd_yearly_my_traffic', $rows, date('Y'));
		break;
		default:
			drupal_goto('my_traffic');
		break;
	}
	if ($output == '') {
		$output = ' ';
	}

	return $output;
} // function my_traffic_myntcd()

/** 
 * theme_myntcd_my_traffic
 */
function theme_myntcd_my_traffic() {
	$output = '';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/myimg/daily" alt="myntcd_daily_image" />', 'my_traffic/daily', array(), NULL, NULL, FALSE, TRUE).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/myimg/weekly" alt="myntcd_weekly_image" />', 'my_traffic/weekly', array(), NULL, NULL, FALSE, TRUE).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/myimg/monthly" alt="myntcd_monthly_image" />', 'my_traffic/monthly', array(), NULL, NULL, FALSE, TRUE).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/myimg/yearly" alt="myntcd_yearly_image" />', 'my_traffic/yearly', array(), NULL, NULL, FALSE, TRUE).'</div>';
	
	return $output;
}

/**
 * theme_myntcd_when_my_traffic
 */
function theme_myntcd_when_my_traffic($when, $rows, $start, $stop = '') {
	$output = '';
	if ($stop != '') {
		$date = $start.' - '.$stop;
	} else {
		$date = $start;
	}
	drupal_set_title(t('%title traffic', array('%title' => drupal_get_title())).' ('.$date.')');

	$output .= '<div class="my_ip_myntcd">'.t('My ip: %IP', array('%IP' => $_SERVER['REMOTE_ADDR']) ).'</div>';
	$output .= '<div class="myntcd_rrd_img">'.l('<img src="myntcd/myimg/'.$when.'" alt="myntcd_'.$when.'_image" />', 'my_traffic/'.$when, array(), NULL, NULL, FALSE, TRUE).'</div>';

	$header = array(array('data' => t('Time')),
		array('data' => t('In Byte')),
		array('data' => t('Out Byte')),
		array('data' => t('Total Byte')),
		array('data' => t('Out%')),
	);
	$output .= theme('table', $header, $rows);
	return $output;
	
} // function theme_myntcd_when_my_traffic()

/**
 * theme_myntcd_daily_my_traffic
 */
function theme_myntcd_daily_my_traffic($rows) {
	return theme('myntcd_when_my_traffic', 'daily', $rows, date('Y-m-d'));
} // function theme_daily_my_traffic_myntcd()

/**
 * theme_myntcd_weekly_my_traffic
 */
function theme_myntcd_weekly_my_traffic($rows) {
	return theme('myntcd_when_my_traffic', 'weekly', $rows, date('Y-m-d', strtotime('-6 day')), date('Y-m-d'));
} // function theme_monthly_my_traffic_myntcd()

/**
 * theme_myntcd_monthly_my_traffic
 */
function theme_myntcd_monthly_my_traffic($rows, $start, $stop) {
	return theme('myntcd_when_my_traffic', 'monthly', $rows, $start, $stop);
} // function theme_monthly_my_traffic_myntcd()

/**
 * theme_myntcd_yearly_my_traffic
 */
function theme_myntcd_yearly_my_traffic($rows, $date) {
	return theme('myntcd_when_my_traffic', 'yearly', $rows, $date);
} // function theme_monthly_my_traffic_myntcd()

/**
 * myntcd_myimg
 */
function myntcd_myimg($type) {
	myntcd_img($_SERVER['REMOTE_ADDR'], $type);
} // function myimg_myntcd()

/**
 * myntcd_filter: IP cim szures konfiguralasa
 */
function myntcd_filter() {
	global $myntcd_server;

	/** Kapcsolodas az SQL szerverhez */
	$db =& DB::connect($myntcd_server);
	if (DB::isError($db)) {
		drupal_set_message( t($db->getMessage()), 'error' );
		return " ";
	}
	$db->setFetchMode(DB_FETCHMODE_ASSOC);

	$sql = 'SELECT * FROM filter ORDER BY ip';
	$result =& $db->query($sql);
	if (DB::isError($result)) {
		drupal_set_message( t($result->getMessage()), 'error' );
		return " ";
	}

	/** tiltott es engedelyezett ip cimek lekerdezese, szetvalogatasa */
	$form_values['blacklist_ip'] = array();
	$form_values['whitelist_ip'] = array();
	while ($row =& $result->fetchRow()) {
		if ($row['date'] == '0000-00-00') {
			$row['date']= t('never');
		}
		if ($row['blacklist']) {
			$form_values['blacklist_ip'][$row['ip']] = $row['ip'].' ('.t('Remove day:').' '.$row['date'].')';
		} else {
			$form_values['whitelist_ip'][$row['ip']] = $row['ip'].' ('.t('Remove day:').' '.$row['date'].')';
		}
	}
	
	if (!count($form_values['blacklist_ip'])) {
		$form_values['blacklist_ip']['empty'] = t('Empty');
	}
	if (!count($form_values['whitelist_ip'])) {
		$form_values['whitelist_ip']['empty'] = t('Empty');
	}
	
	/** Tiltott cimek engedelyezese */
	$form['blacklist_myntcd'] = array(
		'#type' => 'fieldset',
		'#title' => t('Blacklist'),
		'#collapsible' => TRUE,
		'#collapsed' => false,
	);
	$form['blacklist_myntcd']['blacklist_ip'] = array(
		'#type' => 'select',
		'#title' => t('Ip address'),
		'#options' => $form_values['blacklist_ip'],
		'#required' => false,
	);
	$form['blacklist_myntcd']['blacklist_ip'] = array(
		'#type' => 'select',
		'#title' => t('Ip address'),
		'#options' => $form_values['blacklist_ip'],
		'#required' => false,
	);
	$form['blacklist_myntcd']['submit'] = array('#type' => 'submit', '#value' => t('Add whitelist'));
	$output .= drupal_get_form('myntcd_filter', $form); 

	/** Engedelyezett cimek, tiltasa/torlese */
	$form = array();
	$form['whitelist_myntcd'] = array(
		'#type' => 'fieldset',
		'#title' => t('Whitelist'),
		'#collapsible' => TRUE,
		'#collapsed' => false,
	);
	$form['whitelist_myntcd']['whitelist_ip'] = array(
		'#type' => 'select',
		'#title' => t('Ip address'),
		'#options' => $form_values['whitelist_ip'],
		'#required' => false,
	);
	$form['whitelist_myntcd']['submit'] = array('#type' => 'submit', '#value' => t('Remove whitelist'));
	$output .= drupal_get_form('myntcd_filter', $form); 

	/** Uj szures hozza adasa */
	$form = array();
	$form['filter_myntcd'] = array(
		'#type' => 'fieldset',
		'#title' => t('Add filter'),
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);
	$form['filter_myntcd']['filter_ip'] = array(
		'#type' => 'textfield',
		'#title' => t('Ip address'),
		'#size' => 20,
		'#maxlength' => 15,
		'#required' => true,
	);
	$form['filter_myntcd']['filter_type'] = array(
		'#type' => 'select',
		'#title' => t('Type'),
		'#options' => array(1 => t('Blacklist'), 0 => t('Whitelist')),
		'#required' => false,
	);
	$form['filter_myntcd']['filter_time'] = array(
		'#type' => 'select',
		'#title' => t('time interval'),
		'#options' => array('1' => '1 '.t('day'), '2' => '2 '.t('day'), '5' => '5 '.t('day'), '7' => '1 '.t('week'), '14' => '2 '.t('week'), '30' => '1 '.t('month'), '-1' => t('for ever')),
		'#required' => false,
	);

	$form['filter_myntcd']['submit'] = array('#type' => 'submit', '#value' => t('Save'));
	$output .= drupal_get_form('myntcd_filter', $form); 
	return $output;
} // function myntcd_filter()

/**
 * myntcd_filter_submit
 */
function myntcd_filter_submit($form_id, $form) {
	global $myntcd_server, $_POST;

	$db =& DB::connect($myntcd_server);
	if (DB::isError($db)) {
		drupal_set_message( t($db->getMessage()), 'error' );
		return " ";
	}
	$db->setFetchMode(DB_FETCHMODE_ASSOC);

	/** Kivalasztott form meghatarozasa. */
//	switch ($form['submit']) {
	switch ($_POST['op']) {
		case t('Add whitelist'):
		/** Levesz a tilto listarol */
			if ($form['blacklist_ip'] != 'empty') {
				$sql = "UPDATE filter SET blacklist=0 WHERE ip = ?";
				$result =& $db->query($sql, array($form['blacklist_ip']));
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
			}
		break;
		case t('Remove whitelist'):
		/** Levesz az engefelyezettek listajarol */
			if ($form['whitelist_ip'] != 'empty') {
				$sql = "UPDATE filter SET blacklist=1 WHERE ip = ? AND date > '0000-00-00'";
				$result =& $db->query($sql, array($form['whitelist_ip']));
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}

				$sql = "DELETE FROM filter WHERE ip = ? AND date = '0000-00-00'";
				$result =& $db->query($sql, array($form['whitelist_ip']));
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
			}
		break;
		case t('Save'):
		/** Uj szurest tesz fel */
			if (_myntcd_is_ip($form['filter_ip'])) { 
			
				$sql = "INSERT INTO filter (ip, blacklist, date) VALUES (?, ?, ?)";
				if ($form['filter_time'] == '-1') {
					$form['filter_time'] = '0000-00-00';
				} else {
					$form['filter_time'] = date('Y-m-d', strtotime('+'.$form['filter_time'].' day'));
				}
				$result =& $db->query($sql, array($form['filter_ip'], $form['filter_type'], $form['filter_time']));
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
			}
		break;
	}
	drupal_goto('myntcd/filter');
	return;
} // function myntcd_filter_submit()

/**
 * _myntcd_traffic2tmptable: megadott intervallum forgalmat IP cimenkent osszegyujti
 * @param db adatbazis kapcsolat
 * @param start megadott idoponttol
 * @param stop megadott idopontig
 */
function _myntcd_traffic2tmptable(&$db, $start, $stop = '') {
	/** Seged tabla definialasa */
	if ($stop == '') {
		$stop = date('Y-m-d');
	}
	$SQL = "CREATE TEMPORARY TABLE tmp_table";
	$SQL .= " ( `ip` varchar(15) default NULL, `in_byte` bigint(20) unsigned NOT NULL default '0',";
	$SQL .= "  `out_byte` bigint(20) unsigned NOT NULL default '0')";
	$result =& $db->query($SQL);
	if (DB::isError($result)) {
		drupal_set_message( t($result->getMessage()), 'error' );
		return " ";
	}

	/** aktualis nap adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO tmp_table SELECT ip, SUM(in_byte), SUM(out_byte) FROM now";
	$SQL .= " WHERE date(date) = ? GROUP BY ip";
	$result =&$db->query($SQL, array($stop));
	if (DB::isError($result)) {
		die($result->getMessage());
	}

	/** megadott ido intervallum adatainak betoltese a seged tablaba */
	$SQL = "INSERT INTO tmp_table SELECT ip, SUM(in_byte), SUM(out_byte) FROM daily";
	$SQL .= " WHERE date >= ? AND date <= ? GROUP BY ip";
	$result =&$db->query($SQL, array($start, $stop));
	if (DB::isError($result)) {
		die($result->getMessage());
	}
} // function _myntcd_traffic2tmptable()

/**
 * myntcd_top: toplistak
 */
function myntcd_top($when = '', $date = '') {
	global $myntcd_server;
	theme_add_style($path = 'modules/myntcd/style.css', $media = 'all');

	/** Kapcsolodas az SQL szerverhez */
	$db =& DB::connect($myntcd_server);
	if (DB::isError($db)) {
		drupal_set_message( t($db->getMessage()), 'error' );
		return " ";
	}
	$db->setFetchMode(DB_FETCHMODE_ASSOC);

	/** Melyik idoszakra vagyunk kivancsiak */
	switch ($when) {
		case 'daily':
		/** Napi toplista */
			if ($date == '') {
				$date = date('Y-m-d');
			}
			if (!_myntcd_chk_date($date)) {
				drupal_goto('myntcd/top/daily');
			}
			/** Napnak megfelelo adatbazis kivalasztasa */
			if ($date == date('Y-m-d')) {
				$from = " FROM now";
			} else {
				$from = " FROM daily";
			}

			/** Top lista: kimeno forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= $from." WHERE date(date) = ? GROUP BY ip, date(date) ORDER BY ? DESC";
			$data = array($date, 'out_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			$tables['out'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['out'], $when);

			/** Top lista: bejovo forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= $from." WHERE date(date) = ? GROUP BY ip, date(date) ORDER BY ? DESC";
			$data = array($date, 'in_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['in'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['in'], $when);

			/** Top lista: teljes forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= $from." WHERE date(date) = ? GROUP BY ip, date(date) ORDER BY ? DESC";
			$data = array($date, 'total');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['total'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['total'], $when);

			$output .= theme('myntcd_daily_top', $tables, $date);
		break;

		case 'weekly':
		/** Heti toplista */
			$date = date('Y-m-d');
			$start_week = date('Y-m-d', strtotime('-1 week'));

			/** Seged tabla definialasa es feltoltese */
			_myntcd_traffic2tmptable(&$db, $start_week);

			/** Top lista: kimeno forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('out_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			$tables['out'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['out'], $when);

			/** Top lista: bejovo forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('in_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['in'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['in'], $when);

			/** Top lista: teljes forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('total');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['total'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['total'], $when);

			$output .= theme('myntcd_weekly_top', $tables, $start_week, $date);
		break;

		case 'monthly':
		/** Havi toplista */
			if ($date == '') {
				$date = date('Y-m-01');
			}
			if (!_myntcd_chk_date($date)) {
				drupal_goto('myntcd/top/month');
			} else {
				$date = date('Y-m-01', strtotime($date));
			}

			if (strtotime('now') < strtotime($date.' +1 month')) {
				$end_month = date('Y-m-d');
			} else {
				$end_month = date('Y-m-d', strtotime($date.' +1 month -1 day'));
			}

			/** Seged tabla definialasa es feltoltese */
			_myntcd_traffic2tmptable(&$db, $date, $end_month);

			/** Top lista: kimeno forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('out_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			$tables['out'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['out'], $when);

			/** Top lista: bejovo forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('in_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['in'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['in'], $when);

			/** Top lista: teljes forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('total');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['total'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['total'], $when);

			$output .= theme('myntcd_monthly_top', $tables, $date, $end_month);
		break;

		case 'yearly':
		/** Eves toplista */
			$date = date('Y-m-d');
			$start_year = date('Y-01-01');
			/** Seged tabla definialasa es feltoltese */
			_myntcd_traffic2tmptable(&$db, $start_year);

			/** Top lista: kimeno forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('out_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			$tables['out'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['out'], $when);

			/** Top lista: bejovo forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('in_byte');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['in'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['in'], $when);

			/** Top lista: teljes forgalom */
			$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
			$SQL .= " FROM tmp_table GROUP BY ip ORDER BY ? DESC";
			$data = array('total');
			$result =& $db->limitQuery($SQL, 0, 20, $data);
			if (DB::isError($result)) {
				drupal_set_message( t($result->getMessage()), 'error' );
				return " ";
			}
			
			$tables['total'] = array();
			/** Tablazat sorainak elkeszitese */
			_myntcd_get_ip_rows($result, &$tables['total'], $when);

			$output .= theme('myntcd_yearly_top', $tables, $start_year, $date);
		break;
		default:
		/** Bekoszonto kepernyo */
			if ($when == '') {
				$date = date('Y-m-d');

				/** Napi Top lista */
				$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
				$SQL .= " FROM now WHERE date(date) = ? GROUP BY ip, date(date) ORDER BY ? DESC";
				$data = array($date, 'total');
				$result =& $db->limitQuery($SQL, 0, 20, $data);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				
				$tables['total'] = array();
				/** Tablazat sorainak elkeszitese */
				_myntcd_get_ip_rows($result, &$tables['daily'], 'daily');
	
				$start_month = date('Y-m-01');
				$start_year = date('Y-01-01');
				/** Seged tabla definialasa */			
				$SQL = "CREATE TEMPORARY TABLE tmp_table";
				$SQL .= " ( `ip` varchar(15) default NULL, `date` DATE, `in_byte` bigint(20) unsigned NOT NULL default '0',";
				$SQL .= "  `out_byte` bigint(20) unsigned NOT NULL default '0')";
				$result =& $db->query($SQL);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
	
				/** aktualis nap adatainak betoltese a seged tablaba */
				$SQL = "INSERT INTO tmp_table SELECT ip, date(date), SUM(in_byte), SUM(out_byte) FROM now";
				$SQL .= " WHERE date(date) = ? GROUP BY ip";
				$data = array($date);
				$result =&$db->query($SQL, $data);
				if (DB::isError($result)) {
					die($result->getMessage());
				}
	
				/** aktualis ev adatainak betoltese a seged tablaba */
				$SQL = "INSERT INTO tmp_table SELECT ip, date, SUM(in_byte), SUM(out_byte) FROM daily";
				$SQL .= " WHERE date > ? AND date <= ? GROUP BY ip, date";
				$data = array($start_year, $date);
				$result =&$db->query($SQL, $data);
				if (DB::isError($result)) {
					die($result->getMessage());
				}
	
				/** Havi Top lista */
				$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
				$SQL .= " FROM tmp_table WHERE date >= ? AND date <= ? GROUP BY ip  ORDER BY ? DESC";
				$data = array($start_month, $date, 'total');
				$result =& $db->limitQuery($SQL, 0, 20, $data);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				
				$tables['total'] = array();
				/** Tablazat sorainak elkeszitese */
				_myntcd_get_ip_rows($result, &$tables['monthly'], 'monthly');

				/** Eves Top lista */
				$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total";
				$SQL .= " FROM tmp_table WHERE date >= ? AND date <= ? GROUP BY ip  ORDER BY ? DESC";
				$data = array($start_year, $date, 'total');
				$result =& $db->limitQuery($SQL, 0, 20, $data);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				
				$tables['total'] = array();
				/** Tablazat sorainak elkeszitese */
				_myntcd_get_ip_rows($result, &$tables['yearly'], 'yearly');

				$output .= theme('myntcd_top', $tables);
			} else {
				drupal_goto('myntcd');
			}
		
		break;
	}
	if ($output == '') {
		$output = ' ';
	}

	return $output;
} // function myntcd_top()

/**
 * theme_myntcd_when_top
 */
function theme_myntcd_when_top($tables, $when, $start, $stop = '') {
	$output = '';

	if ($stop != '') {
		$date = $start.' - '.$stop;
	} else {
		$date = $start;
	}
	drupal_set_title(t($when.' Top %num', array('%num' => '20')).' ('.$date.')');

	$header = array(array('data' => t('Time')),
		array('data' => t('In Byte')),
		array('data' => t('Out Byte')),
		array('data' => t('Total Byte')),
		array('data' => t('Out%')),
	);
	$output .= '<div class = "myntcd_top_label">'.t($when.' Top %num in byte', array('%num' => '20')).':</div>';
	$output .= '<div id = "myntcd_in_top_table">';
	$output .= theme('table', $header, $tables['in']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t($when.' Top %num out byte', array('%num' => '20')).':</div>';
	$output .= '<div id = "myntcd_out_top_table">';
	$output .= theme('table', $header, $tables['out']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t($when.' Top %num total byte', array('%num' => '20')).':</div>';
	$output .= '<div id = "myntcd_total_top_table">';
	$output .= theme('table', $header, $tables['total']);
	$output .= '</div>';

	return $output;
} // function theme_myntcd_when_top()

/**
 * theme_myntcd_daily_top
 */
function theme_myntcd_daily_top($tables, $date) {
	return theme('myntcd_when_top', $tables, 'Daily', $date);
} // function theme_myntcd_daily_top()

/**
 * theme_myntcd_weekly_top
 */
function theme_myntcd_weekly_top($tables, $start, $stop) {
	return theme('myntcd_when_top', $tables, 'Weekly', $start, $stop);
} // function theme_myntcd_weekly_top()

/**
 * theme_myntcd_monthly_top
 */
function theme_myntcd_monthly_top($tables, $start, $stop) {
	return theme('myntcd_when_top', $tables, 'Monthly', $start, $stop);
} // function theme_myntcd_monthly_top()

/**
 * theme_myntcd_yearly_top
 */
function theme_myntcd_yearly_top($tables, $start, $stop) {
	return theme('myntcd_when_top', $tables, 'Yearly', $start, $stop);
} // function theme_myntcd_yearly_top()

/**
 * theme_myntcd_top
 */
function theme_myntcd_top($tables) {
	$output = '';

	$header = array(array('data' => t('Time')),
		array('data' => t('In Byte')),
		array('data' => t('Out Byte')),
		array('data' => t('Total Byte')),
		array('data' => t('Out%')),
	);
	$output .= '<div class = "myntcd_top_label">'.t('Daily Top %num total byte', array('%num' => '20')).':</div>';
	$output .= '<div id = "myntcd_in_top_table">';
	$output .= theme('table', $header, $tables['daily']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t('Monthly Top %num total byte', array('%num' => '20')).':</div>';
	$output .= '<div id = "myntcd_out_top_table">';
	$output .= theme('table', $header, $tables['monthly']);
	$output .= '</div>';
	$output .= '<div class = "myntcd_top_label">'.t('Yearly Top %num total byte', array('%num' => '20')).':</div>';
	$output .= '<div id = "myntcd_total_top_table">';
	$output .= theme('table', $header, $tables['yearly']);
	$output .= '</div>';

	return $output;
} // function theme_myntcd_top() 

/**
 * myntcd_iprange: ip cim tartomanyok forgalmi adatai
 */
function myntcd_iprange($ip, $when = '') {
	global $myntcd_server;
	theme_add_style($path = 'modules/myntcd/style.css', $media = 'all');

	/** Kapcsolodas az SQL szerverhez */
	$db =& DB::connect($myntcd_server);
	if (DB::isError($db)) {
		drupal_set_message( t($db->getMessage()), 'error' );
		return " ";
	}
	$db->setFetchMode(DB_FETCHMODE_ASSOC);

	$output = '';
	/** Az atadott parameter IP cim */
	if (_myntcd_is_ip($ip.'.0') && $when != '') {
		$rows = array();
		switch ($when) {
			case 'daily':
			/** IP tartomanyhoz tartozo napi forgalom */
				$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM now WHERE date(date) = ? AND substring(ip,1,length(ip)-locate('.',reverse(ip))) = ? GROUP BY ip ORDER BY total DESC";
				$result =& $db->query($SQL, array(date('Y-m-d'), $ip) );
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-m-d');
			break;
			case 'weekly':
			/** IP tartomanyhoz tartozo heti forgalom */
				$start_week = date('Y-m-d', strtotime('-1 week'));

				/** Seged tabla definialasa es feltoltese */
				_myntcd_traffic2tmptable(&$db, $start_week);

				$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM tmp_table WHERE substring(ip,1,length(ip)-locate('.',reverse(ip))) = ? GROUP BY ip ORDER BY total DESC";
				
				$result =& $db->query($SQL, array($ip) );
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-m-d', strtotime('-1 week +1 day')).' - '.date('Y-m-d');
			break;
			case 'monthly':
			/** IP tartomanyhoz tartozo havi forgalom */
				/** Seged tabla definialasa es feltoltese */
				_myntcd_traffic2tmptable(&$db, date('Y-m-01'));

				$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM tmp_table WHERE substring(ip,1,length(ip)-locate('.',reverse(ip))) = ? GROUP BY ip ORDER BY total DESC";
				$result =& $db->query($SQL, array($ip) );
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-m-01').' - '.date('Y-m-d');
			break;
			case 'yearly':
			/** IP tartomanyhoz tartozo eves forgalom */
				/** Seged tabla definialasa es feltoltese */
				_myntcd_traffic2tmptable(&$db, date('Y-01-01'));

				$SQL = "SELECT ip, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM tmp_table WHERE substring(ip,1,length(ip)-locate('.',reverse(ip))) = ? GROUP BY ip ORDER BY total DESC";
				$result =& $db->query($SQL, array($ip) );
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-01-01').' - '.date('Y-m-d');
			break;
			default:
				drupal_goto('myntcd');
			break;
		}
		/** SQL lekerdezes feldolgozasa */
		_myntcd_get_ip_rows($result, &$rows, $when);
		$output .= theme('myntcd_iprange', $rows, $when, $date);
	} elseif ( ($ip == 1) && ($when != '') ) {
	/** Ha a tartomanyok adataira vagyunk kivancsiak */
		$rows = array();
		switch ($when) {
			case 'daily':
				$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS ip_range, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM now WHERE date(date) = ? GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
				$result =& $db->query($SQL, array(date('Y-m-d')) );
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-m-d');
			break;
			case 'weekly':
				$start_week = date('Y-m-d', strtotime('-1 week'));

				/** Seged tabla definialasa es feltoltese */
				_myntcd_traffic2tmptable(&$db, $start_week);


				$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS ip_range, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM tmp_table GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
				$result =& $db->query($SQL);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-m-d', strtotime('-1 week +1 day')).' - '.date('Y-m-d');
			break;
			case 'monthly':
				/** Seged tabla definialasa es feltoltese */
				_myntcd_traffic2tmptable(&$db, date('Y-m-01'));

				$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS ip_range, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM tmp_table GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
				$result =& $db->query($SQL);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-m-01').' - '.date('Y-m-d');
			break;
			case 'yearly':
				/** Seged tabla definialasa es feltoltese */
				_myntcd_traffic2tmptable(&$db, date('Y-01-01'));

				$SQL = "SELECT substring(ip,1,length(ip)-locate('.',reverse(ip))) AS ip_range, SUM(in_byte) as in_byte, SUM(out_byte) as out_byte, SUM(in_byte)+SUM(out_byte) as total ";
				$SQL .= " FROM tmp_table GROUP BY substring(ip,1,length(ip)-locate('.',reverse(ip))) ORDER BY ip";
				$result =& $db->query($SQL);
				if (DB::isError($result)) {
					drupal_set_message( t($result->getMessage()), 'error' );
					return " ";
				}
				$date = date('Y-01-01').' - '.date('Y-m-d');
			break;
			default:
				drupal_goto('myntcd');
			break;
		}
		/** SQL lekerdezes feldolgozasa */
		_myntcd_get_ip_rows($result, &$rows, $when, 'ip_range');
		$output .= theme('myntcd_iprange', $rows, $when, $date);
	} else {
		$output = ' ';
	}

	return $output;
} // function myntcd_iprange()

/**
 * theme_myntcd_iprange
 */
function theme_myntcd_iprange($rows, $when, $date) {
	$output = '';
	drupal_set_title(t('%title traffic', array('%title' => drupal_get_title())).' ('.$date.')');

	$header = array(array('data' => t('IP')),
		array('data' => t('In Byte')),
		array('data' => t('Out Byte')),
		array('data' => t('Total Byte')),
		array('data' => t('Out%')),
	);
	$output .= '<div id = "myntcd_in_top_table">';
	$output .= theme('table', $header, $rows);
	$output .= '</div>';

	return $output;
} // function theme_myntcd_iprange()

?>